# Cultural Evolution {#cultural-evolution}

## Definition und Geschichte

Die Grundaussage der *Cultural evolution theory* ist, dass die Prozesse der natürlichen Entwicklung von Spezies durch Evolution auch bei der menschlichen Kulturentwicklung wirken. Mechanismen der Evolution wie Selektion und Mutation wären entscheidend dafür, welche Verhaltensweisen, Ideen und Innovationen sich langfristig durchsetzen könnten. Entsprechend könnte biologische Terminologie und Modellbildung zumindest eingeschränkt auch in anthropologischen Kontexten sinnvoll eingesetzt werden. 

Cultural evolution theory wird in der archäologischen Fachliteratur vor allem als *Darwinian Archaeology* oder *Evolutionary Archaeology* diskutiert. Daneben gab und gibt es in der Forschungsgeschichte eine ganze Reihe weiterer Begriffe und Schulen, die mit dem Evolutionsbegriff verknüpft sind. Das ist kein rein archäologisches Forschungsgebiet: Unter anderem Verhaltensbiologie, Neurologie, Genetik, Soziologie und alle Anthropologischen Fächer sind betroffen und haben sich an dieser Diskussion beteiligt. Die Übertragung biologisch-evolutiver Wirkmechanismen zur Erklärung menschlichen Verhaltens war bereits Gegenstand akademischer Debatte, lange bevor Charles Darwins (\*1809 - \†1882) Evolutionstheorie mit den Standardwerken *On the Origin of Species* ^[@Darwinoriginspeciesmeans1859] und *The Descent of Man*^[@Darwindescentmanselection1871] in Fachwelt und Öffentlichkeit verarbeitet wurden^[@petermann_geschichte_2004, 501-502.]: Parallel zu den Entwicklungen in den Naturwissenschaften -- allerdings mit allgemein geringen Wechselwirkungen -- wurde Evolutionstheorie im wissenschaftichen Diskurs der Sozialwissenschaften reflektiert. Eine erste wesentliche Spannungslinie, die hier betrachtet werden muss, reicht von *Evolutionismus* über *Neoevolutionismus* hin zu *Kulturrelativismus* und *Multilinearer Evolution*. Sie hat in der archäologischen Theoriediskussion große Wirkung entfaltet und ist untrennbar mit der Geschichte des Faches verknüpft. 

### Evolutionsbiologie: Von Darwinismus zu Erweiterter Synthese {#biology}

Die biologische Forschung ist nicht bei Charles Darwin stehen geblieben sondern hat sich über die Korrekturen im *Neo-Darwinismus* um 1890, über die *Synthetische Theorie der biologischen Evolution* um 1940 und die *Erweiterte Synthetischen Theorie* ab dem Ende der 1990er bis in die Gegenwart weiterentwickelt. Ende des 19. Jahrhunderts wurden wesentliche Aspekte biologischen Evolutionstheorie noch kontrovers diskutiert^[@bowler_evolution_1989, 188-202.]. Insbesondere der Streit zwischen darwinistischer Evolution durch Selektion und *lamarckistischer Evolution* durch Vererbung erworbener Eigenschaften war nicht entschieden. Jean-Baptiste de Lamarck (\*1744 - \†1829) war zwar weitestgehend überholt, aber sein Adaptionsgedanke lebte in *Neo-Lamarckismus*^[@bowler_evolution_1989, 236-247.] und *Orthogenese*^[@bowler_evolution_1989, 247-250.] fort, die als Alternativen für den vor allem von August Weismann (\*1834 - \†1914) und Alfred Russel Wallace (\*1823 - \†1913) propagierten *Neo-Darwinismus*^[@bowler_evolution_1989, 251-260.] diskutiert wurden. Weismann vertrat einen dogmatischen *Selektionismus* und führte mit der *Keimplasmatheorie* eine Erklärung für Vererbung ein, die wichtige Aspekte der Genetik vorwegnahm und lamarckistische Adaption ausschloss. Die frühe *Genetik* ging jedoch nicht aus darwinistischem Selektionismus hervor. Stattdessen wurde die Wiederentdeckung der bereits von Gregor Mendel (\*1822 - \†1884) 1866 publizierten *Mendelschen Vererbungsregeln* um 1900 vor allem im Kontext der *Saltationstheorie* diskutiert, die nicht Selektion, sondern tiefgreifende, spontane Mutationen als Motor der Evolution favorisierte^[@bowler_evolution_1989, 260-261.]. Ein bekannter, streitbarer Vertreter dieser Schule war William Bateson (\*1861 - \†1926). Er prägte den Begriff *Genetik* und trug maßgeblich zur Popularisierung der Mendelschen Regeln bei. Ihm entgegen stand die ebenfalls noch junge Wissenschaft der *Biometrie*, die statistische Methoden zur Untersuchung von Populationen einführte und die Bedeutung von Selektion hervorhob. Darwins Cousin Francis Galton (\*1822 - \†1911) gilt als Vorreiter dieser Strömung, vertrat aber eine fehlerhafte, inkohärente Vererbungslehre. Erst Nachfolgern wie Walter Frank Raphael Weldon (\*1860 - \†1906) und Karl Pearson (\*1857 - \†1936) gelang der Nachweis, dass Selektion zur nachhaltiger Veränderung in Populationen führen kann^[@bowler_evolution_1989, 256-260.]. Die Debatte um den genauen Mechanismus der Evolution war entscheidend für die Biologie im späten 19. und frühen 20. Jahrhundert -- die Interdepenzen von Mutation, Adaption und Selektion waren noch nicht verstanden. 

In den ersten Jahrzehnten des 20. Jahrhunderts wurde Hugo de Vries (\*1848 - \†1935) *Mutationstheorie* die in Fachkreisen am weitesten verbreitete Evolutionstheorie. Nach de Vries funktioniert Mutation wie in der  *Saltationstheorie* als schnelles Hervobringen neuer, vollständiger Varianten, die dann durch Selektion sortiert werden. Viele seiner Anhänger verwarfen die Notwendigkeit für Selektion jedoch -- so z.B. Thomas Hunt Morgan (\*1866 - \†1945) oder Wilhelm Johannsen (\*1857 - \†1927), die moralisch und inhaltlich gegen eine tragende Rolle von Selektion argumentierten und gleichzeitig wesentliche Beiträge zur Definition der Vererbungseinheiten im Kontext der noch jungen *Genetik* leisteten. Morgans Forschung an Fruchtfliegen führte zu einem signifikant besseren Verständnis von Vererbung, das den langen Konflikt zwischen Mendelianern und Biometrikern effektiv löste. Ab 1920 setzten sich in Großbritannien und den USA *Präformationslehre* und die Mechanismen *Natürliche Selektion* und kleinteilige, zufällige *Mutation* als die wesentlichen, theoretischen Grundlagen der Evolution der Arten durch, nachdem alle anderen zuvor diskutierten Theorien weitestgehend ausgeschlossen worden waren. In einzelnen Fachbereichen und in Kontinentaleuropa wurden alternative Ansätze -- insbesondere *lamarckistische Evolution* -- allerdings noch wesentlich länger diskutiert und gelehrt^[@bowler_evolution_1989, 268-273.]. Der nun folgende Prozess der Konsolidierung und Vereinheitlichung der Evolutionstheorie in allen Subdisziplinen der Biologie dauerte bis in die 40er Jahre an und wird als *Synthese* bezeichnet. Sie entwickelte sich aus einem langjähriger akademischen Diskurs in vielen wesentlichen Publikationen. Letztlich ging aus ihr die moderne Evolutionsbiologie hervor und viele Bereiche wie Paläontologie, Populationsbiologie und die botanische und zoologische Feldforschung erhielten deutliche Anstöße -- auch zur Quantifizierung und Systematisierung von Forschung. Die *Synthese* wurde von Protagonisten wie Julian S. Huxley (\*1887-\†1975), Sewall G. Wright (\*1889 - \†1988), Ronald A. Fisher (\*1890 - \†1962), John B. S. Haldane (\*1892-\†1964), Theodosius G. Dobzhansky (\*1900-\†1975), Bernhard Rensch (\*1900-\†1990), Edmund B. Ford (\*1901 - \†1988), George G. Simpson (\*1902-\†1984) und neben vielen anderen vor allem Ernst Mayr (\*1904 - \†2005) getragen. Trotz ihrer augenscheinlich anregenden Wirkung verblieb berechtigte Kritik an der *Synthetischen Evolutionstheorie*: Der rigide durchgesetzte Schwerpunkt auf Selektionismus auf Darwinismus führte etwa zunächst zu einer globalen Ablehnung später rehabilitierter Phänomene wie zum Beispiel *Genetischer Drift*^[@bowler_evolution_1989, 325-327 & 333-339.]. 

Ab den späten 1990ern und besonders nach der Jahrtausendwende wurde immer häufiger der Wunsch nach einer Erneuerung des Paradigmas des *Modernen Synthese* artikuliert. Die Methoden und Erkenntnismöglichkeiten der biologischen Subdisziplinen hatten sich massiv weiterentwickelt, und es schien sinnvoll, die alten Maximen zu ersetzen oder zumindest zu erweitern. Die Diskussion um diese *Erweiterte Synthese* hält bis in Gegenwart an. Wesentliche Konzepte, die die alte *Synthese* noch nicht kennen konnte, sind zum Beispiel *Evolvierbarkeit*^[@wagner_robustness_2013], *phänotypische Plastizität*^[@pigliucci_phenotypic_2001] oder der neue aufgegriffene Fachbereich der Evolutionären Entwicklungsbiologie (*EvoDevo*)^[@muller_evodevo_2007]. Ihre Integration und die Reflexion über die Mechanismen der Artenentwicklung wird auch in Zukunft Gegenstand der biologischen Fachdiskussion bleiben^[@pigliucci_elements_2010].

### Evolutionismus und Sozialdarwinismus

Klassischer *Evolutionismus* ist ein Überbegriff für die erste Übertragung biologischer Evolutionsforschung auf die Kulturgeschichte. Er betont den Aspekt des schrittweisen, kulturellen Aufstiegs und der Zunahme organisatorischer Komplexität. Zivilisation hätte sich über mehrere Fortschrittssstufen von einem primitiven Urzustand zur modernen Industriegesellschaft weiterentwickelt. Die Beschreibung einer Kultur kann vor diesem Hintergrund in sehr einfachen Begriffen und mit wenigen Parametern erfolgen^[@noauthor_evolutionismus_1986]. Bei der ersten Formulierung Evolutionistischer Theorie hat Darwin nur eine untergeordnete Rolle gespielt. Protagonisten wie Herbert Spencer (\*1820 - \†1903) und John Lubbok (\*1834 - \†1913) orientierten sich stärker an Charles Lyell (\*1797 - \†1875), der in der ersten Hälfte des 19. Jahrhunderts mit den geologischen Schlüsselprinzipien *Aktualismus* (rezente, natürliche Phänomene haben so auch in der Vergangenheit stattgefunden) und *Gradualismus* (geologischer Wandel ist langsam und stetig) wesentliche Grundlagen für die Evolutionsforschung gelegt hatte. Die Prinzipien gaben der stratigraphischen Vergesellschaftung menschlicher Skelettüberreste mit Pleistozänen Tierknochen eine neue Bedeutung, die eine auf breiter Front *vergleichende Methode* rechtfertigte. Damit wurden vorgeschichtliche Gesellschaften dem Vergleich mit 'primitiven', rezenten Gesellschaften zugänglich. Evolutionismus konzentrierte sich nicht auf Mechanismen der Evolution wie Mutation und Selektion, sondern griff ein dem Kapitalismus entlehntes Konzept von Wettbewerb und Weiterentwicklung der Kulturen auf, das durch Vergleich mit rezenten Gesellschaften und deren Organisationsgrad versteh- und kategorisierbar geworden war. Die Evolutionisten bildeten keine kohärente Schule. Stattdessen wurde eine Gruppe von Individuen -- maßgeblich Lewis Henry Morgan (\*1818 - \†1881), Herbert Spencer, John Ferguson McLennan (\*1827 - \†1881), Edward Burnett Tylor (\*1832 - \†1917) und John Wesley Powell (\*1834 - \†1902) -- abschätzig von Gegnern mit diesem Begriff belegt. Dem Evolutionismus wurde vorgeworfen, die Aussagekraft materieller Kultur über die soziale Organisation vorgeschichtlicher Gesellschaften positivistisch überbewertet zu haben. *Konjekturalgeschichte* und *vergleichende Methode* hätten zu einer Perspektive unlinearer Entwicklung geführt, die durch Stufengliederung der Menschheitsgeschichte kulturelle Vielfalt unangemessen reduziert und durch die Konzentration auf progressive Entwicklungsabläufe zu falschen ethnologischen Beobachtungen geführt habe^[@petermann_geschichte_2004, 464-474, 734.]. Zuletzt wäre die vorgenommene Abgrenzung von Entwicklungsstadien mit einer Teleologisierung auf die moderne, westliche Gesellschaft verbunden und damit Grundlage einer Rechtfertigung von Rassismus, Eurozentrismus und Imperialismus. Damit wurde der Begriff *Sozialdarwinismus* assoziiert^[@ShennanGenesmemeshuman2002, 11.].

*Sozialdarwinismus* ist ebenso wie Evolutionismus keine koherente wissenschaftstheoretische Schule, sondern eine polemische Zuschreibung wissenschaftlicher, ideologischer und politischer Gegner. Die heftige Kontroverse, die rund um Evolutionstheorie in der zweiten Hälfte des 19. Jahrhunderts entstand, wurde von Propagandisten wie Thomas Henry Huxley (\*1825 - \†1895) ("Darwin's Bulldog") oder, im deutschsprachigen Raum, Ernst Haeckel (\*1834 - \†1919) getragen. Die Erkenntnisse hatten Konsequenzen für fundamentale weltanschauliche Fragen -- entsprechend wurde die Diskussion von der Presse aufgegriffenen und einer breiten Öffentlichkeit präsentiert. Das hatte starke, oft unagemessene Vereinfachung der Themenstellung zufolge. Die Reduktion von Evolutionstheorie auf griffige Phrasen wie "survival of the fittest" und "natural selection" wirkte sich schließlich auch auf den Diskurs in den Sozialwissenschaften aus. Spencer entwickelt in seinem Hauptwerk *The Principles of Sociology*^[@SpencerHerbertSpencerPrinciples1898] das Narrativ eines evolutionären Kampf ums Dasein, der nur in den jüngsten Phasen der Menschheitsgeschichte von Altruismus begleitet wird^[@petermann_geschichte_2004, 501-510.]. Diese sozialphilosophische Theorie fällt im Klima der fortgeschrittenen Industrialisierung und deren Konkurrenzgesellschaft auf fruchtbaren Boden. Noch heute wirkt der Gedanke eines Überlebendskampfs im marktwirtschaftlichen Geschehen nach und hat sich etwa über christliche Prädestinationslehre zu jenem traditionell amerikanischen Topos stabilisiert, der sich politisch gegen staatliche Eingriffe ins Wirtschaftssystem und für individuelle, zwischenmenschliche Solidarität ausspricht. Spencer beeinflusste eine ganze Reihe amerikanischer Ethnologen und Soziologen^[@smith_cultural_1992, 62.], darunter William Graham Sumner (\*1840 - \†1910), Lester Frank Ward (\*1841 - \†1913) und Franklin Henry Giddings (\*1855 - \†1931). Sie teilten Spencers Verständnis biosozialer Evolution und deren empirisch-positivistischer Erforschbarkeit, jeder repräsentiert gleichermaßen aber gegensätzliche Ansichten darüber, wie stark die evolutiven Prozesse menschliche Gesellschaften determinieren. Europas Sozialdarwinisten waren keine Spencerianer, dafür aber umso stärker Theorien radikal-biologischen und rassistischen Existenzkampfs verpflichtet. Zu nennen sind unter anderem Gustav Ratzenhofer (\*1842 - \†1904), Jakov Novicov (\*1849 - \†1912), Michelangelo Vaccaro (\*1854 - \†1937) und besonders der jüdisch-polnische Jurist und Soziologe Ludwig Gumplowicz (\*1838 - \†1909), der mit seinem wissenschaftlichen Rassismus in einer Rede im September 1933 von Adolf Hitler fast wörtlich zitiert wurde^[@petermann_geschichte_2004, 511-524.]: 

> Nie und nirgends sind Staaten anders entstanden als durch Unterwerfung fremder Stämme seitens eines oder mehrerer verbündeter oder geeinigter Stämme.
>
> -- [@GumplowiczGrundrissSoziologie1885]

Ein wichtiger Antrieb für Sozialdarwinistische Theorie war die biometrische Forschung von Galton, der intellektuelle Fähigkeit als eine maßgeblich biologisch vererbbare Eigenschaft beschrieb. Ethnische Herkunft hielt er in einer Form von Rassenlehre für das entscheidende Kriterium für die Intelligenz eines Individuums. Er sprach sich in dieser Konsequent für bewusste Zuchtwahl beim Menschen aus und prägte den Begriff *Eugenik*^[@bowler_evolution_1989, 256-257.]. 

### Kulturrelativismus und Neoevolutionismus {#cultural-relativism-neoevolutionism}

Kritiker des Evolutionismus in der ersten Hälfte des zwanzigsten Jahrhunders waren Vertreter der britischen *Social Anthropology*, deutscher *Kulturgeschichte* und vor allem der von Franz Boas (\*1858 - \†1942) etablierten, amerikanischen *Kulturanthropologie*. Die Gemeinsamkeit dieser Schulen und Strömungen liegt an ihrem traditionellen Fokus auf den jeweiligen naturräumlichen, historischen und soziopolitischen Kontext einer kulturellen Ausprägung. Boas war Jude, absolvierte ein naturwissenschaftliches Studium in Deutschland und emigrierte nach seiner Zuwendung zur Ethnologie in die USA. Boas gilt als Begründer des *historischen Partikularismus*, der sich gegen deduktive, umfassende Erklärungsmodelle wie Evolutionismus und Diffusionismus wandte, die vergleichende Methode und ihre Analogieschlüsse verwarf und stattdessen eine genaue, empirische Detailanalyse von Einzelphänomenen betonte. Dabei war Boas Forschungsansatz im Sinne des *four-field approach*, der Ethnologie, Archäologie, Linguistik und Physische Anthropologie zusammenführt, methodisch durchaus breit aufgestellt. Methodisch vielfältige und empirisch fundierte aber gleichzeitig zeitlich und räumlich eng begrenzte Fallstudien sollten den Weg zu einer induktiven Kulturwissenschaft ebnen. Boas begründete damit eine Phase intensiver Datenaufnahme in der amerikanischen Anthropologie (*Salvage ethnography*), die seine Kritiker wiederrum als theorielos verurteilten. 1911 erschien sein Werk *The mind of Primitive Man*^[@Boasmindprimitiveman1911], das die wichtigsten Thesen seines *Kulturrelativismus* zusammenfasst: Es wendet sich gegen biologischen Determinismus, betont den Einfluss von sozialem Lernen und hebt die Multikausailtät historischer Entwicklungen hervor. Kultur sei abhängig von einer Vielzahl natürlicher und zwischenmenschlicher Parameter. Diese Relativität nähme der uniliniearen Gliederung von Kulturzuständen des Evolutionismus die Grundlage. Boas war ein politischer Mensch und argumentierte mit Kulturrelativismus gegen Rassismus und Faschismus^[@petermann_geschichte_2004, 643-655.]. Schüler von Boas (*Boasianer*) wie Clark Wissler (\*1870 - \†1947), Elsie Clews Parsons (\*1875 - \†1941), Alfred Kroeber (\*1876 - \†1960), Alexander Goldenweiser (\*1880 - \†1940), Robert Lowie (\*1883 - \†1957), Paul Radin (\*1883 - \†1959), Edward Sapir (\*1884 - \†1939) prägten die amerikanische Ethnologie nachhaltig und führten über Jahrzehnte einen erbitterten Diskurs mit Evolutionisten und Neoevolutionisten^[@petermann_geschichte_2004, 654-688.].  

*Neoevolutionismus* -- der Begriff wiederrum eine Fremdzuschreibung -- bezeichnet eine Strömung, die als Reaktion auf berechtigte Kritik am Evolutionismus in den 30er Jahren des 20. Jahrhunderts und insbesondere nach dem 2. Weltkrieg an Dynamik gewann. Sie verbindet Ansätze, die sich zwar sozialdarwinistischem Biodeterminismus verweigern, andererseits aber dennoch bewusst nach Gesetzmäßigkeiten soziokultureller Prozesse suchen um der Anthropologie ein höheres Abstraktionsniveau zu erschließen. Aus dieser Definition heraus lassen sich dem Neoevolutionismus einige der bedeutensten Ethnologen und Archäologen zuordnen: Vere Gordon Childe (\*1892 - \†1957), Karl Wittfogel (\*1896 - \†1988), George Murdock (\*1897 - \†1985), Leslie White (\*1900 - \†1975) und Julian Haynes Steward (\*1902 - \†1972) Auch die Arbeit einer nachfolgende Generation mit Protagonisten wie Elman Service (\*1915 - \†1996), Morton Fried (\*1923 - \†1986), Roy Rappaport (\*1926 - \†1997), Marshall Sahlins (\*1930) oder Lewis Binford (\*1931 - \†2011) ist stark von neoevolutionistischem Denken geprägt.

Vere Gordon Childe, ursprünglich Philologe aus Australien, etablierte sich in Europa durch seine großen, synthetischen Werke als Prähistoriker. Ihm gelang es, die Gliederung der Menschheitsgeschichte in Entwicklungsphasen -- Childe griff Morgans Unterscheidung von Wildheit, Barbarei und Zivilisation auf -- durch einen multilinearen Ansatz neu zu beleben und in kohärenten, archäologischen Narrativen (z.B. *The Dawn of European Civilization*^[@childe_dawn_1925], *Man Makes himself*^[@childe_man_1936] oder *Social Evolution*^[@childe_social_1951]) nutzbar zu machen. Als überzeugter Marxist etablierte er den Topos *vorgeschichtlicher Revolutionen*, der Marx *Historischen Materialismus* weiterentwickelt und konkretisiert. Childes Kritiker waren zunächst vor allem jene Spezialisten, deren Forschung er in seinen Büchern zusammen zu fassen und zu vereinfachen auf sich genommen hatte. Der deutsche Soziologe und Sinologe Karl Wittvogel beschäftigte sich mit dem Einfluss von Bewässerungssystemen im Entstehungsprozess früher Hochkulturen. Mit seiner Studie zu *Hydraulischen Gesellschaften*^[@wittfogel_oriental_1957] hat er ein einflussreiches, evolutionistisches Werk vorgelegt, das Staatenbildung und die Herausbildung der Hierarchie des *orientalischen Despotismus* mit Verwaltungsnotwendigkeiten von Bewässerungssystemen erklärt. Wittvogels Theorie hat bemerkenswerte Rezeption und erfahren und wurde in eine Vielzahl anderer Kulturzusammenhänge hineinprojiziert. George Murdock war ein Vorreiter der *Cross-Cultural Analysis* und Begründer der *Human Relations Area Files*^[http://hraf.yale.edu [28.01.2018]]. Dieses Archiv ist 1949 aus einer von Murdock entwickelten Sammlung hervorgegangen, enthält strukturierte Informationen und Literaturlisten zu Kulturmerkmalen vieler hundert -- meist indigener -- Gesellschaften und wird bis heute gepflegt. Murdocks *transkultureller Vergleich* basiert auf evolutionistischer Grundlage und ist stark von quantitativer Auswertung mit ethnostatistischen Methoden geprägt: Sein Hauptwerk *Social Structure*^[@murdock_social_1949] analysiert und dokumentiert universelle Regeln und Gesetze sozialer Beziehungen anhand eines Datensatzes von 250 Ethnien. Im Kontext der Kritik am Evolutionsimus wurde auch Murdock vorgeworfen, Kulturzüge unsachgemäß isoliert betrachtet oder einer solchen Betrachtung zugänglich gemacht zu haben. Der amerikanische Ethnologe Leslie White war einer der wichtigsten Protagonisten des Neoevolutionismus. Nach seiner Lektüre von  Morgan und anderen Evolutionisten wie Spencer und Tylor suchte er explizit die Konfrontation mit dem vorherrschenden Partikularismus der Boasianer und stellte ihr eine umfassende, materialistische Kulturtheorie gegenüber. Diese würde objektiven Kulturvergleich im Sinne einer Wissenschaft der *Kulturologie* entlang einer evolutiven Skala des Prokopfverbrauchs von Energie ermöglichen: *White's Law*^[@white_energy_1943, @white_science_1949]. White betonte die Bedeutung von Technologie und Wirtschaft für die Herausbildung von Sozialordnung und Ideologie, erkannte aber auch die einzigartige, symbolschaffende Kreativität des Menschen an. Kritiker werfen ihm vor, diesen impliziten Widerspruch niemals aufgelöst zu haben. Dennoch inspirierte Whites klare, regelbasierte Anthropologie eine Generation von Studierenden die sich im Kulturrelativismus nicht wiederfinden konnten. Neben White ist auch Julian Steward eine der tragenden Säulen des Neoevolutionismus. Steward veröffentlicht 1955 *Theory of Culture Change*^, wo er *Kulturökologie* als Wissenschaft von definierbaren Ursache-Wirkung Beziehungen von Natur- und Mensch jenseits des überholten *Kulturdeterminismus* formuliert. Sein Vorschlag zur Periodisierung der Ur- und Frühgeschichte folgt einem *multilinearen* Ansatz, der der *unilinearen* Abfolge von für alle Kulturen immer gleicher Zustandsformen die Analogentwicklung von *Kulturtypen* -- Typen der Umweltanpassung -- entgegenstellt. Unter bestimmten natürlichen und sozialen Bedingugen würden sich bestimmte Verhaltensmuster und Formen des Zusammenlebens ergeben, nicht aber mit zwingender Notwendigkeit oder in einer definierten Abfolge. Auch Steward bezog sich methodisch auf transkulturellen Vergleich, der es ermöglichen sollte, die primären, subsistenzbezogenen Eigenschaften von techno-ökonomischen *Kulturkernen* im Gegensatz zum Überbau der sekundären, variablen Charakterzüge von Kulturen zu definieren. Mehrere Protagonisten der noch jungen *New Archaeology* wurden von Stewards modernem, pragmatischer Evolutionismus stark beeinflusst^[@petermann_geschichte_2004, 734-761.].

### Moderne Theorien zur Kulturevolution

Eine neue Welle der Auseinandersetzung mit Kulturevolution gewinnt Mitte der 1970er Jahre an Dynamik^[@creanza_cultural_2017]. Sie lenkt das Interesse weg von Politik und Gesellschaftsstruktur, sondern abstrahiert auf die basalen Grundzüge menschlichen Denkens. Dieser Ansatz inkorporiert Ergebnisse und Methoden moderner, biologischer Verhaltensforschung und erlaubt neue Perspektiven Jenseits des Evolutionismus und seiner Varianten. Von entscheidender Bedeutung für die Entstehung dieser Strömungen sind Edward Osborne Wilsons (\*1929) *Sociobiology: The New Synthesis*^[@WilsonSociobiologynewsynthesis1975] und Richard Dawkins (\*1941) *The Selfish Gene*^[@Dawkinsselfishgene1976], auf das unten genauer eingegangen werden soll^[@SmithThreestylesevolutionary2000, 27.]. Auch Luigi Luca Cavalli-Sforza (\*1922), Marcus William Feldmann (\*1942) und andere entwickeln wesentliche Ansätze für den Brückenschlag zwischen Biologie und Anthropologie^[@alland_cultural_1972, @cavalli-sforza_models_1973, @feldman_models_1975, @feldman_cultural_1976, @blum_uncertainty_1978]. 
Um die Jahrtausendwende unterscheidet Eric Aldan Smith schließlich drei große Strömungen^[@SmithThreestylesevolutionary2000. Stephen Shennan greift diese Unterscheidung auf [@ShennanGenesmemeshuman2002, 15-18.]] in der Untersuchung menschlichen Verhaltens aus einer Evolutionsperspektive: *Evolutionary psychology*, *Human behavioural ecology* und *Dual inheritance theory*.

*Evolutionary psychology* konzentriert sich auf die Entwicklung des menschlichen Denkens vor dem Hintergrund seiner evolutionären Geschichte. Selektiver Druck habe zur Ausbildung spezialisierter Verhaltensmodule geführt, die in bestimmten Situationen bestimmte Reaktionen auslösen. Von entscheidender Bedeutung für die Entstehung dieser angepassten Verhaltensmodule sei die *Environment of Evolutionary Adaptiveness (EEA)*, also die Umgebung, in der sich die menschliche Entwicklung maßgeblich abgespielt hat. Dabei bezieht sich die *Evolutionary psychology* auf die Lebensrealität pleistozäner Jäger- und Sammlergruppen, in der der moderne Mensch den überwältigend größten Teil selektiv wirksamer Generationszyklen durchlebt hat. Die Selektionsparameter wären in diesem Zeitraum relativ stabil geblieben. In der Konsequenz seien Menschen heute beispielsweise ideal an das nomadische Leben in kleinen Gruppen in großer gegenseitiger Abhängigkeit adaptiert, Männer würden junge, gesunde und hübsche Sexualpartnerinnen bevorzugen und süße Speißen wären beliebt, weil Süße bei Früchten ein Indikator für Reife und Genießbarkeit ist. Alle Aspekte des Verhaltens seien auf bestimmte Gegebenheiten in der *EEA* optimiert und entsprechend schlecht für eine andere, etwa neolithische oder postneolithische Lebensweise geeignet^[@SmithThreestylesevolutionary2000, 27-29.]. 
Der *Evolutionary psychology* wird vorgeworfen, die unangemessen vereinfachende Annahmen über vorgeschichtliches Verhalten zu treffen, ohne sich ausreichend mit jenen archäologischen Daten und Auswertungsergebnissen auseinanderzusetzen, die eine Rekonstruktion der tatsächlichen Lebensverhältnisse in der Vorgeschichte erlauben würden. Aus archäologischer Perspektive greift unter anderem @Mithenprehistorymindsearch1996 Überlegungen der *Evolutionary psychology* auf^[@ShennanGenesmemeshuman2002, 15.].

*Human behavioural ecology* überträgt Ansätze aus der Verhaltensbiologie auf den Menschen^[@smith_cultural_1992; @winterhalder_analyzing_2000]. Dabei nimmt sie den klassisch-darwinistischen Standpunkt ein, menschliches Verhalten könnte ebenso wie tierisches als permanente Maximierung des Reproduktionserfolgs durch Selektion verstanden werden^[@creanza_cultural_2017]. Bewusste oder unbewusste Entscheidungen würden hinsichtlich der Frage getroffen werden, inwiefern das Ergebnis den Erhalt der eigenen genetischen Information gewährleistet. Im Zentrum steht dabei die Beziehung zwischen Mensch und natürlicher Umwelt: "Welche ökologischen Faktoren (z.B. Ressourcenverfügbarkeit, Populationsdichte, etc.) schaffen den Rahmen dafür, dass ein bestimmtes Verhalten (z.B. Altruismus, Vorratshaltung, etc.) zum Erfolg führt?". Die ökologische Nische des Menschen in Relation zu seinen Subsistenzstrategien, seinem Paarungsverhalten und seiner sozialen Struktur sind wesentliche Forschungsgegenstände der *Human behavioural ecology*^[@henrich_search_2001; @kaplan_theory_2000; @voland_evolutionary_1998; @winterhalder_risk-senstive_1999]. Die kleinteilige Aufgliederung der Fragestellungen hinsichtlich einzelner Situationen und Verhaltensweisen erlaubt es dabei, auch komplexe Fragen quantitativ in einfachen Modellen abzubilden. Diese Modelle versprechen testbare Aussagen: "Wenn Frauen ihre Sexualpartner nach dem Kriterium wählen, wer den Nachwuchs am besten versorgen kann, dann wäre die Anzahl der Frauen pro Mann proportional zu seinem Reichtum.". Die Reduktion auf direkte, kausale Beziehungen birgt jedoch die Gefahr die vielfältigen Interdependenzen einzelner Verhaltensweisen zu übersehen. Gerade Langtzeitstudien spielen dafür eine wichtige Rolle^[@belovsky_optimal_1988; @broughton_widening_1997; @low_population_1993; @stiner_paleolithic_1999; @stiner_tortoise_2000; @winterhalder_population_1988]. *Behavioural ecology* erklärt die Vielfalt menschlichen Verhaltens aus der großen Diversität biologischer- und sozialer Nischen, die sehr viele unterschiedliche Erfolgsstrategien erlaubt. Tatsächlich gäbe es sogar eine Korrelation zwischen Verhaltensvielfalt und Diversität der sozioökologischen Umwelt. Sie erlaubt sich eine große Vereinfachung, indem sie die Mechanismen, die zur Ausbildung einer Verhaltensanpassung führen, nicht hinterfragt: Die einschränkende Wirkung von Kultur (hier: vererbtes Verhalten) etwa in Form von Tradition sei untergeordnet, da erfolglose Strategien unabhängig davon in wenigen Generationen durch biologische Selektion aussterben würden. Diese bewusste, statistische Vereinfachung von Übergangsprozessen wird als *phenotypic gambit* bezeichnet (und kritisiert^[@rubin_phenotypic_2016]). In ihrer Konsequenz sei auch anzunehmen, dass der Mensch sein Verhalten schnell und gut an die revolutionären Veränderungen des Holozän oder der Industrialisierung angepasst habe^[@SmithThreestylesevolutionary2000, 29-31.]. 

*Dual inheritance theory* postuliert neben der Vererbung von Genen ein zweites Vererbungssystem von Ideen und Kulturmerkmalen. Auch diese würden von Generation zu Generation, von Person zu Person und von Tag zu Tag weitergereicht und stünden unter dem Einfluss von Selektion und Mutation. Dabei würde sowohl die im genetischen Vererbungssystem entscheidende, natürliche Selektion wirken als auch eine Selektion durch bewusste oder unbewusste Entscheidung der Träger von Ideen: Menschen. Ersterer Selektionsprozess sei Konsequenz der Rückwirkung von Ideen auf die Fitness ihrer Träger, letzterer ein System von Interdepenzen verschiedener Ideen, Umweltsituationen und genetischer Determinanten. Ebenfalls von entscheidender Bedeutung seien die zwischenmenschlichen Prozesse wie Erziehung, Gefolgschaft oder Freundschaft, die die Weitergabe von Ideen steuern. Entstehung neuer Ideen aus der Kombination vorhandener wäre eine Form der Mutation. Da nun also in der Kulturgeschichte Vererbung, Entstehung von Variabilität und Auswahl nach Fitnesskriterien als gegeben angenommen werden dürften, und damit große strukturelle Ähnlichkeit des genetischen und des kulturellen Vererbungssystems bestünde, sei auch die Übertragung neo-darwinistischer Methoden auf die Untersuchung von Kulturmerkmalen möglich. Die beiden Vererbungssysteme könnten unabhängig und in ihrer Interaktion erforscht werden, wobei Konzepte zur Erklärung des einen potentiell auch zur Erklärung im anderen geeignet sein könnten.  Andererseits gäbe es auch klare Unterschiede: Beispielsweise erfolgt die Weitergabe genetischer Information fast ausschließlich vertikal durch sexuelle oder asexuelle Fortpflanzung, während Ideen beliebig horizontal weitergeben werden, also unabhängig von Verwandschaft diffundieren können. Individuelle Menschen sind zwar sowohl Träger vieler Gene als auch vieler Kulturmerkmale, erstere werden aber nur einmal festgelegt, während letztere ständigem Wechsel unterliegen. *Dual inheritance theory* ist sich dieser Unterschiede bewusst, hält sie aber für analystisch bewätigbar. Da die kulturelle Evolution in anderen zeitlichen, räumlichen und kausalen Maßstäben agieren würde, könnte diese Theorie auch das Auftreten von Verhaltensmerkmalen erklären, die aus einer Reproduktionsperspektive nicht sinnvoll sind. Kulturelle Evolution ist schneller und flexibler: Anpassung an neue oder für das Überleben von Menschen ungeeignete Umgebungen geschieht nicht mehr genetisch, sondern durch Verhaltensanpassung. Genetische Anpassung folgt der kulturellen langsam, bedeutet aber auch Einschränkungen für die Flexibilität der kulturellen Evolution^[@SmithThreestylesevolutionary2000, 31-33.]. 

Smith legt seinem Artikel Tabelle \@ref(tab:smiththreestyles) bei, die die Unterschiede zwischen *Evolutionary psychology*, *Human behavioural ecology* und *Dual inheritance theory* zusammenfasst.

```{r smiththreestyles, echo=FALSE, tidy=FALSE, results = "asis"}
library(magrittr)

tibble::tribble(
                                                  ~X1,             ~`Evolutionary psychology`,                     ~`Behavioural ecology`,                 ~`Dual.inheritance theory`,
                           "What is being explained:",           "Psychological mechanisms",                 "Behavioural strategies",                     "Cultural evolution",
                                   "Key constraints:",                 "Cognitive, genetic",                   "Ecological, material",                "Structural, information",
                 "Temporal scale of adaptive change:",                "Long-term (genetic)",                "Short-term (phenotypic)",                 "Medium-term (cultural)",
                     "Expected current adaptiveness:",                             "Lowest",                                "Highest",                           "Intermediate",
                             "Hypothesis generation:",                 "Informal inference",                      "Optimality models",                "Population-level models",
                        "Hypothesis-testing methods:",             "Survey, lab experiment", "Quantitative ethnographic observartion",  "Mathematical modelling and simulation",
                                   "Favoured topics:", "Mating, parenting, sex differences",   "Subsistence, reproductive strategies", "Large-scale cooperation, maladaptation"
                 ) %>%
  knitr::kable(
    caption = "Three Styles of Evolutionary Explanation (nach \\textcite{SmithThreestylesevolutionary2000})",
    format = "latex",
    booktabs = T,
    escape = F,
    col.names = c("", "Evolutionary psychology", "Behavioural ecology", "Dual.inheritance theory")
  ) %>%
  kableExtra::kable_styling(full_width = T) %>%
  kableExtra::column_spec(1, width = "15em") %>%
  kableExtra::column_spec(2, width = "10em") %>%
  kableExtra::column_spec(3, width = "10em") %>%
  kableExtra::column_spec(4, width = "10em") %>%
  gsub("table", "table*", .)
```

*Dual inheritance theory* ist ein wesentlicher Teil der theoretischen Grundlage für die Expansionsssimulation, die für die vorliegende Arbeit entwickelt wurde (siehe Kapitel \@ref(simulation-theorie)). Um sie besser zu verstehen, lohnt es sich, einen wichtigen Teil ihrer Entstehungsgeschichte nachzuzeichnen: Richard Dawkins *Memetik*.

## Memetik {#memetics}

Memetik (engl. *Memetics*) ist eine Variante der oben beschriebenen *Dual inheritance theory*. Der Begriff *Meme* wurde 1976 vom britischen Evolutionsbiologen Richard Dawkins in *The selfish gene*^[@Dawkinsselfishgene1976. Ich werde im folgenden aus einer Neuauflage des Buches zitieren, die 2016 40 Jahre nach der Erstpublikation veröffentlicht und um Kommentare von Dawkins erweitert wurde: @Dawkinsselfishgene40th2016.] eingeführt. Obgleich populärwissenschaftlich hat es doch in verschiedenen Fachbereichen beachtliche Rezeption erfahren und darf als wichtiger Grundstein dieser intellektuellen Strömung gelten. Memetik ist eine außergewöhnlich wirkungsvolle Nischenwissenschaft, die von Kritikern als irrelevant, unpraktikabel, Ideologie oder Pseudowissenschaft abgelehnt (siehe Kapitel \@ref(memetics-critique)) wurde. Das liegt nicht zuletzt an ihrem niederschwelligen Zugang zu Cultural evolution theory. Ihr größter Verdienst ist es, Grundgedanken zur Kulturevolutionsforschung zu Ende zu denken und radikal vereinfacht auszufomulieren. Das hat den Diskurs in mehrere Fächer getragen und zu einer neuen Reife geführt: Memetik hat sich selbst abgeschafft. In dieser Arbeit steht Memetik auch exemplarisch für andere Strömungen der Cultural evolution theory, die sich an der Formulierung eines einer einheitlichen und umfassenden Entwicklungsmodells versucht haben -- z.B. *Cultural virus theory*^[@cullen_contagious_2000].

### Meme in Dawkins *The selfish gene* {#memetics-dawkins}

Dawkins führt in *The selfish gene* einen wesentlichen Perspektivenwechsel durch, indem er Evolution nicht aus der Sicht der sich entwickelnden Organismen sondern aus der sich durch die Organismen ausbreitenden Gene betrachtet. Gene würden -- freilich nicht bewusst -- Lebewesen als komplexe Vehikel für ihre eigene Reproduktion nutzen und so die Entwicklung derselben mittel- und langfristig auf Populationsniveau steuern: *the gene's eye view*. In Kapitel 11, *Memes: the new replicators*^[@Dawkinsselfishgene40th2016, 287-303], bezieht Dawkins explizit die Spezies Mensch in seine Analyse mit ein und prüft, ob die Menschheit im selben Umfang dieser Determination durch den statistischen Willen ihres Erbguts untertan ist? Dawkins verneint das: Sein Kulturverhalten würde den Menschen von allen anderen bekannten Lebewesen abheben. 

Auch bei Tieren gibt es Verhaltensmuster, die unabhängig von genetischer Vererbung von Individuum zu Individuum weitergegeben werden: beispielsweise bestimmte Melodien des Gesangs von Singvögeln, die erwachsene Tiere voneinander lernen. Kein anderes bekanntes Lebewesen erreicht jedoch das Komplexitätsniveau des Menschen, der Sprache, Mode, Ritual, Kunst, Architektur und Technologie besitzt und sie unter ständigen Anpassungen tradiert. Die Entwicklungen in diesen Bereichen über archäologische Zeiträume zeigt eine Tendenz hin zu zunehmend höherer Komplexität und Vielfalt. Geschwindigkeit und Diversität liegen weit jenseits dessen, was genetische Evolution zu leisten in der Lage wäre. Erklärungsversuche dafür von *Evolutionary psychology* und *Human behavioural ecology* empfindet Dawkins als unzureichend. Stattdessen abstrahiert er die von ihm postulierte Evolutionstheorie und führt den Begriff des *Replikators* ein. Wenn irgendeine Form von Replikator vorhanden sei, dann würde zwangsläufig Evolution stattfinden. Gene seien Replikatoren -- Ideen, Gedanken, *Meme* aber ebenso. Glaubt man einer Fußnote in Dawkins später kommentiertem Text, so war die Aussage, dass das Gen nicht die einzige mögliche Form eines Replikators ist, bereits die wesentliche in Kapitel 11. Umso erstaunlicher, dass er den Moment der Schöpfung seines Neologismus Meme dennoch theatralisch zelebriert:  

> I think that a new kind of replicator has recently emerged on this very planet. It ist staring us in the face. It is still in its infancy, still drifting clumsily about in its primeval soup, but already is it achieving evolutionary change at a rate that leaves the old gene panting far behind.
The new soup is the soup of human culture. We need a name for the new replicator, a noun that conveys the idea of a unit of cultural transmission, or a unit of *imitation*. 'Mimeme' comes from a suitable Greek root, but I want a monosyllable that sounds a bit like 'gene'. I hope my classicist friends will forgive me if I abbreviate mimeme to meme. [...] It should be pronounced to rhyme with 'cream'. 
>
> -- @Dawkinsselfishgene40th2016, 291.

Meme seien kleine abgrenzbare Informationseinheiten wie Melodien, Geflügelte Worte, Kleidungsmoden oder das Wissen um spezifische technische Prozesse. So wie Gene Lebewesen als Vehikel gebrauchen, so wären menschliche Gehirne das Medium, in denen sich Gene ausbreiten. Die Informationsweitergabe ist nicht auf sexuelle oder asexuelle Fortpflanzung beschränkt, sondern funktioniert über eine Form der zwischenmenschlichen Kommunikation, die Dawkins unter dem Überbegriff Imitation zusammenfasst. Er geht davon aus, dass Meme physische als Strukturen verschaltener Nervenzellen existieren. Unabhängig davon sei ihr Effekt deutlich zu spüren: Entitäten, die unser Denken parasitisch bewohnen und ihre eigene Ausbreitung bezwecken. Dawkins bemüht für eine erste Illustration das Beispiel des monotheistischen Glaubens an einen Gott^[Religionskritik ist ein wiederkehrendes Thema in Dawkins umfangreichem, populärwissenschaftlichem Werk. Siehe z.B. @dawkins_god_2006]:  

> Consider the idea of God. [..] How does it replicate itself? By the spoken and written word, aided by great music and great art. [...] What is it about the idea of a god that gives it its stability and penetrance in the cultural environment? The survival value of the god meme in the meme pool results from its great psychological appeal. It provides a superficially plausible answer to deep and troubling questions about existence. It suggests that injustices in this world may be rectified in the next. The 'everlasting arms' hold out a cushion against our own inadequacies which, like a doctors placebo, is none the less effective for being imaginary. These are some of the reasons why the idea of God is copied so readily by successive generations of individual brains.
> 
> -- @Dawkinsselfishgene40th2016, 292.

Warum ist das menschliche Gehirn empfänglich für Meme? Gibt es einen klassisch evolutionären Vorteil von dieser Empfänglichkeit? Nach Dawkins ist die grundsätzliche Kulturfähigkeit des Menschen durchaus ein Effekt genetischer Mutation und Selektion. Ab einem gewissen Punkt -- in fließendem Übergang -- sei allerdings der Replikator Meme im Kulturraum entstanden und hätte die Zügel in die Hand genommen. 

> Whenever conditions arise in which a new kind of replicator *can* make copies of itself, the new replicators *will* tend to take over, and start a new kind of evolution of their own. Once this new evolution begins, it will in no necessary sense be subservient to the old. 
> 
> -- @Dawkinsselfishgene40th2016, 293.

Die genetische Evolution habe also den Nährboden bzw. das Medium einer neuen, viel schnelleren Form der Evolution geschaffen, die andere Prioritäten für Gesundheit, Langlebigkeit und Fortpflanzungsfähigkeit ihrer Trägerorganismen anlegt. In vielen Fällen sind diese Prioritäten ähnlich. Ein Beispiel dafür sind Meme, die positv konnotiert mit Sex umgehen. Andererseits gibt es auch Meme wie etwa das Zölibat katholischer Ordensträger, die aus einer Genperspektive schwerer zu erklären sind, da sie die Verbreitung der Gene ihrer Träger effektiv hemmen.

Wenn nun also auch im Medium Kultur die Mechanismen der Evolution wirken, dann müssten sich die Replikatoren Meme dem selben Druck beugen wie die Gene in der natürlichen Umwelt. Überleben könnten nur Replikatorenvarianten mit einer hohen Qualität der Eigenschaften *longevity*, *fecundity* und *copying-fidelity*^[@Dawkinsselfishgene40th2016, 47-49.].

*longevity* -- Langlebigkeit -- sei eine günstige Eigenschaft für einen Replikatortyp, da er seinen Gesamtbestand im Medium so einerseits leicht hoch halten kann und ihm außerdem mehr Zeit für Reproduktion zur Verfügung steht. Einzelne Kopien von Genen sind in ihrer Lebenszeit an den Organismus gebunden, dessen Aufbau sie kodieren. Instanzen eines Memes seien dagegen von der menschlichen Gedächtnisleistung abhängig. Meme könnten aber auch außerhalb von Menschen überdauern, wenn sie etwa in geschriebener oder digitaler Form abgelegt wurden. Damit könnte das Meme etwa später wieder einen Menschen infizieren, obgleich kein direkter Kontakt mit einem Infizierten stattgefunden hat. 

*fecundity* -- Fruchtbarkeit -- sei für die Durchsetzungsfähigkeit eines Replikatortyps noch wichtiger als *longevity*: Um so mehr Kopien er in kürzerer Zeit von sich selbst anfertigen kann, desto schneller wird er das Medium dominieren. Die Reproduzierfähigkeit eines Memes sollte von verschiedenen Eigenschaften abhängen, allem voran schlicht seiner Beliebtheit in oder außerhalb einer assoziierten Adressatengruppe.

*copying-fidelity* -- Kopiertreue -- scheint hier zunächst deplaziert. Ein gewisser Grad an Mutationsfähigkeit ist unerlässlich für Anpassung. Tritt allerdings bei einem Replikatortyp eine zu große Instabilität auf, so argumentiert Dawkins, könnte er seine Identität nicht aufrechterhalten und würde entweder schnell von Varianten abgelöst, die aus ihm selbst hervorgegangen sind, oder sich völlig auflösen. Bei Memen scheint gerade das häufig zu passieren: Übertragungsfehler oder bewusste Modifikation scheinen die Regel, nicht die Ausnahme zu sein. Damit muss die Qualität von Memen als Replikatoren in Frage gestellt werden. Dawkins gibt das zu -- diese Frage nach der Kopiertreue führt ihn zurück zur Definition von Memen. Welche Information enthält ein individuelles Meme bzw. -- in einem Analogieschluss -- das Gen?

Das Gen hat hinsichtlich seines mikrobiologischen Aufbaus eine langwierige Definitionsgeschichte hinter sich^[@gerstein_what_2007; siehe auch Kapitel \@ref(biology)]. Dawkins definiert es als einen dedizierten DNA-Abschnitt mit hinreichender Wirkung und Kopiertreue, um als selektionsrelevante Einheit zu wirken. Gene schließen sich auf verschiedenen hierarchischen Ebenen zu Komplexen zusammen, die als Gruppe gegebenfalls eine Gesamtwirkung entfalten und wiederum als ganzes selektionsrelevant wirken kann^[@Dawkinsselfishgene40th2016, 36-37.]. Ein ähnliches Strukturverhalten könnte auch für Meme angenommen werden. Eine Symphonie setzt sich beispielsweise aus einer Vielzahl einzelner, für sich wiedererkennbarer Melodieabschnitte und Figuren zusammen. Eine Religion ist die Gesamtheit vieler verknüpfter Ideen und Ritualen, die als ganzes tradiert werden, eine Konfession möglicherweise ein *stable set of mutually-assisting memes*^[@Dawkinsselfishgene40th2016, 299. Komplexe zusammenhängener Meme wurden später von Dawkins Schülern mit dem Begriff *Memeplex* belegt (siehe Kapitel \@ref(memetics-history).]. 

> I conjecture that co-adapted meme-complexes evolve in the same kind of way as co-adapted gene-complexes. Selection favours memes that exploit their cultural environment to their own advantage. This cultural environment consists of other memes which are also being selected. The meme pool therefore comes to have the attributes of an evolutionarily stable set, which new memes find it hard to invade. 
> 
> -- @Dawkinsselfishgene40th2016, 301.

Wie oben ausgeführt, versetzt sich Dawkins in die Perspektive der Gene hinein und personifiziert sie. Eine empirisch naheliegende und terminoligisch praktische Metapher um ihre effektive Entwicklung zu beschreiben. Diese Übertragung möchte er auch für Meme vornehmen. Meme stünden in starker Konkurrenz zueinander um die Zeit, die Menschen ihnen widmen und sie gegebenenfalls replizieren: Meme möchten so viele menschliche Gehirne wie möglich so lange wie möglich dominieren.

> Time is possibly a more important limiting factor than storage space, and it is the subject of heavy competition. The human brain, and the body that it controls, cannot do more than one or a few things at once. If a meme is to dominate the attention of a human brain, it must do so at the expense of 'rival' memes.
>
> -- @Dawkinsselfishgene40th2016, 298. 

Aus dieser Perspektive könnte, so Dawkins, etwa das oben angesprochene Zölibat-Meme verstanden werden, dass im Memeplex katholischer Glaubenspraxis Priester freisetzt, keine Zeit an einer Familie zu verlieren, sondern sich voll auf die Pflege und Verbreitung anderer Meme der Kirchendoktrin zu konzentrieren. Die Prioritäten von Menschen, Genen und Memen müssen sich unterscheiden.

> What we have not previously considered, is that a cultural trait may have evolved in the way that it has, simply because it is *advantageous to itself*.
> 
> -- @Dawkinsselfishgene40th2016, 302. 

Das wirft die philosophische Frage auf, inwiefern Menschen Sklaven ihrer Gene und Meme sind. Dawkins gibt dazu zu bedenken, dass weder Gene noch Meme im Gegensatz zum Menschen über Bewusstsein oder Planungsfähigkeit verfügen. Gene und Meme seien *unconscious, blind, replicators*^[@Dawkinsselfishgene40th2016, 302.]. Damit könnte sich der Mensch seine Situation bewusst machen, sich zumindest teilweise den auf ihn wirkenden Entitäten entziehen und neue Meme schaffen, die seinen Zielen besser dienen: zum Beispiel solche, die langfristige Kooperation stabilisieren und den immanenten Egoismus von Genen und Memen ächten.

### Kurze Geschichte der Memetik {#memetics-history}

Dawkins war nicht der erste Autor, der den Meme-Begriff für Einheiten der Kulturübertragung genutzt hat, obgleich die subjektive Orginalität seiner Wortschöpfung der Wahrheit entsprechen mag^[@laurent_note_1999]. Dawkins Quellen und Inspiration zu hinterfragen würde den Rahmen dieser Arbeit sprengen, es seien aber immerhin Ted Cloak^[@cloak_cultural_1966; @cloak_is_1975] sowie Cavalli-Sforza und Feldman^[@cavalli-sforza_models_1973] erwähnt, die Teile des Replikatormodells vorweg genommen hatten und von Dawkins darin auch zitiert werden. Ausgehehend von *The selfish gene* hat sich Memetik -- in Dawkins Terminologie -- als außerordentlich potentes Meme erwiesen. Eine intensive Außeinandersetzung damit fand allerdings erst mit einigem zeitlichem Abstand in den 1990ern statt. Die Cultural evolution Debatte, in deren größeren Kontext Memetik eingeordnet werden muss, erfuhr indes auch in den 80ern wesentliche Beiträge: 1981 wurden mit Charles Lumsdens (\*1949) und Edward Wilsons *Genes, Mind and Culture* [@lumsden_genes_1981] sowie Cavalli-Sforzas und Feldmans *Cultural Transmission and Evolution*^[@cavalli-sforza_cultural_1981] zwei wichtige und gleichermaßen kontroverse Monographien veröffentlicht, die Modelle zur Inkorporation evolutionärer Ansätze für die anthropologische Forschung ausformulierten. Lumsden und Wilson führten statt des Memes den bedeutungsähnlichen Begriff *cultural gene* ein. Die Geistes- und Geschichtswissenschaften standen soziobiologischen Ansätzen in den 70ern und 80ern grundsätzlich kritisch gegenüber^[u.a. @sahlins_use_1976] -- entsprechend zurückhaltend war der Umgang mit diesen Publikationen. Peter James Richerson (\*1943) und Robert Boyd (\*1948) nahmen mit *Culture and the Evolutionary Process*^[@boyd_culture_1985] wesentlichen Einfluss auf diese Diskussion indem sie mit einem expliziten Schwerpunkt auf Dual Inheritance theory Teile der festgefahrenen Soziobiologie-Konflikts vermieden. Gleichzeitig übernahmen sie damit ein der Memetik ähnliches Gerüst, ohne jedoch den Meme-Begriff zu referenzieren. Die 90er schließlich waren das Jahrzehnt der Memetik. Maßgeblichen Anteil daran hatten neben Dawkins^[@dawkins_viruses_1993] unter anderem die Psychologin Susan Blackmore (\*1951) mit *The Meme Machine* ^[@blackmore_meme_1999 -- Ich werde im folgenden aus einer mir vorliegenden, deutschen Ausgabe zitieren: @blackmore_macht_2000], der Philosoph Daniel Dennett (\*1942) mit *Consciousness Explained*^[@dennett_consciousness_1991] und *Darwin’s Dangerous Idea*^[@dennett_darwins_1995; siehe auch @dennett_brainstorms_1978 und @dennett_elbow_1984] sowie eine große Zahl von Natur- und Geisteswissenschaftlern, die sich unter anderem im 1997 eigens gegründeten Journal of Memetics^[http://cfpm.org/jom-emit/ [06.01.2018]] zu Wort gemeldet haben. Darunter genannt werden sollen Aaron Lynch^[u.a. @lynch_thought_1996] (\*1880 - \†1940), Francis Heylighen^[u.a. @heylighen_evolution_1996 und @heylighen_selfish_1992] (\*1960), und Derek Gatherer^[u.a. @gatherer_identifying_2002 und @gatherer_spread_2002]. In den frühen 2000ern wurden die kritischen Stimmen innerhalb und außerhalb der Community of Practice immer lauter^[z.B. in @aunger_darwinizing_2000] und leiteten den Abgesang der Memetik ein: Memetik wurde zunehmend weniger referenziert und dem einem Stigma der pseudowissenschaftlichkeit assoziiert. Das Journal of Memetics wurde 2005 in Ermangelung von Beiträgen eingestellt^[@vada_what_2015]. Die sichtbarste Referenz zur Memetik in der archäologischen Literaturlandschaft ist Stephen Shennans (\*1949) *Genes, memes, and human history*^[@shennan_genes_2002] geblieben, das sich aber weniger der Memetik als vielmehr der Evolutionary Archaeology im Allgemeinen widmet.

Die Qualität Susan Blackmores *The meme machine* liegt in der Synthese vieler Diskurse und Spannungslinien, die sich rund um die Memetik bis in die 90er Jahre herauskristallisiert hatten. Im ersten Teil ihres Buches formuliert Dawkins Grundgedanken sehr bildhaft aus: Meme sind das Ergebnis von *Imitation*, *Universeller Darwinismus* greift wo immer *Replikatoren* auftreten, Kulturentwicklung zieht biologische Evolution an einer *langen Leine* hinter sich her, Meme haben Ähnlichkeit zu *Krankheiten* und *Computerviren*, Meme haben -- zumindest statistisch -- Willen und Agency (*the memes’ eye view*). Bevor sie diese Konzepte im Letzten Teil des Buches für gesellschaftlichen Kommentar instrumentalisiert (*Meme des New Age*, *Ins Internet*, *Religionen als Memplexe*), wendet sie sich im mittleren wesentlich Fragen der Menschheitsentwicklung aus memetischer Perspektive zu. Dabei lässt sich ihr Erklärunsmodell auf eine einfache Formel reduzieren: Sobald Meme existieren übernehmen sie die Rolle des dominanten Replikators, der das Verhalten seiner Träger wesentlich und langfristig beeinflusst. Dieses Interpretationsmuster bringt sie so beispielsweise für die Entstehung von Sprache, als Mechanismus sexueller Selektion oder als Begründung für zwischenmenschnlichem Altruismus zur Anwendung: 

> Als sich die Imitationsfähigkeit erst einmal entwickelt hatte und Meme auftauchten, haben diese Meme die Umwelt verändert, in der die Gene selektiert wurden und zwangen sie so, immmer bessere memverbreitende Apparate zu schaffen. Mit anderen Worten ist die menschliche Sprachfähigkeit memgetrieben, und die Funktion der Sprache besteht darin, Meme zu verbreiten.
> 
> -- @blackmore_macht_2000, 159.

> Der Memetik [...] zufolge wird die Partnerwahl nicht nur vom genetischen, sondern auch vom memetischen Vorteil beeinflusst. Eine meiner Schlüsselannahmen ist, dass die natürliche Selektion nach Entstehung der ersten Meme begann, Menschen zu favorisieren, die sich für eine Paarung mit den besten Imitatoren oder den besten Benutzern und Verbreitern von Memen entschieden.
> 
> -- @blackmore_macht_2000, 213.

> Wenn Leute altruistisch sind, werden sie beliebt, weil sie beliebt sind, werden sie kopiert, und weil sie kopiert werden, breiten sich ihre Meme -- *einschließlich der Altruismusmeme selbst* -- weiter aus als die Meme weniger altruistischer Leute. Das liefert einen Mechanismus für die Ausbreitung altruistischen Verhaltens. 
> 
> -- @blackmore_macht_2000, 252.

Daniel Dennett verarbeitet Dawkins Memetik ausführlich in seinen philosophischen Beiträgen zu Religion, Moral und der Natur des menschlichen Denkens. Sein Engagement in der Diskussion um evolutionäre Perspektiven auf die Kulturentwicklung ist ein Beleg dafür, dass Memetik -- wie schon weiter oben angedeutet -- weniger als wissenschaftliche Theorie denn als philosophische Strömung verstanden werden kann. In *Darwin's Dangerous Idea*^[@dennett_darwins_1995] betrachtet er den Kontrast zwischen der von Darwin initiierten Evolutionstheorie und Entstehungsmodellen, die übernatürliche Mechanismen -- *skyhooks* -- inkorporieren. Evolutionstheorie müsste trotz ihrer immanenten Überlegenheit als modernes, wissenschaftliches Erklärungsmodell auch eine fundierte Begründung für die scheinbare und effektive Zweckhaftigkeit und Formähnlichkeit zufälliger, biologischer Entwicklung und menschlichen Kulturhandelns formulieren. Dafür führt Dennett das Konzept des *Design Space* ein, der der natürlichen Evolution Grenzen aufzwingt und sie lenkt. Evolution versteht Dennett als streng *algorithmischen* Prozess von Anpassung durch Selektion. Memetik dient ihm als philosophisches Werkzeug, um diesen Mechanismus aus dem Natur- in den Kulturkontext zu übertragen. Das erlaubt es, sogar über den Menschen hinaus -- hinsichtlich künstlicher Intelligenz -- ein und dasselbe Erklärungsmodell für unterschiedliche Domänen zur Anwendung zu bringen. 

> Then a few billion years passed, while multicellular life forms explored various nooks and crannies of Design Space until, one fine day, another invasion began, in a single species of multicellular organism, a sort of primate, which had developed a variety of structures and capacities [...] that just happend to be particularly well suited for these invaders. It is not surprising that the invaders where well adapted for finding homes in their new hosts, since they were themselves created by their hosts [...]. In a twinkling -- less than a hundred thousand years -- these new invaders transformed the apes who were their unwitting hosts into something altogether new: *witting* hosts, who, thanks to their huge stock of newfangled invaders, could imagine the heretofore unimaginable, leaping through Design Space as nothing had ever done before. Following Dawkins (1976), I call the invaders *memes* [...].
> 
> -- @dennett_darwins_1995, 341.

> There is no denying that there is cultural evolution, in the Darwin-neutral sense that cultures change over time, accumulating and losing features, while also maintaining features from earlier ages. The history of the idea of say, crucifixion, or of a dome on squinches, or powered flight, is undeniably a history of transmission through various nongenetic media of a family of variations on a central theme. But whether such evolution is weakly or strongly analogous to, or parallel to, genetic evolution, the process that Darwinian theory explains so well, is an open question. [...] At one extreme, we may imagine, it could turn out that cultural evolution recapitulates *all* the features of genetic evolution: not only are there gene analogues (memes), but there are strict analogues of phenotypes, genotypes, sexual reproduction, [...]. At the other extreme, cultural evolution could be discovered to operate according to entirely different principles [...], so that there was no help at all to be found amid the concepts of biology. [...] In between the extremes lie the likely and valuable prospects: that there is a large (or largish) and important (or merely mildly interesting) transfer of concepts from biology to the human sciences.
> 
> -- @dennett_darwins_1995, 345-346.

Das Journal of Memetics -- Evolutionary Models of Information Transmission (JoM-EMIT) wurde als Online Zeitschrift mit Peer-Review Prozess eingerichtet. Während seiner kurzen Existenz wurden in ihm nur 45 Artikel^[http://cfpm.org/jom-emit/all.html [23.08.2018]] zu kulturevolutionärer Grundlagenforschung, Wissenschaftstheorie, Philosophie sowie Modellierung und Empirie rund um und mit der Terminologie der Memetik veröffentlicht. Die Mehrzahl der -- häufig sehr kurzen -- Beiträge beschäftigt sich mit Begriffsdefinition, der experimentellen Anwendung der Memetik auf Fragestellungen in diversen Fachbereichen sowie Vorschläge zur computerbasierten Simulation von Memeexpansionsprozessen. Obgleich das Ziel der Zeitschrift insofern erreicht wurde, als dass sie als wichtige Kommunikationsplattform für die Diskussion rund um Memetik wahrgenommen wurde, ist sie gleichermaßen die Dokumentation ihres Scheiterns als eigenständige Wissenschaft: Mehrere Autoren stellen die Aussichten der Memetik zuletzt explizit in Frage.

### Kritik {#memetics-critique}

Die Kritik an der Memetik ist vielfältig und setzt sowohl an ihren Grundsätzen als auch Details an. Auf eine umfassende Darstellung muss hier verzichtet werden^[Viele Punkte werden etwa von Tim Tyler aufgelistet (und vermeintlich entkräftet), dessen Webpräsenz http://memetics.timtyler.org/criticisms/ [23.08.2018] und Monographie *Memetics: memes and the science of cultural evolution* (@tyler_memetics_2011) ein Beleg dafür sind, welchen Anklang Memetik in pseudo- und grenzwissenschaftlichen Sphären gefunden hat]. Nur drei Angriffspunkte sollen herausgegriffen werden, die von verschiedenen Kritikern wiederholt wurden und die ich zusammen für besonders wichtig erachte, den Niedergang der Memetik zu erklären. 

1. *Die Übertragung biologischer Terminologie und Erkentnisse auf Kulturprozesse ist grundsätzlich unzulässig oder zumindest in der Memetik zu stark vereinfacht.* Diese Fundamentalkritik geht weit über die Memetik hinaus -- trifft also die Grundidee der Cultural evolution theory -- hat sich aber besonders an der niederschwelligen und gleichzeitig in Absoluten argumentierenden Memetik entladen. Sie ähnelt der frühen Kritik am Evolutionsmus durch die Boasianer (siehe Kapitel \@ref(cultural-relativism-neoevolutionism)). Einer der sichtbarsten Vertreter dieser ausgesprochen antisoziobiologischen Perspektive war Stephen Jay Gould (\*1941 - \†2002).

> I am convinced that comparisons between biological evolution and human cultural or technological change have done vastly more harm than good -- and examples abound of this most common of intellectual traps [...]. Biological Evolution is powered by natural selection, cultural evolution by a different set of principles that I understand but dimly.
> 
> -- @gould_pandas_1991, 63.

2. *Memetik bietet keine ausreichenden Ansatzpunkte für systematische Falsifizierung oder quantitative Modellierung.* Besonders aus dem Kreis jener Autoren, die tatsächlich den Versuch unternommen haben, Memetik für ihre Forschung zu applizieren, gingen mehrere hervor, die die Anwendbarkeit von memetischer Problemformulierung und Modellierung schließlich stark in Frage gestellt haben. 

> The central core, the meme-gene analogy, has not been a wellspring of models and studies which have provided "explanatory leverage" upon observed phenomena.  Rather, it has been a short-lived fad whose effect has been to obscure more than it has been to enlighten. I am afraid that memetics, as an identifiable discipline, will not be widely missed.
> 
> -- @edmonds_revealed_2005

3. *Die Terminologie der Memetik bringt keinen substantiellen Zugewinn im Kontext der Cultural evolution Forschung.* Diese Erkenntnis brachte der Memetik den Todesstoß. Cultural evolution theory entwickelte sich permanent weiter, die Bezugnahme auf den Meme Begriff war allerdings minimal -- er scheint schlicht nicht erforderlich zu sein und keinen nennenswerten Vorteil für die Beschreibung von Kulturprozessen zu bieten. 


## Themen und Konflikte der gegenwärtigen Cultural Evolution Forschung

Cultural Evolution ist heute eine wichtige theoretische Strömung der anthropologischen Forschung. Die oben unterschiedenen Perspektiven Evolutionary psychology, Human behavioural ecology und Dual inheritance theory sind Grundlage für abstrakte Modelle, Fallstudien und theoretische Weiterentwicklung. Besonders hervorgetan haben sich hier in den vergangenen 30 Jahren neben Cavalli-Sforza, Feldmann, Richerson, Boyd und Shennan auch Robert Chester Dunnell (\*1942 - \†2010), Michael John O’Brien (\*1950), Patrice A. Teltser (\*1954), Ben Sandford Cullen (\*1964 - \†1995) und eine Vielzahl jüngerer Kollegen wie Joseph Henrich, Oren Kolodny, Ken Aoki oder Alex Mesoudi. Seit 2015 konstituiert sich eine Cultural Evolution Society als interdisziplinäre Wissenschaftsvereinigung^[https://culturalevolutionsociety.org [01.02.2018]].

@creanza_cultural_2017 geben einen guten Überblick über aktuelle Fragestellungen der Cultural Evolution Forschung. Ausgehend von dieser Themensammlung werde ich einige wesentliche Zusammenhänge nachvollziehen um darauf aufbauend im folgenden Kapitel Bestattungssitten im Licht der Cultural Evolution Theorie zu diskutieren. Ein wichtiger Themenkomplex der Cultural Evolution Forschung, Kultur und Kulturentwicklung in Nicht-menschlichen Spezies^[@laland_question_2009], soll hier aufgrund seiner geringen Relevanz in diesem Kontext ignoriert werden. Ebenso die Diskussion zur Evolution von Sprache in der Linguistik^[@nowak_evolution_1999] und eine Vielzahl von Ansätzen, moderne gesellschaftlichen Problemstellungen wie Klimawandel^[@seneviratne_allowable_2016], Industrielle Landwirtschaft^[@garibaldi_farming_2017] und Multiresistente Keime^[@boni_evolution_2005] aus einer Cultural Evolution Perspektive zu analysieren. Stattdessen wird dem Themenfeld Cultural Transmission und seiner Bedeutung für archäologische Modellbildung in einem eigenen Kapitel viel Raum gegeben. 

### Unterschiede und Gemeinsamkeiten von Kulturentwicklung und Genetik 

Eine der Grundannahmen der Cultural Evolution Theorie ist die Ähnlichkeit zwischen biologischer Evolution und kultureller Entwicklung. Das schließt die Übertragung biologischer Konzepte wie Mutation, Selektion, Transmission und Drift explizit ein^[@smith_cultural_1992]. Das Methodenset der Populationsgenetik kann damit auf Kulturprozesse übertragen werden. Cavalli-Sforza und Feldmann^[@cavalli-sforza_cultural_1981], Robert Boyd und Peter Richerson^[@boyd_culture_1985] und andere^[@lumsden_genes_1981; @pulliam_programmed_1980] legten dafür in den 1980ern konkrete Ausarbeitungen oft mathematisch formulierter Modelle vor. Dennoch bestehen klare Unterschiede zwischen biologischer Populationsgenetik und der Entwicklung und Transmission von Ideen. Cultural Evolution folgt nicht den Mendelschen Regeln zu Uniformität, Spaltung und Unabhängigkeit^[@mesoudi_pursuing_2017] und große Teile der Terminologie (z.B. Genotyp vs. Phänotyp, Homozygotie vs. Heterozygotie) sind nicht oder nur unter großen Bedeutungsverschiebungen anwendbar. Horizontale Transmission spielt in der biologischen Vererbung eine untergeordnete Rolle und die Übertragung erfordert große Anpassungen an den vor allem vertikalen, genetischen Ausgangsmodellen^[@cavalli-sforza_cultural_1973; @feldman_cultural_1976]. 

Im Gegensatz zur DNS der Genetik, ist die Identität der Informationsträger kultureller Entwicklung unbekannt **hier ggf. Diskussion dazu**. Bestimmte kulturelle Eigenschaften lassen sich binär oder diskret kategorisieren, andere eher quantitativ bzw. proportional beschreiben. Zu ersteren gehören beispielsweise das technologische Wissen um Herstellung und Verwendung eines bestimmten Werkzeugs oder die Verwendung eines bestimmten Ritzmusters zur Keramikverzierung. Auch die in der vorliegenden Arbeit vorgenommene Untersuchung von Bestattungssitten reduziert diese auf die binäre Komponente der Ab- und Anwesenheit eines bestimmten Aspekts des Rituals. Analysen auf metrischem Skalenniveau wurden etwa zur Abbildung von Risikobereitschaft^[@bisin_economics_2001-1] in Gruppen oder einem Kompentenzniveau^[@baldini_revisiting_2015; @henrich_demography_2004; @kobayashi_innovativeness_2012] im Umgang mit einem bestimmten Werkzeug zur Anwendung gebracht.

### Menschliches Verhalten: Genetische Determination vs. Kulturelles Lernen

Der von [@smith_three_2000] (s.o.) beobachtete Riss durch die Forschungslandschaft zwischen Evolutionary Psychology, Human behavioral ecology und Dual inheritance theory wird besonders an der Frage deutlich, welche Aspekte menschlichen Verhaltens genetisch determiniert und welche kulturell konstruiert sind. Unter der Annahme, dass die Transmission von Ideen Menschen eine viel höhere Anpassungsfähigkeit an widrige Subsistenzumstände ermöglicht, zeigen entsprechend konzipierte Modelle, dass genetisch transportiertes Verhalten nur in ökologisch sehr stabilen Umgebungen Relevanz entwickeln kann^[@aoki_emergence_2005; @aoki_evolution_2014; @boyd_cultural_1983]. Aus dieser Perspektive ergibt sich das klare Primat kultureller Transmission für den Menschen, der sich dank seiner Kulturfähigkeit in fast alle auf der Erde vertretenen Biome hat ausbreiten können. 

Auch bei einer Dominanz sozialen Lernens und kultureller Transmission für die Prägung menschlichen Verhaltens ist der genetische Anteil nicht zu vernachlässigen -- schon allein aufgrund der häufig zu beobachtenden Korrelation zwischen einem Verhaltensmuster und biologischer Verwandtschaft. Diese Übereinstimmung ergibt sich aus vertikalen Transmissionstrukturen, die biologisch und kulturell oft parallel verlaufen. Genauso muss die natürliche Umwelt als wesentlicher Faktor bei der Determination menschlichen Verhaltens in Betracht gezogen werden. Die genaue Charakterisierung des Einflusses von Genen, Kultur und Umwelt ist unter den Stichworten Gene-Culture coevolution, Dual Inheritance theory und Cultural Niche construction intensiv diskutiert worden^[@aoki_gene-culture_2017; @boyd_culture_1985; @cavalli-sforza_cultural_1981; @chudek_culturegene_2011; @feldman_aspects_1979; @mesoudi_towards_2006; @richerson_dual_1978]. 

Die Methode der Genomweiten Assoziationsstudie (GWAS, Genome-wide association study) erlaubt es heute, Menschen und ihr Verhalten mit zunehmender Präzision auf Korrelation mit der Anwesenheit bestimmter Genen zu untersuchen. Dadurch wird die Suche nach genetischer Anpassung etwa an die naturräumliche Rahmensituation erleichtert^[@berg_population_2014]. Die Untersuchung von Verhaltensmerkmalen wie dem IQ oder dem erreichten Ausbildungsniveau mit diesem Werkzeug^[@benyamin_childhood_2014; @davies_genome-wide_2011; @minkov_genetic_2015; @okbay_genome-wide_2016] ist jedoch mit Risiken verbunden. Einerseits eröffnen die Erkenntnisse über solche Zusammenhänge ethische Implikationen, andererseits ist eine statistische Ergebnissicherheit nicht gewährleistet: Korrelation von Genen und Verhalten muss nicht Konsequenz einer kausalen Beziehung sein. Stattdessen könnte sie nur Nebeneffekt von z.B. räumlicher und sozialer Autokorrelation oder assortativer Paarung sein^[@abdellaoui_educational_2015; @domingue_genetic_2014; @okbay_genome-wide_2016; @piffer_review_2015]. Moderne Fallbeispiele, für die komplexe, sozioökonomische Erklärungen angenommen werden müssen obgleich auch genetische Korrelation besteht, beschäftigen sich unter anderem mit Tabakkonsum, Armut, Gesundheit oder Rassismus^[@maes_genetic_2006; @marden_african_2016; @nugent_geneenvironment_2011; @paradies_racism_2015].

### Mensch-Umwelt Interaktion und Cultural Niche construction

Cultural Niche construction hält ein potentes Erklärungsmodell bereit, um den wechselseitigen Selektionsdruck nachzuvollziehen, den Kultur, Gene und Umwelt aufeinander ausüben^[@laland_niche_2000; @odling-smee_niche_2003; @laland_cultural_2011; @rendell_runaway_2011]. Dabei beschreibt Niche construction in der Biologie Veränderungen der natürlichen Umwelt, die einerseits von einer Spezies selbst hervorgerufen werden und gleichermaßen die Selektionsdrücke auf diese Spezies beeinflussen^[@laland_niche_2006]. Für den Menschen ergibt sich daraus ein komplexes Geflecht von Interdependenzen zwischen Kulturverhalten, genetischer Disposition und Natur, die die schrittweise Modifikation all dieser Systembestandteile zur Folge hat^[@alberti_global_2017; @creanza_models_2012; @laland_cultural_2001]. Viel beachtete Fallbeispiele dieser Interaktion sind unter anderem anthropogen induzierte Aussterbeereignisse von Megafauna^[@barnosky_assessing_2004], Feuernutzung für Landschaftseingriffe^[@bird_fire_2008], die Ausbreitung der Links- und Rechtshändigkeit^[@laland_gene-culture_1995], die Entstehung der Laktose-Toleranz^[@feldman_theory_1989; @ingram_population_2012] und die rückläufige, demographische Entwicklung in modernen, westlichen Gesellschaften^[@borgerhoff_mulder_demographic_1998; @fogarty_role_2013; @ihara_cultural_2004].

Subsistenzbezogenes Verhalten ist unmittelbar selektionsrelevant, da es die Sterbe- und Reproduktionswahrscheinlichkeit einer Population beeinflusst. Der Mensch hat seine Versorgung über den größten Teil seiner Existenz aus Jagen und Sammeln bestritten. Dabei war er von den Ressourcen einer natürlichen Umwelt abhängig und hat sie durch Güterentnahme destabilisiert. Etliche Modelle im Kontext der Human behavioral ecology dokumentieren, wie diese Wechselwirkung zum Katalysator von Veränderung im Mensch-Umwelt System wurde^[@hardy_climatic_2010; @hockett_nutritional_2005; @stiner_thirty_2001]. Auch die Neolithisierung könnte durch einen solchen Prozess verstanden werden^[@rowley-conwy_foraging_2011; @smith_onset_2013]. 

### Mikroorganismen und Pathogene

Krankheiten sind ein wesentlicher Selektionsfaktor für den Menschen und hatten großen Einfluss sowohl auf seine biologische^[@bustamante_natural_2005; @enard_viruses_2016; mead_balancing_2003; @sabeti_genome-wide_2007@] als auch auf seine prähistorisch-kulturelle^[@martin_health_2002; @oxenham_skeletal_2005] und historische^[@alfani_plague_2013; @murray_estimation_2006] Entwicklung. Malaria hat beispielsweise wesentliche Veränderungen im menschlichen Erbgut durchgesetzt^[@kwiatkowski_how_2005; @tishkoff_haplotype_2001] -- unter anderem die weitreichende Verbreitung der Sichelzellenanämie^[@allison_protection_1954]. Die Interaktion des Menschen mit Krankheiten lässt sich nicht auf eine rein biologische Perspektive reduzieren. Stattdessen sind Krankheiten und ihre Verbreitung stark durch Kulturverhalten bedingt. Nassfeldanbau in Westafrika könnte die initiale Verbreitung von Malaria massiv begünstigt haben^[@durham_coevolution_1991-1], Krankheiten waren ein wesentlicher Bestandteil des Kulturpakets, mit dem sich die Nordamerikanischen Ureinwohner in Folge von Kolumbus Landung 1492 konfrontiert sahen^[@nunn_columbian_2010] und die Kuru Krankheit, die bis in die 1940er im Hochland von Neuguinea immer wieder in Epidemien ausbrach, war in ihrer Übertragung abhängig von kannibalistischen Ritualen^[@lindenbaum_kuru_2015]. 

Neben Pathogenen ist der Mensch auch Wirt für weniger parasitäre Mikroorganismen. Die Gesamtheit von Lebensformen, die in und auf dem menschlichen Körper leben ohne Krankheiten oder Entzündungen hervorzurufen -- die Normalflora -- hat durchaus Rückwirkung nicht nur auf den menschlichen Organismus, sondern auch auf dessen Verhalten und Verhaltensspielraum. Menschen können die Fähigkeit zur Laktoseverarbeitung beispielsweise nicht nur über eine Mutation des eigenen Erbguts erlangen, sondern auch indirekt über Bakterien im Verdauungstrakt. Solche Bakterien haben möglicherweise ebenfalls eine wichtige Rolle bei der Entstehung der Milchwirtschaft in der Vorgeschichte gespielt^[@walter_human_2011]. 

### Entstehung und Wirkung von Innovationen: Cultural Complexity und Demographie

In der biologischen Evolution entstehen neue Varianten durch Mutationen im Erbgut von Individuuen. Cultural Evolution kennt dagegen eine ganze Reihe von Prozessen, die zur Entstehung von Innovationen verschiedener Größenordnungen führen können. Viele Modelle reduzieren diese Prozesse auf simple Zufallsereignisse oder die Interaktion eines Individuums mit seiner Umwelt^[@henrich_evolution_2003; @rendell_why_2010]. Andere bringen komplexere Mechanismen ins Spiel, wie die Verknüpfung bestehender Innovationen zu neuen^[@enquist_why_2008] und die Interaktion vieler Innovationen in einer schnellen, aufeinander aufbauenden Kettenreaktion von Kombination und Ableitung^[@fogarty_cultural_2015; @kolodny_evolution_2015; @kolodny_game-changing_2016]: Eine einzige Idee zieht möglicherweise viele andere nach sich. In der prähistorischen und historischen Menschheitsentwicklung gibt es viele Ereignisse, die solche Effekte nahelegen, etwa die explosionsartige Zunahme an Komplexität im Steingerätinventar am Übergang von Mittel- zu Jungpaläolithikum^[@bar-yosef_nature_1998; @roebroeks_time_2008] oder die neolithische Revolution im Vorderen Orient^[@gopher_when_2001; @veen_agricultural_2010]. 

Die Veränderung der Menge und Art kultureller Eigenschaften einer Gruppe ist mit dem Begriff der Cultural Complexity Forschung verknüpft. Sie untersucht die Akkumulation und den Verlust von Innovationen (Cultural accumulation und Cultural decay) im Abgleich zu systemtheoretischen Gleichgewichtszuständen. Dabei zeigt sich, dass die Innovationsverfügbarkeit in einer Population durch die Verschränkung der verschiedenen Ideen starken Schwankungen unterworfen ist, bis sie einen stabilen Zustand erreicht[@kolodny_evolution_2015]. Innovationen können selbst Rückwirkungen auf die Systemdynamik ihrer Wirtpopulationen nehmen, indem sie zum Beispiel die Subsistenzbedingungen verändern und Bevölkerungswachstum oder -niedergang katalysieren^[@kolodny_game-changing_2016]. @crema_revealing_2016 eröffnen mit einer Fallstudie an neolithischer Keramik die Perspektive dafür, dass die Annahme von Gleichgewichtszustände in archäologischen Kontexten vor diesem Hintergrund hinterfragt werden muss.            

Populationsgröße und Subsistenzrisiko

@henrich_demography_2004, @collard_what_2011, @KobayashiInnovativenesspopulationsize2012, @collard_population_2013, @BaldiniRevisitingEffectPopulation2015, @henrich_understanding_2016, @vaesen_population_2016

150, 151, 152

Unabhängig davon welcher Effekt letztlich die größere Wirkung auf kulturelle Komplexität entfaltet, gibt es eindeutig einen Zusammenhang zwischen Kulturverhalten und demographischer Entwicklung einer Population: Der Übergang von einer Jäger- und Sammlerischen Lebensweise zu Ackerbau und Viehzucht am Beginn des Holozän geht mit einem starkem Bevölkerungswachstum einher, das unter dem Stichwort der *Neolithic demographic transition* als eines der folgenreichsten Auswirkungen der Neolithisierung diskutiert wird^[@bocquetappel_paleoanthropological_2002; @gage_what_2009]. Neben Subsistenzpraktiken beeinflussen eine Vielzahl von Faktoren wie religiöse Normen, Heiratsgepflogenheiten oder gewaltsame Konflikte die Altersstruktur und das Wachstum einer Gesellschaft. Etliche davon reduzieren die Geburtenrate^[@smith_cultural_1992; @colleran_cultural_2016; @richerson_natural_1984] und wirken so stabilisierend auf das Mensch-Umwelt-System. Ein Phänomen dieser Art lässt sich im modernen China und in Teilen Indiens beobachten: Eine kulturelle Präferenz für männliche Nachkommen, die sich etwa durch selektive Abtreibung manifestiert, führt lokal zu einem assymetrischen Überschuss von bis zu 6:5 von Männern gegenüber Frauen. Diese kulturell induzierte demographische Veränderung hat erwartungsgemäß schwerwiegende ökonomische Konsequenzen^[@banister_shortage_2004; @li_cultural_2000; @tuljapurkar_high_1995].       

### Altruismus

@smith_cultural_1992, 83ff.

## Cultural transmission

Die Ausbreitung von Ideen geschieht im sozialen Raum ihrer Träger. Die Formen der Kommunikation, die dabei zur Anwendung kommen sind vielfältig und entwickeln auf unterschiedlichen Skalenniveaus unterschiedliche Relevanz. Grundsätzlich bewegt sich Information mit ihren Trägern, das heißt alle Prozesse, die zur Bewegung von Menschen im Raum führen, sind auch Prozesse, die zur Ausbreitung von Information führen. Zu Cultural Transmission müssen also alle Modi des Austauschs von der Massenmigration, über den Frauentausch in Heiratsnetzwerken bis hin zum einzeln wandernden Händler und Handwerker gezählt werden. Daneben stehen Prozesse innerhalb kohärenter Gruppen, wie die Kindererziehung (vertical transmission), Lehre und Ausbildung von einer Generation zur nächsten (oblique transmission) und der einfache Austausch von Information zwischen allen Mitgliedern einer Population (horizontal transmission), wie er durch Sprache, Schrift und Imitation permanent stattfindet. 

Einige der weitreichendsten Transformationsereignisse in der Geschichte der Menschheit, die zu einem tiefgreifenden Wandel der vorhandenen kulturellen Eigenschaften geführt haben, sind von Populationsbewegungen zumindest begleitet, wenn nicht sogar initiiert worden^[@boyd_voting_2009]. Der Neanderthaler wurde vor ca. 40.000 Jahren vollständig vom Modernen Menschen verdrängt^[@skoglund_origins_2012], und mit ihm ging eine erste -- freilich in ihrer Dynamik umstrittene -- Phase kultureller Modernität zu Ende, die sich erst durch jüngste Forschungsergebnisse zu erschließen beginnt^[@hoffmann_symbolic_2018; @tuniz_did_2012]. Paläogenetische Ergebnisse legen nahe, dass die neolithische Revolution in Europa im wesentlichen von wandernden Siedlern aus dem Vorderen Orient getragen wurde, nicht von der Übernahme eines Innovationspakets durch lokale Jäger- und Sammlergruppen^[@aoki_travelling_1996; @bar-yosef_nature_1998; @patterson_modelling_2010; @skoglund_origins_2012]. Im fortgeschrittenen Neolithikum bis zum Beginn der Bronzezeit vollzog sich eine weitere genetische und kulturelle Transformation in Mitteleuropa infolge der Einwanderung berittener Steppenbewohner aus dem Yamnaya Kulturkomplex^[@allentoft_population_2015; @goldberg_ancient_2017]. 

Jenseits von Populationsbewegungen ist Cultural Transmission abhängig vom Austausch zwischen Menschen: *Social Learning*.

### Social Learning

Menschen besitzen die ausgeprägteste soziale Lernfähigkeit unter allen bekannten Spezies. Aus einer anthropozentrischen Perspektive betont das die menschliche Besonderheit, jenseits davon erweckt es aber durchaus Zweifel an der Qualität dieses Merkmals:

> What is so *wrong* with culture that it should be really conspicuous in only one species?
> 
> -- @smith_cultural_1992, 70.

Möchte man diese Frage nicht mit einem Hinweis auf evolutionäre Zufälle abtun, muss man die Natur des Selektionsdrucks untersuchen, der die enorme Intensivierung von Imitation begünstigt hat. Prominente Methoden zur Erforschung dieser Frage sind soziale Experimente mit Menschen unter konstruierten Bedingungen, mathematische Modelle auf Populationsniveau und agentenbasierte Computermodelle. Die folgenden Erkenntnisse basieren vor allem auf minimalistischen mathematischen und computerbasierten Modellrechnungen:

Soziales Lernen steht neben genetischer Vererbung und individuellem Lernen. Während individuelles Lernen große Flexibilität mit sich bringt, dafür aber auf das Individuum begrenzt ist, wirkt genetische Vererbung nur auf dem Populationsniveau und damit gemessen an der Lebensspanne des Einzelnen sehr langsam. Soziales Lernen steht zwischen diesen Polen und erlaubt sowohl kurzfristige und kleinräumige, als auch langfristige, kummulative und populationsweite Anpassung. Während individuelles Lernen und Experimentieren viel Zeit und Energie in Anspruch nehmen kann, kann soziales Lernen Wissen über einen Sachverhalt unmittelbar und risikoarm transportieren. Gefährliche Fehler beim individuellen Lernen, die durch die für den Einzelnen geringe Anzahl von Experimentdurchläufen häufig sind, können durch soziales Lernen vermieden werden^[@boyd_evolution_1988]. Es ist dafür allerdings anfällig für schnelle und schnell aufeinanderfolgende Veränderungen der natürlichen Umweltbedingungen, da gegebenefalls ein unangepasstes Verhalten traditionell weitergeführt wird^[@rogers_does_1988]. Vergleicht man eine Kombination von genetischer Anpassung und individuellen Lernen einerseits mit einer Kombination von sozialem und individuellem Lernen andererseits, dann führen erstere nur dann zu besserer Anpassung, wenn die Umgebung nahezu unverändert bleibt oder sich enorm schnell und völlig zufällig verändert. In den Fällen zwischen diesen Extrema ist soziales Lernen überlegen^[@boyd_culture_1985, 117-128.]:

> A cultural system of inheritance combining individual and social learning ought to provide adaptive advantages in environments with an intermediate degree of environmental similarity from generation to generation. This is the regime where the faster tracking due to the evolutionary force of cumulative, relatively weak, low-cost individual learning pays off most. Most individuals can depend primarily on tradition, yet the modest pressure of individual learning is sufficient to keep culture "honest".
> 
> -- @smith_cultural_1992, 73.

Diese Hypothesen sind außerhalb der künstlichen Modellumgebungen aus denen sie abgeleitet wurden schlecht überprüfbar. Fallstudien mit bedingt sozial lernfähigen Tieren wie Ratten könnten zur Prüfung der Hauptaussagen geeignet sein. Für die menschliche Entwicklung müssen entsprechende empirische Belege im archäologischen Befund ausgemacht werden. Geht man von einer Korrelation von Gehirngröße und sozialer Lernfähigkeit aus, dann könnten zum Beispiel anthropologische Daten aus dem klimatisch variablen Pleistozän als starkes Indiz auftreten^[@smith_cultural_1992].

Soziales Lernen kann zur Konsequenz haben, dass schädliches -- also für genetische Reproduktion ungeeignetes -- Verhalten unter positiven Selektionsdruck gerät und sich verbreitet. Genetische Disposition und individuelles Lernen können diesem Effekt entgegenwirken. Wenn etwa eine strenge Religion Prüderie und Abkehr vom Weltlichen propagiert, kann sexuelles Verlangen und eine Liebe zu Kindern der familienverneinenden Ideologie entgegenwirken. Oft sind die Vor- und Nachteile einer Verhaltensform für den Einzelnen oder die Gesamtpopulation allerdings nicht so offensichtlich. Die genetische Anlage des Menschen sieht für komplexes Kulturverhalten keine adequate Reaktion vor und der Einzelne ist mit der Evalutation vieler Fragen überfordert.  

> The natural world is complex, hard to understand, and variable from place to place and time to time. Is witchcraft effective? What causes malaria? What are the best crops to grow in a particular location? Are natural events affected by human pleas to their governing spirits? [...] What sort of person(s) should one marry? What mixture of devotion to work and family will result in the most happiness or the highest fitness? 
> 
> -- @smith_cultural_1992, 79.

Dabei treffen Menschen selbst komplexe Entscheidungen oft auf Grundlage stark vereinfachter Faustregeln. Die investierte Mühe ergibt sich als Kompromiss zwischen der erwarteten Belohnung einer richtigen Entscheidung und den Kosten der Informationssammlung^[@nisbett_human_1980]. Eben weil damit nicht viel Kapazität für nicht drängenden Entscheidungen übrig bleibt, ist Kultur im wesentlichen ein Vererbungssystem. Ein großer Teil der Fähigkeiten, Glaubens- und Moralvorstellungen des Individuums hat es von anderen übernommen, ohne sie zu hinterfragen. Das macht das Verhalten von Menschen anhand des kulturellen Milieus aus dem sie stammen vorhersagbar^[@smith_cultural_1992].      

Zur näheren Charakterisierung der zwischenmenschlichen Informationsvererbung grenzen
[@cavalli-sforza_cultural_1981] drei Formen des Sozialen Lernens voneinander ab: *Vertical Transmission*, *Horizontal Transmission* und *Oblique Transmission*: 

Die vertikale Vererbung kultureller Eigenschaften von Eltern zu Kind spielt eine entscheidende Rolle. 

Vertical Transmission ist stark mit der demographischen Entwicklung einer Population verknüpft. Geht man von einem klassischen Modell der Life-history-Theorie aus, das Populationsentwicklung auf Grundlage von sich reproduzierender Altersklassen beschreibt^[@leslie_further_1948] und erweitert es um kulturelle Merkmale und Transmission, dann ergeben sich bemerkenswerte Simulationsergebnisse^[@coratenuto_age_1989; @fogarty_role_2013]. Sogar Verhaltensmuster, die die Reproduktionsfähigkeit eines Individuums reduzieren, können bei ausreichend starker Übertragungsfähigkeit dauerhaft relevant bleiben. Das gilt besonders dann, wenn eine Idee zwar die Reproduktionsfähigkeit reduziert, gleichzeitig aber die Überlebenschance des Individuums erhöht.  

 [@mulder_intergenerational_2009]

*Horizontal Transmission* 

*Oblique Transmission* [@fogarty_evolution_2011]

Horizontaler und Schräger Austausch von Ideen ist günstig um einem Individuum möglichst viel Auswahl an Strategien zur Verfügung zu stellen, aus denen es zur Lösung von Problemen wählen kann. Umso stärker diese Formen der Cultural Transmission in einer Gesellschaft ausgeprägt sind, desto mehr verschiebt sich der Selektionsdruck zugunsten von sozialen Führungsrollen wie die von Lehrern, Priestern oder Großeltern. Elternschaft kann demgegenüber ins Hintertreffen geraten. Ein solches Verhaltensmuster ist für genetische Selektion ungünstig, da Kinder unter diesen Umständen nicht die biologische Reproduktion, sondern andere Lebensmodelle anstreben können^[@smith_cultural_1992]. 

Social Learning: [@arbilly_arms_2014; @enquist_evolution_2007; @rendell_cognitive_2011; @rendell_rogers_2010]

### Entscheidungsprozesse

Die Intensität und Dauerhaftigkeit der Verbreitung einer Idee in einer Gesellschaft ist chaotisch und nicht mit Sicherheit vorhersagbar. Dennoch lassen sich Effekte beschreiben, die wesentlichen Einfluss auf den Erfolg einer Innovation haben. Menschen treffen die Entscheidung ob sie eine Idee oder ein Verhaltensmuster übernehmen nicht zufällig. Stattdessen evaluieren sie oft sowohl wen als auch was sie in der jeweiligen Situation imitieren. Um so leichter es ist, die Vor- oder Nachteile verschiedener Verhaltensmuster zu erkennen, desto schneller kann die Entscheidung für oder gegen einzelne getroffen werden. Die Konsequenz des Evalutationsverhaltens ist *Biased Transmission*. Ihr Gewicht nimmt zu, wenn dem Einzelnen durch mehr kulturelle Vielfalt eine größere Auswahl untschiedlicher Verhaltensmuster zur Verfügung steht^[@smith_cultural_1992].

Menschen zeigen beispielsweise die Tendenz, das Verhalten erfolgreicher Menschen oder einzelne, erfolgreiche Strategien zu übernehmen^[@henrich_evolution_2003]. Zwar ist das Modell eines Homo Ökonomikus, der stets die rational beste Entscheidung in einer gegebenen Situation trifft, zu einfach, dennoch spielt die Verbesserung der eigenen Situation nach unterschiedlichen Kriterien eine wichtige Rolle bei Entscheidungsprozessen^[@mesoudi_cultural_2008; @mesoudi_experimental_2011]. Die klassische *Diffusion of Innovation* Forschung identifiziert den individuell wahrgenommenen Vorteil als wesentliches Kriterien zur Übernahme oder Ablehung einer Neuerung^[@rogers_diffusion_1983]. Aus der Perspektive der Behavioural ecology kann argumentiert werden, dass das Nervensystem hinreichend komplexer Lebewesen grundsätzlich Verhaltensweisen bevorzugt, die zu positiven Stimuli führen. Das sind oft gleichzeitig jene, die für die Anpassung an eine Umgebung förderlich sind. Biologisch oder durch vormalige Lernprozesse determinierte Lernregeln führen in einem Prozess von *Guided Variation* zur Selektion von Verhaltensmustern^[@smith_cultural_1992]. Dieser postulierte Automatismus besitzt Implikationen für eine mögliche biologische Selektionswirkung von Innovationen: Imitation kann den Untergang einer Population in Krisensituationen verhindern oder zumindest die Anpassung an Umweltveränderungen erheblich beschleunigen und so den mit biologischer Selektion oft verbundenen Bevölkerungsrückgang vermeiden. 

Ein Dualismus von Konformität (*Conformity Bias*) und Neugierde (*Novelty bias*) ist entscheidend dafür, ob und wie Innovationen sich in einer Population verhalten. Menschen neigen besonders in Phasen von Stabilität dazu^[@henrich_evolution_1998; @kendal_evolution_2009], das Verhalten einer Bevölkerungsmehrheit zu übernehmen^[@efferson_conformists_2008; @giraldeau_social_1994; @henrich_evolution_1998]. Dieser *Frequency Bias* hat zur Konsequenz, dass sich Ideen, die ohnehin schon weit verbreitet sind, weiter stabilisieren können und Neuerungen, die in direkter Konkurrenz zu vorhanden Konzepten stehen, nur langsam an Relevanz gewinnen oder verschwinden: Ein sich selbst verstärkendes System. Insbesondere Ideen, die nicht direkt subsistenzrelevant sind, sind in ihrer momentanen Ausbreitungsdynamik stark davon abhängig, wie groß die Verbreitung der Idee in der Population bereits ist. Eindrucksvolle Beispiele dafür sind unter anderem Kleidermode oder Babynamen^[@acerbi_biases_2014; @acerbi_logic_2012]. Ist eine Population in teilweise isolierte Gruppen aufgeteilt, erwirkt ein starker Frequency Bias Homogenität innerhalb und Heterogenität außerhalb von Gruppen. Die bei biologischer Evolution umstrittene *Group Selection* kann damit im Kontext von Cultural Evolution durchaus starke Wirkung entfalten^[@smith_cultural_1992]. 

Trotz des Frequency Bias brechen Individuuen jedoch mitunter bewusst aus dem Verhalten der Mehrheit aus^[@henrich_evolution_2003]. Als Konsequenz des Widerstreits dieser Pole folgt die Verbreitung kultureller Eigenschaften oft einer logistischen, S-förmigen Wachstumskurve^[@henrich_cultural_2001]. Neue Ideen werden zunächst von einigen, meist wohlhabenden und gut gebildeten *Innovators* eingeführt bis die ökonomisch empfindlichere *Majority* sie übernimmt und nur wenige konservative *Laggards* zurücklässt, die sich der Neuerung bewusst verweigern^[@rogers_diffusion_1983]. 

In archäologischen Zusammenhängen wird häufig über den Einfluss sozialer Eliten auf das Verhalten einer Gesamtpopulation diskutiert. Tatsächlich tendieren Menschen dazu, soziale höher gestellte Vorbilder zu wählen und sie zu kopieren^[@henrich_evolution_2001]. Dieses Kopierverhalten lässt sich experimentell bereits an Kleinkindern beobachten, die sich an jenen Erwachsenen orientieren, die die verstärkte Aufmerksamkeit anderer Erwachsenen genießen^[@chudek_prestige-biased_2012]. *Prestige Bias* führt zu *Indirect Bias*: Menschen wählen ihre Vorbildern oft aufgrund weniger auszeichnender Charakteristika aus. Sie neigen auch dazu, neben den ursprünglich ausschlaggebenden Eigenschaften weitere Verhaltensmuster des Vorbilds zu übernehmen. Das hat zur Konsequenz, dass Konzepte, die für sich genommen keine oder nur geringe Ausbreitung erfahren würden, mit anderen Konzepten transportiert werden. Einerseits kann dank dieser Tendenz mehr Information schneller verbreitet werden, andererseits können sich so auch Ideen durchsetzen, die ihrem Träger keinen Vorteil oder sogar Nachteile bringen können. Trotz dieses Nachteils kann es evolutiv sinnvoll sein, einfach das gesamte Verhalten erfolgreicher Individuuen zu übernehmen -- ohne kostenaufwändige Reflektion darüber, welche Muster genau den Erfolg herbeiführen^[@smith_cultural_1992]. 

> If wealth partly derives from subsistence or social skills that can be acquired by imitation, it makes adaptive sense to imitate the wealthy. The assumption that wealth is correlated with adaptive behavior is perhabs generally correct; if so it would be sensible to imitate wealthy people even if it is not always very clear just what components of wealthy people's behavior are adaptive.
> 
> -- @smith_cultural_1992, 81.

Soziale Hierarchien und Prestigesysteme können als Hilfsmittel dienen, um zu entscheiden, welche Eigenschaften und Verhaltensweisen übernommen werden sollten^[@rogers_diffusion_1983]. Gerade arme und schlecht gebildete Gruppen orientieren sich oft and Führungspersonen, die über mehr Risikokapital verfügen, das sie für die Evalutaion von Innovationen investieren können. Dabei werden bevorzugt Menschen imitiert, die lokal präsent sind und in ähnlichen Umständen leben wie der Imitierende.  

Ein Phänomen, das für vertikale Transmission besondere Relevanz besitzt, ist Assortative Paarung (Assortative mating). Partnerwahl beim Menschen ist kein zufälliger Prozess, sondern zeigt die Tendenz, Individuen mit hoher Ähnlichkeit körperlicher und kultureller Merkmale zusammen zu führen. Ein Nachweis dieses Effekts gelang an Merkmalen wie Augenfarbe, Körpergröße, IQ, Bildungsstand und Tabakkonsum^[@domingue_genetic_2014; @keller_genetic_2013; @laeng_why_2007; @treur_spousal_2015]. Assortative Paarung führt zu höherer Korrelation genetischer und kultureller Eigenschaften in einer Population und kann mehr Vielfalt hervorrufen^[@feldman_evolution_1977; @rice_multifactorial_1978]: Seltene Eigenschaften können sich leichter ausbreiten und behaupten^[@creanza_complexity_2014; @creanza_models_2012]. Assortativer Paarung ist dabei auch ein sich selbst verstärkender Prozess, da aus Beziehungen ähnlicher Partner statistisch mehr Kinder hervorgehen^[@thiessen_human_1980] und soziale Netzwerke dazu neigen, sich zu reproduzieren^[@abdellaoui_association_2013; @abdellaoui_educational_2015]. Das hat auch Rückwirkungen auf die genetische Zusammensetzung von menschlicher Populationen^[@robinson_genetic_2017]. Sprachgrenzen können dabei als wesentliche Hürde beim genetischen Austausch auftreten^[@barbujani_zones_1990; @de_filippo_y-chromosomal_2011; @karafet_coevolution_2016], müssen es aber keinesfalls^[@hunley_gene_2005; @hunley_genetic_2008; @srithawong_genetic_2015]. Homophily, die Präfenrenz mit ähnlichen Menschen zu interagieren, beschränkt sich nicht nur auf die Partnerwahl, sondern erstreckt sich auf jede Form zwischenmenschlicher Beziehung: Ideen werden grundsätzlich schneller zwischen ähnlichen Individuen übertragen^[@centola_experimental_2011; @centola_spread_2010]. 

### (Computerbasierte) Modellierung

Cultural Evolution theory ist angelegt zur Modellbildung in Anthropologischen Wissenschaften. Edmonds definierte Memetik vor seiner oben nachvollzogenen Abkehr folgendermaßen:

> the application of models with an evolutionary or genetic *structure* to the *domain* of (cultural) information transmission. 
>
> -- @edmonds_modelling_1998

Im selben Artikel *On Modelling in Memetics* aus dem 2. Band des Journal of Memetics weist er aber bereits auf Risiken der Modellierung in diesem Kontext hin und formuliert Anforderungen. 



\pby[title={Literatur},segment=\therefsegment,heading=subbibintoc]
