# Bestattungsritus in der Europäischen Bronzezeit

## Fallbeispiel und Betrachtungsperspektive

Ziel dieser Arbeit ist die Formulierung eines computerbasierten Cultural Evolution Modells, dass .... Um die Sinnhaftigkeit dieses Ansatzes zu erforschen, ist es unerlässlich ein Fallbeispiel heranzuziehen, das potentiell geeignet ist durch ein solches abgebildet zu werden. Für den Kontext des Fallbeispiels sollen sich idealerweise Synergieeffekte ergeben. Das heißt, das Modell sollte geeignet sein, archäologische Fragestellungen in seinem Kontext zu beantworten oder zumindest aus einer neuen Perspektive zugänglich zu machen. Scheitert dies, so ist zwar nicht der gesamte Ansatz zu verwerfen, jedoch darf die Nützlichkeit der Methode aus archäologischer Perspektive in Zweifel gezogen werden. 

Die Wahl des Fallbeispiels hat also wesentliche Konsequenzen für das Gesamtergebnis der Arbeit. Konkret drückt sich das etwa in der Natur der untersuchten Meme und Memeplexe aus: Unmittelbar funktional relevante Meme, die z.B. eine Veränderung der Subsistenzsstrategie hervorrufen, sind anders zu analysieren als Modememe in Keramikverzierung und Gewandschmuck. Manche Meme sind äußerst erfolgreich, breiten sich über ganze Kontinente aus und bleiben über Jahrhunderte verhältnismäßig stabil, andere dagegen sind nur auf eine eine Siedlung beschränkt und überdauern nicht einmal ihre Schöpfergeneration. Jedes Fallbeispiel ist über eine Auswahl archäologischer Daten zugänglich. Diese sind höchst heterogen strukturiert, mit unterschiedlichen Zielsetzungen -- meist nicht der einer Cultural Evolution Analyse -- aufgenommen und decken, ebenso wie die Meme, die sie potentiell abbilden, sehr verschiedene zeitliche und geographische Spektren und Skalenniveaus ab. Ideal wäre sicher, selbst Daten zu zu einzelnen Memen und deren Entwicklung zu sammeln. Das ist aber im Rahmen dieser Arbeit nicht möglich, ohne viel Zeit zu verlieren, die für theoretische Vorüberlegungen sowie die Modellimplementierung und -Analyse investiert werden sollte. Die Suche nach einem Fallbeispiel war aus dieser Konsequenz gleichermaßen die Suche nach einem Datensatz, bei dem Anküpfungspunkte zur Modellidee zu erwarten waren. 

Ein spezielles Subset der C14-Datenbank Radon-B^[@jutta_kneisel_radon-b_2013] erfüllt diese Bedingung. 

Brandbestattung und Körperbestattung sind Meme, die schon lange vor Beginn der Bronzezeit in Konkurrenz standen. Erstaunlicherweise ist dieser Konflikt bis heute nicht entschieden -- beide Bestattungsrituale, freilich immer wieder neu konnotiert und kontextualisiert -- finden in der Gegenwart in Europa Anwendung. Man könnte den Konflikt aus dieser Perspektive in seiner gesamten zeitlichen Dimension von der frühesten Vorgeschichte bis in die Moderne nachzeichnen. Die Cultural Evolution Perspektive bietet für dieses Phänomen ein kohärentes Erklärungsmodell. Dennoch konzentriert sich diese Arbeit auf die Bronzezeit. Das geschieht einerseits aufgrund der zur Verfügung stehenden Daten und weiterhin aufgrund der unglaublichen Komplexität der Memeplexe, in die sich beide Meme im Laufe der Geschichte eingegliedert haben. Eine Geschichte von Brand- und Körperbestattung würde den Rahmen dieser Arbeit bei weitem sprengen, ist vielleicht überhaupt nicht sinnvoll formulierbar. Ähnlich verhält es sich mit der Grabüberhügelung: Auch dieser Brauch kann auf eine lange Geschichte zurückschauen und hat im Laufe der Zeit mannigfaltige, verwandte weil abgeleitete Meme hervorgebracht. 

Dieses Fallbeispiel beobachtet also vier eng verknüpfte Meme (Körperbestattung, Brandbestattung, Flachgrab, Hügelgrab) über eine gewisse Phase (2500-500calBC, Bronzezeit) ihrer eigentlich wesentlich längeren Entwicklung in einem gewissen Raum (Nord-, Ost und Westeuropa), der nur einen Auschnitt ihrer eigentlichen Verbreitung darstellt.

## Vorüberlegungen zur archäologischen Untersuchung von Bestattungen

Betrachtet man Bestattungssitten als in Raum und Zeit verbreitetes Kulturverhalten dann kann man das doch nicht gänzlich losgelöst von seiner besonderen Qualität als mit dem Tod assoziiertem Verhalten tun. Bestattungssitten sind weder funktional -- obgleich auch aus hygienischer Perspektive und hinsichtlich Materialkosten und Arbeitszeit für oder gegen bestimmte Rituale argumentiert werden kann -- noch sind sie Mode, die leichtfertig und ohne Reflexion übernommen wird. Der Tod von Angehörigen ist meist ein schwerwiegendes Ereignis, das mit einem besonderen, kulturellen und individuellen Verarbeitungsprozess einhergeht. Bestattungssitten gehören eben zu diesem Verarbeitungsverhalten und sind als solche Gegenstand ihrer Erforschung.

Thanatologie ist die Wissenschaft des Todes und seiner Wirkung auf die Umwelt des Sterbenden und Verstorbenen. Sie ist interdisziplinär angelegt und beschäftigt sich mit allen biologischen, sozialen, psychologischen und sonstigen Prozessen im Kontextes des biologischen und speziell menschlichen Todes^[ @hofmann_rituelle_2008, 100.]. Thanatoarchäologie beschäftigt sich mit dem Tod in archäologischen Kontexten, also mit dem Niederschlag, den der Tod von Menschen im archäologischen Befund hinterlassen hat^[@hofmann_rituelle_2008, 123.]. Der wichtigste Befundtyp hierfür ist das Grab, das umgekehrt eine der wichtigsten Forschungsgegenstände der Archäologie im allgemeinen darstellt. Seiner Erforschung wird vor dem Hintergrund chronologischer und sozialer Fragestellungen viel Aufmerksamkeit gewidmet. Dennoch bleibt ein großer Teil der mit Gräbern assoziierten Bedeutungsbelegung unbekannt, da Gräber sich nur aus der Wahrnehmung des Todes ihn ihrer Erzeugerkultur und deren Vorstellungen pränataler- und postmortaler Zustandsformen in Abgrenzung zum bekannten irdischen Leben verstehen lassen. Archäologische Quellen geben über diese spirituellen Abstraktionen keinen oder nur sehr eingeschränkt Aufschluss. 

Eben daraus erwächst die große Gefahr, in Ermangelung des Wissens über das Todesverständnis prähistorischer Gesellschaften moderne, westliche Vorstellungen auf archäologisch erschlossene Grabzusammenhänge zu projizieren. Eine eurozentrisches Verhalten, das insbesondere die Postprozessuale Archäologie in Anlehnung an die Postmoderne identzifiziert hat. Stattdessen muss eine Auseinandersetzung mit dem breiten Spektrum an Weltanschauungen und Wahrnehmungen erfolgen, in die Bestattungssitten eingeordnet werden können. Vollständigkeit kann dabei nicht erreicht werden, aber zumindest eine erhebliche und wertvolle Aufweitung der Perspektive.

### Der rituelle Umgang mit dem Tod

Kerstin Hofmanns Dissertationsschrift *Der rituelle Umgang mit dem Tod -- Untersuchungen zu bronze- und früheisenzeitlichen Bestattungen im Elbe-Weser-Dreieck*^[@hofmann_rituelle_2008] enthält einige theoretische Vorüberlegungen zur Thanatoarchäologie, die ich hier verarbeiten und einer Betrachtung von Bestattungssitten im Kontext der Cultural Evolution Theorie voranstellen möchte. Damit soll einerseits einer simplistischen und eurozentristischen Deutung von Gräbern vorgebeugt, andererseits die Besonderheit der Bestattungsmeme betont werden.

#### Sterben als Prozess

Die Feststellung, ab wann genau ein Mensch Tod ist, ist mit erstaunlichen Unsicherheiten und Unschärfen verknüpft. Diese nehmen ihren Anfang bei den biologischen Prozessen, die es erlauben, den Eintritt des Todes an verschiedenen Parametern zu messen und entsprechend unterschiedlich festzulegen. Leben drückt sich im Menschen in verschiedenen Körperfunktionen wie Atmung, Herzschlag oder Stoffwechsel aus. Der Ausfall eines Teilsystems bewirkt je nach seiner Relevanz mehr oder weniger schnell den Zusammenbruch aller anderen Systeme. Das kann sich über einen langen Zeitraum hinziehen: Auch im Falle des normalen, sukzessiven Ausfalls aller Teilsysteme stirbt die letzte Körperzelle viele Stunden nach dem Kreislaufstillstand. Da die Individualität eines Menschen an die intakte Funktion seines Gehirns gebunden ist, gilt der Kollaps dieses Teilsystems als eines der wesentlichen Definitionsmomente für den Eintritt des Todes. Umgekehrt kennt die Medizin mit dem Hirntod auch den Sonderfall, dass nur das Gehirn seine Funktion mit irreperablen Schäden eingestellt hat, alle anderen Körperprozesse allerdings weiter funktionieren. Der Hirntod kann nur klinisch diagnostiziert werden (Harvard-Kriterium), da in diesem Fall andere Indikatoren für den Eintritt des Todes fehlen. Letztere lassen sich grundsätzlich in unsichere und sichere pathophysiologische Kriterien untergliedern. Zu den unsicheren gehören ein Abkühlen des Körpers, Reflexlosigkeit, Erschlaffen der Muskeln, Pulslosigkeit, Atemstillstand, Leichenblässe und ein Vertrocknen an Schleimhäuten und Wunden. Obgleich diese traditionellen Todesanzeiger weitreichend bekannt sind und im Laufe der Geschichte wesentlich für die Feststellung des Todes waren, sind sie einzelnen oder sogar bei gemeinsamem Auftreten nicht verlässlich. Sie können (zumindest kurz- bis mittelfristig) als Folge von Erkrankungen oder Umgebungsparametern auftreten. Pulslosigkeit und Atemstillstand sind, wenn der Zustand anhält, sichere Todesanzeichen. Dazu gehören auch Totenflecken -- rötliche Verfärbungen an der Körperunterseite infolge der Unterbrechung des Blutflusses -- und die Totenstarre -- eine biochemische Körperreaktion, die zur Erstarrung der Muskulator in einem Zeifenster von 6-9 bis 50-300 Stunden nach dem Todeszeitpunkt führt. Völlig unzweifelhafte Todesanzeiger sind schließlich spätere Veränderungen an der Leiche wie Autolyse (Selbstauflösung/Selbstverdauung), Fäulnis, Mumifizierung, Fettwachsbildung und Skelettierung^[@hofmann_rituelle_2008, 92-94.].

Der mit naturwissenschaftlichen Kriterien messbare Tod ist in einer modernen, westlich geprägten Gesellschaft oftmals die entscheidende Form des Todes. Tatsächlich ergeben sich aber neben dieser biologisch-technischen auch fundamental abweichende Perspektiven, die den Tod durch seine Kontextualisierung im kulturell-sozialen Gefüge des Verstorbenen verstehen. Der Tod ist dabei der Abbruch der sozialen Beziehungen. Dieses Ereignis muss nicht mit dem biologischen Tod einhergehen. Tatsächlich kann sowohl ein biologisch Lebender aus einer Gemeinschaft ausgeschlossen und damit für "tot" erklärt werden, als auch ein biologisch Toter -- etwa im Kontext eines Ahnenkults -- weiter in zwischenmenschliche Interaktion einbezogen und wie ein Lebender behandelt werden. Vor diesem Hintergrund hält Hofmann die Einschätzung ob jemand tot ist oder lebendig für von kultureller Wahrnehmung abhängig:

> Niemand kann demnach eine Todesfeststellung kulturfrei vornehmen.
>
> -- @hofmann_rituelle_2008, 92.

Das Urteil, ob biologischer und sozialer Tod gleichzeitig eingetreten sind, ist darüber hinaus stark mit der Art des Todes verknüpft, die den Verstorbenen ereilt hat. Ein schneller Unfalltod, ein Mord, ein Tod in kriegerischem Konflikt oder ein langsames Dahindämmern infolge von Alter oder Krankheit werden unterschiedlich wahrgenommen und sind kulturell unterschiedlich konnotiert. Oftmals ist genau das Auschlaggeben dafür, ob sich der Tod im Einzelfall Angehörigen und Beobachtern als schnelles, unumkehrbares Überschreiten einer Linie oder als länger andauernder Transformationsprozess darstellt. Den Rahmen für diese Unterscheidung bilden Vorstellungen von postmortalem Leben, das das irdische Leben fortsetzt oder mit ihm interagieren kann. Damit ist der Tod und seine Erfahrung eng mit grundsätzlichen, weltanschaulichen Fragen verknüpft, denen jede Kultur mit anderen Paradigmen begegnet^[@hofmann_rituelle_2008, 94-95.].

#### Kulturübergreifende Wahrnehmung des Todes

Wie und mit welchen Hoffnungen und Ängsten der Einzelne dem eigenen oder dem Tod anderer Menschen begegnet, hängt von einer Vielzahl von Faktoren ab. Prägend dafür ist ein Erfahrungshorizont, der sich aus Kultur- und Religionszugehörigkeit ergibt, aber auch individuellen Eigenschaften und Erfahrungen.

> Die Einstellung zum Tode entstehen aus der dynamischen, sich verändernden Wechselwirkung zwischen Individuum und Umwelt und sind mit dem individuellen und kollektiven Bild von Mensch, Natur und Gesellschaft verknüpft. 
>
> -- @hofmann_rituelle_2008, 96.

Nach moderner, naturwissenschaftlicher Erkenntnis muss jeder Mensch sterben. Diese Wahrnehmung hat ihren Ursprung wahrscheinlich in der Antike, ist allerdings nicht universell menschlich. In indigenen Gesellschaften wird der Tod oft als etwas unnatürliches und fremdes gedeutet, dass durch schädliche äußere Einflüsse -- etwa durch Flüche oder den Eingriff von Gottheiten -- ausgelöst wird. Viele Schöpfungssagen beschreiben einen Urzustand, in dem der Tod noch nicht existierte. Erst ein durch Versehen oder Unwissenheit ausgelöstes Ereignis habe ihn in die Welt gebracht. Oft wird ein "guter", von der Gemeinschaft begleiteter Tod von einem "schlechten", einsamen in der Fremde abgegrenzt. 

Der Glaube an ein postmortales Weiterleben ist in der Mehrzahl bekannter Kulturen verbreitet. Die Auflösung des Körpers im Anschluss an den Tod mag ein wichtiger Grund dafür sein, dass die meisten das auch mit einer Trennung von Körper und Seele in Verbindung bringen. Die Seele vollzieht einen Transformationsprozess -- eine Reise ins Reich der Toten -- der sich über einen gewissen Zeitraum hin erstreckt. Oft werden Verstorbene in diesem Übergangsstadium als gefährlich empfunden, da sie sowohl Macht als auch das Interesse zur Interaktion mit der Welt der Lebenden besitzen könnten. Im Gegensatz zum Personenkonzept des westlichen Individualismus, der Menschen als Einheit aus einem Körper und einer unteilbaren Seele versteht, unterscheiden andere Gesellschaften gegebenfalls mehrere Seelenkategorien, die im Todesfall unterschiedlich reagieren, oder etwa durch unterschiedliche Rituale wie Kremation freigesetzt werden müssen. Unabhängig davon ist die Seele jedoch in vielen Weltanschauungen die Entität, die im Jenseits weiterlebt. Das Totenreich ist in verschiedenen Kulturen mit vielfältigen Assoziationen belegt -- häufig mit dem Bild des Schlafens, einer spiegelbildlichen Parralelwelt zum irdischen Dasein oder mit Mechanismen, die Ausgleich und Sühne schaffen sollen. Kulturen, die ein Reinkarnationskonzept verinnerlicht haben, verstehen den Tod meist nur als eine kurze Phase zwischen zwei Daseinsformen.

In ausnahmslos allen Kulturen gibt es ein Totenbrauchtum, das den Umgang mit Verstorbenen regelt. Die praktizierten Handlungen wie Leichnamsvorbereitung, Bestattung, Totenmahlzeit, Besuchsfeste oder Wiederbestattungen sind höchst vielfältig und stark von den oben beschriebenen, ideologischen Voraussetzungen abhängig. Ebenso sind Zweck und Bedeutung der Riten unterschiedlich. Sie zeigen jedoch kulturübergreifend einige Gemeinsamkeiten und richten sich grundsätzlich sowohl an die Toten als auch die Lebenden. Viele Rituale dienen dazu, das emotionale Trauma und die Trennung zu verarbeiten. Darüber hinaus soll der Zusammenhalt der Bestattenden sozialen Gruppe auch über den Tod des Verstorbenen hinaus aufrecht erhalten werden. Dabei kanalisieren die rituellen Handlungen den kritischen Übergangsprozess von der dauerhaften An- zur Abwesenheit des Individuums. Bestattungsbräuche können auch aus einer Angst vor dem Toten hervorgehen und dazu dienen, ihn zu bannen, zu besänftigen oder zumindest seinen Einfluss auf die Lebenden zu verringern. Umgekehrt existiert mit der Totenfürsorge ein Verhalten, den Verstorbenen mit Grabbeigaben für sein postmortales Dasein auszustatten oder ihn mit Wegzehr für die Reise ins Totenreich zu versehen. Bestattungsrituale können auch dazu dienen formalisiert zu Erinnern und eine bestimmte Form der Erinnerung an den Toten zu konstruieren. Weltanschauung und Moralvorstellungen können gegebenfalls in der Gruppe durch Repetition und den besonderen Charakter des Anlasses vertieft werden. Eben hieran wird deutlich, dass Bestattunsriten nicht losgelöst, sondern in den religiösen, sozioökonomischen, politischen und sonstigen Kontexten einer Gesellschaft verankert sind. Umfang und Komplexität einer Beisetzung hängen oft stark von der Ausprägung der sozialen Hierarchien und der individuellen Position des Verstorbenen darin ab. Eine systemtheoretische Perspektive macht deutlich, wie sehr Totenbrauchtum von anderen Subsystem der Gesellschaft abhängen und diese widerspiegeln kann^[@hofmann_rituelle_2008, 96-99.].

#### Tod in den anthropologischen Wissenschaften

Hm... Das könnte ein wenig zu viel sein...
ggf. @hofmann_rituelle_2008, 100-122.

Genauso die Forschungsgeschichte der Thanatoarchäologie...
ggf. @hofmann_rituelle_2008, 132-140.

#### Die Erforschung des Todes in der prähistorischen Archäologie

Vergangenes, menschliches Kulturverhalten lässt sich nur über das Medium archäologischer Quellen erschließen. Diese Materielle Kultur spiegelt den eigentlichen Forschunsgegenstand allerdings nur mehrfach und stark gefiltert wieder. Selbst ihre eigene Bedeutung lässt sich nur indirekt und unvollständig rekonstruieren. Dieser Problematik widmet sich ein großer Teil der theoretischen, archäologischen Forschung^[@hofmann_rituelle_2008, 123-128.]. Wie oben ausgeführt sind Handlungen, die mit dem Tod in Verbindung stehen, meist besonders bedeutungsgeladen und deswegen schwer rekonstruierbar.

Die wichtigsten Befundtypen der Thanatoarchäologie sind Gräber -- einzeln oder im Kontext von Gräberfeldern und sonstigen Kollektivgrabanlagen. Schrift- oder ikonographische Quellen, die Aufschluss über das Totenritual oder sogar die zugrundeliegende Vorstellungswelt geben würden, existieren in der prähistorischen Archäologie nicht oder sind äußerst selten. Im Kontext von Gräberfeldern können oft neben den eigentlichen Bestattungseinrichtungen auch Gruben, Steinpflaster, Ustrinen (Verbrennungsplätze, an denen Scheiterhäufen errichtet wurden) und aufgehende Strukturen wie Zäune, Grabmarkierungen oder Ritualaufbauten dokumentiert werden. Selbst im Fall von datierbarer Gleichzeitigkeit müssen jedoch nicht alle Befunde auf einem Gräberfeld mit dem Totenbrauchtum in Verbindung stehen. Umgekehrt haben nicht alle Handlungen eines Bestattungsrituals in räumlicher Nähe zum Bestattungsplatz stattfinden müssen. Auch die Anlage von Gräbern ist nicht obligatorisch: Viele Bestattungsrituale sehen keine Grabarchitektur vor und manche schließen den eigentlichen Leichnam aus der Deponierung aus. Solche Pseudogräber oder Kenotaphe sind schwer von Hortfunden unterscheidbar und werden meist nur über ihre Position auf dem Gräberfeld identifiziert. Siedlungsbestattungen sind in wenigen Kulturzusammenhängen die Regel, treten aber immer wieder auf. Sie erlauben eine besondere Kontextualisierung der Bestattung über die räumliche Verknüpfung zu Siedlungsarealen oder Haushalten^[@hofmann_rituelle_2008, 128-129.].

Menschliche Überreste finden sich auch außerhalb von intentionell angelegten Gräbern -- etwa als Konsequenz unnatürlicher Tode durch Unglücke, Naturkatastrophen oder Gewalt. Auch diese Quellen sind Teil der thanatoarchäologischen Forschung, müssen aber anders interpretiert werden. Aufgrund schlechter Erhaltungssituation durch stärkere taphonomischer Einflüsse sowie Unsicherheiten über das Kulturverhalten vormoderner Menschen ist die Entscheidung, ob ein Leichnam in einem Ritual bewusst niedergelegt oder schlicht zufällig durch Sedimentbedeckung konserviert wurde besonders in der paläolithischen Archäologie oftmals schwer^[@hofmann_rituelle_2008, 145-147.]. 

#### Quellengattung Grab

Neben Siedlungen, Horten und Einzelfunden gehören Gräber zu den Hauptkategorien archäologischer Quellengattungen. Gräber und Depots heben sich von Siedlungen ab, da sie grundsätzlich eine positive Artefaktauswahl einschließen, das heißt, die eingebrachten Objekte wurden intentional in diesem Kontext platziert. Diese Intentionalität gilt auch für den Grabaufbau. Gräber sind also hochgradig bedeutungsgeladene Befunde, die als Überrest der rituellen Handlungen des Totenbrauchtums konserviert werden. Sie bilden religiöse, soziale und politische Strukturen, Werte und Normen einer Gruppe ab -- allerdings stets schematisiert und gegebenefalls bewusst manipuliert. Die Vielzahl an Filtermechanismen, die zwischen der Lebensrealität einer prähistorischen Gesellschaft und dem archäologisch fassbaren Befund wirken, werden bei der Rekonstruktion von Sozialstrukturen oftmals nicht ausreichend reflektiert. Das ist umso mehr relevant, wenn aus den statischen archäologischen Quellen dynamische, chronologische Entwicklungen und Transformationsprozesse abgelesen werden sollen.  

Menschen trafen in der Vorgeschichte immer wieder neu eine Entscheidung für die Position eines Bestattungsplatzes im natur- und kulturgeographischen Raum. Der Entscheidungsprozess erschließt sich aus einer landschaftsarchäologischen Perspektive, die einerseits natürliche Gegebenheiten wie Topographie, Vegetation oder Wassernähe am Bestattungsplatz sowohl absolut als auch in Relation zu damit wahrscheinlich verknüpften Siedlungen betrachtet, als auch die kulturhistorischen Bezüge zu kontemporärer oder vorangegangener menschlichen Aktivität in der Umgebung. Das erfordert eine grundsätzlich mit Unsicherheiten behaftet Rekonstruktion der Landschaft zum Zeitpunkt der Anlage des Bestattungsplatzes. Funktionale Kriterien wie das Meiden von hochwassergefährdeten Flächen oder Arealen mit schwacher Bodendecke mögen zu einer Vorauswahl der Plätze geführt haben. Darüber hinaus sind dem Feld ideologischer Konnotationen keine Grenzen gesetzt. Das kann zum Beispiel zur Beachtung astronomischer Relationen oder einer bewusst erzeugten über- oder unterbetonten Sichtbarkeit der Anlage führen. Ein Bestattungsplatz ist schließlich selbst landschaftsprägend: Grabanlagen können Territorien abgrenzen oder Wege markieren. Die Aufgabe eines Gräberfelds, seine kontinuierliche Nutzung oder die Wiederaufnahme der Nutzung einer alten Anlage, die gegebenenfalls aus einem vorangegangenen, archäologischen Kulturzusammenhang stammt, geschieht oft in einem Prozess, der mit anderen schwerwiegenden Veränderungen in einer Siedlungsgemeinschaft korreliert.

Jenseits der Frage nach der Position des Bestattungsplatzes stellt sich eine weitere nach der inneren Gliederung desselben. Wird ein Areal neu für diesen Zweck erschlossen, ist es zunächst meist ohne Einrichtungen, die als kulturelle Bedeutungsträger fungieren. Erst die Nutzung für Bestattungen führt zu einer langsamen Akkumulation von -- aus archäologischer Perspektive -- Befunden. Architektur wie Grabanlagen oder Ritualstellen können über längere Nutzungszeiträume erneuert, umgebaut oder entfernt werden. Gräber können einzelnen in individuellen Einrichtungen wie Gruben oder Kisten für sich stehen oder durch Konstruktionen wie Grabhügel, Kammern in Megalithbauten oder Einhegungen zu Einheiten zusammengefasst werden. Letztere führen zu einer Gliederung des Bestattungsplatzes in nach verschiedenen, oft unbekannten Kriterien zusammengehörige Grabkomplexe. Auch die Anordnung von Einzelgräbern auf Gräberfeldern ist in der Regel nicht zufällig und wird unter dem Stichwort der Horizontalstratigraphie archäologisch diskutiert: Durch das sukzessive Sterben von Mitgliedern einer Siedlungsgemeinschaft stellt sich aus Sicht der Bestattenden für jeden Toten erneut die Frage der Platzierung in Relation zu den bereits vorhandenen Gräbern. Häufig bilden sich in der Verteilung der Gräber die chronologische Entwicklung des Gräberfelds ab, aber auch andere Kategorien wie biologische und soziale Gruppengliederung, Alters- und Geschlechtsunterschiede sowie Unterschiede im Rang der Verstorbenen in einer vergangenen soziopolitischen Hierarchie können sich hier niederschlagen. Ausdruck dieser Kategorien sind räumliche Verteilungsmuster der Gräber in denen Merkmalsvariation von einem Zentrum aus oder entlang Achse nachvollzogen werden können, merkmalsgleiche Gruppen zu voneinander getrennten Clustern akkumulieren oder Außreißer mit positiv oder negativ herausragenden Eigenschaften getrennt von der Hauptgruppe platziert wurden. Eine weitere Beobachtungsgröße ergibt sich daraus, ob Gräber in andere Gräber eingreifen und diese stören. Das kann bewusst vermieden werden, zufällig in Einzelfällen auftreten oder ein Gräberfeld als Charakteristikum auszeichnen. Auch die Beraubung von Gräbern nach der Beisetzung kann Teil des Bestattungsrituals sein und die innere Gliederung eines Bestattungsplatzes sowie die Grabarchitektur beeinflussen.

Die vorliegende Arbeit konzentriert sich mit den Dichotomien Brandgrab vs. Körpergrab sowie Hügelgrab vs. Flachgrab auf Aspekte von Bestattungsform und Grabbau. Diese Kategorien dürfen als besonders bedeutungsgeladen verstanden werden: Sie sind kulturell deutlich unterschiedlich und ihre Merkmale besitzen meist starken, symbolischen Aussagewert. Auch innerhalb von Kulturzusammenhängen herrscht große Variabilität -- ein möglicher Indikator für die Intensität sozialer Reglementierung des Bestattungsrituals. Das erschwert eine umfassende Klassifizierung, die in der Lage wäre alle Phänomene aufzunehmen. Wesentliche Gliederungsgrößen sind Ein- und Mehrphasigkeit sowie Partielle und Vollständige Bestattung, darüber hinaus ergeben sich aus der Architektur des Grabbaus sowie der Art der Deponierung des Leichnams Unterscheidungskriterien^[Hofmann sammelt einige der wichtigsten Kategorien in einer tabellarischen Aufstellung: @hofmann_rituelle_2008, 152.]. Grabanlagen besitzen in der Regel eine innere, unsichtbare Struktur und einen sichtbaren, oberirdischen Aufbau. Das Innere des Grabes ist oft nur während der Errichtung und im Moment der Beisetzung offen und zugänglich. Es addressiert entsprechend neben dem Toten und angenommener Entitäten der postmortalen Welt vor allem die Bestattenden und eventuelle Zuschauer der Bestattungszeremonie. Der dauerhaft sichtbare Teil des Grabes hat einen potentiell größeren Adressatenkreis und damit oft einen anderen Symbolgehalt. 

Grabformen können Strukturen im sozialen Gefüge der Lebenden widerspiegeln, indem für Verstorbene aus verschiedenen sozialen Gruppen jeweils unterschiedliche Grabformen genutzt oder indem besondere Individuen in von der Norm abweichenden Sondergrabformen beigesetzt werden. In vielen Gesellschaften werden für Führungspersonen und deren Verwandten aufwendigere und auffälligere Gräber errichtet während fremde und soziale Außenseiter gegebenenfalls deutlich einfacher bestattet werden. Kollektivgräber nivillieren demgegenüber soziale Hierarchien: Die archäologische Forschung bringt sie häufig mit einem betonten Gemeinschaftsdenken und egalitären Gesellschaftsformen in Verbindung. Bestattungsform und Grabbau bieten die Möglichkeit, nicht nur Einblicke in die soziale Organisation sondern auch die spirituelle Vorstellungswelt einer archäologischen Kultur zu gewinnen. Zwar sind mit ein und der selben Religion durchaus unterschiedliche Grabriten vereinbar und eine plakative Trennung der Vorstellungen, die zum Beispiel hinter Körper- und Brandbestattungen stehen mögen, ist nicht haltbar. Bestimmte Rituale, wie etwa eine aufwändige Mumifizierung, geben allerdings begründeten Anstoß zur Vermutung, die Unversehrtheit des Körpers spiele in der Jenseitsvorstellung der entsprechenden Kultur eine entscheidende Rolle. In verschiedenen Kulturzusammenhängen erwecken Gräber, die als Totenhäuser gestaltet sind oder hausförmige Urnen enthalten, den Eindruck, die Toten würden in ihren Gräbern wie in Häusern weiterleben. Die systematische Orientierung des Körpers in Relation zu den Himmelsrichtungen tritt auf prähistorischen Gräberfeldern häufig auf und könnte mit einer religiösen Begründung gut erklärt werden. Der Grabbau kann auch durch die Angst vor dem Toten beziehungsweise dessen Eingriffe in die Welt der Lebenden bestimmt sein. Das kann sich dadurch ausdrücken, dass der Leichnam bewusst mit schweren Steinen bedeckt oder gefesselt wird.

Jenseits von Bestattungsform und Grabbau konzentriert sich die archäologische Erforschung von Gräbern vor allem auf die Grabausstattung, also jene Artefakte und Überreste, die bei der Beisetzung intentionell in das Grab eingebracht wurden. Aufgrund taphonomischer Gegebenheiten erhalten sich bestimmte Materialkategorien weniger gut oder besser als andere und sind entsprechend im archäologischen Befund über- oder unterrepräsentiert. Grabbeigaben können und müssen hinsichtlich ihrer Bedeutung nach verschiedenen Kriterien untersucht werden. Bestimmte Objekte wurden nur für den Bestattungskontext hergestellt, andere dem Materialkreislauf der Lebenden bewusst entzogen. Artefakte können Teil des Grabbaus sein, zur persönlichen Ausstattung und Tracht des Verstorbenen gehört haben oder als sonstige Beigaben in den Grabkontext eingebracht worden sein. Letztere können beispielsweise als Gebrauchsgegenstände für den Toten in seiner postmortalen Existenz verstanden werden, als durch den Tod verunreinigt gelten oder zur Selbstdarstellung der Hinterbliebenen im Bestattungsritual präsentiert werden. Aus archäologischer Perspektive ist es oft sehr schwierig, die Motive hinter der Deponierung einer einzelnen Beigabe zu erschließen. Der potentielle Symbolgehalt von Form, Farbe und Verzierung der Artefakte steigert bringt weitere Unsicherheiten mit sich. In der archäologischen Literatur werden beispielsweise immer wieder einzelne Artefakte als Amulette angesprochen. Meist handelt es sich um Einzelstücke ohne erkennbaren, funktionalen Nutzen, die nah am Leichnam platziert wurden. Sie könnten sowohl Funktionen als Glücksbringer für den Toten als auch als Bannmittel zum Schutz der Lebenden übernommen haben. Nahrungsbeigaben sind in rezenten Kulturen oft mit der Vorstellung einer Reise ins Jenseits verknüpft. Der Verstorbene hat auch nach dem Tod noch Bedarf nach physischer Nahrung. Diese Assoziation ist allerdings nicht zwingend: Nahrungsbeigaben können auch schlicht eine weitere Ausdrucksform für die soziale Identität des Toten sein. 

Interpretationsansätze für Grabausstattungen betonen meist den Aussagewert der Beigabensammlung für die Identität des Bestatteten. In der Regel werden Unterschiede in der Qualität und Quantität von Beigaben mit dem vertikalen sozialen Status einer Person oder Gruppe in Verbindung gebracht. Insbesondere Prestigegüter -- auffallende Einzelobjekte aus heute als wertvoll erachteten Materialien -- werden in diesem Kontext betont betrachtet. Beigaben können auch die Zugehörigkeit unter anderem zu einem sozialen Geschlecht, einer Altersgruppe, einem Berufszweig oder einer Herkunftsregion ausdrücken. Zuordnungen dieser Art lassen sich mit physisch-anthropologischen oder naturwissenschaftlichen Daten korrelieren und so gegebenenfalls verifizieren. Allerdings kann sowohl eine Person mehrere Identitäten in sich vereinen als auch ein Artefakt mit mehreren Bedeutungsebenen verknüpft sein. Die Auszeichung von eindeutigen Leit- oder Faziesartefakten kann zwar statistisch relevant, im Einzelfall aber auch irreführend sein und zu Zirkelschlüsse führen^[@hofmann_rituelle_2008, 145-165.].

### Eine Cultural Evolution Perspektive auf Bestattungssitten

Bergensen 1998, 54ff & 63 f.
Grimes 1998, 131 ff.

## Räumliche und zeitliche Trends im Bestattungsritus der Bronzezeit 

In der europäischen Bronzezeit sind mehrere unterschiedliche Bestattungstraditionen unterscheidbar, die zeitlich und räumlich verschiedene Entwicklungen durchlaufen. Dabei können zwei wesentliche Dimensionen abgegrenzt werden, entlang derer sich fast alle dokumentierten Grablegungen kategorisieren lassen: 1. Körperbestattungen im Gegensatz zu Brandbestattungen sowie 2. Flachgräber gegenüber überhügelten Gräbern. In diesem Spektrum gibt es etliche Varianten hinsichtlich der Grabanlage- und Vergesellschaftung (z.B. Nachnutzung neolithischer Megalithanlagen, Gräberfelder, etc.), des Grabbaus (Särge, Totenhäuser, Bootsgräber etc.) der Beigabenauswahl, der Platzierung des Leichnams oder des investierten Aufwands für Bestattungszeremonie und Architektur. Angesichts dieser Variablenvielfalt ist Generalisierung und die Reduktion des Gesamtzusammenhangs auf die Spannungsfelder Körper- vs. Brandbestattung und Flach- vs. Hügelgrab schwierig. Dennoch soll für die vorliegende Arbeit diese Perspektive eingenommen werden, da nur zu diesen primären Variablen Informationen im Radon-B Datensatz (siehe Kapitel \@ref(radonb-dataset)) enthalten sind. Der Datensatz gibt auch das Forschunsareal und die Abgrenzung künstlicher Regionen vor, die als Beobachtungseinheiten dienen (siehe Kapitel \@ref(data-prep-and-segmentation)).

Kurz zusammengefasst besagt das klassische Narrativ der Entwicklung bronzezeitlicher Bestattungssitten folgendes: In der frühen und mittleren Bronzezeit dominieren Körperbestattungen in verschiedenen Variationen. Brandgräber kommen in diesem Zeitfenster nur in der Ungarischen Tiefebene verstärkt vor. Hügelgräber konzentrieren sich auf Teile des Balkans sowie Ost-, West- und Nordeuropa, während in Zentral- und Südeuropa Flachgräber -- mehrheitlich Körperbestattungen -- überwiegen. In der mittleren Bronzezeit gewinnt Überhügelung zumindest in West- und Mitteleuropa an Bedeutung. In der späten Bronzezeit wird Brandbestattung zum häufigsten Bestattungsbrauch^[@harding_european_2000, 75-76. **Eigentlich Häusler 1977/1994/1996 -> ausbauen!**].

### Körperbestattung und Brandbestattung

Nach verbreiter Lehrmeinung sind Brandbestattungen in erster Linie ein Phänomen der Spätbronzezeit. Ein fast universelles Phänomen sind Flachgräberfelder mit einzeln beigesetzen Urnen. Aus dieser Beobachtung heraus wird die Spätbronzezeit in Zentral-, Nord- und Westeuropa auch als *Urnenfelderzeit* bezeichnet. Tatsächlich kommen Brandbestattungen schon erheblich früher vor.

In Ungarn wird die Brandbestattung schon in der Frühbronzezeit von den Nagyrév- und Kisapostag Gruppen und in der Mittelbronzezeit von der Vatya Kultur praktiziert. Auch in Großbritannien treten Brandbestattungen schon früh und über einen langen Zeitraum parallel zu Körperbestattungen auf. In der Mittelbronzezeit wird die Verbrennung dort die dominante Bestattungssitte. Auch in Zentral- Nord und Südwesteuropa treten Kremationen in geringem Anteil lange vor der lokalen Spätbronzezeit auf^[@harding_european_2000, 111.]. 

Grundsätzlich gilt, dass kohärente Bestattungsplätze und Gräberfelder in einer Belegungsperiode jeweils einheitlich eine Bestattungsform praktizieren. Das zeigt sich besonders in der Urnenfelderzeit, wo eine Vielzahl großer und weitreichend untersuchter Gräberfelder in Zentraleuropa, im Mediterranen Raum, in Frankreich und in Skandinavien abgesehen von verschwindend wenigen Ausnahmen exklusiv mit Kremationen belegt sind. Dazu gehören zum Beispiel die Gräberfelder Moravičany (Mähren) mit 1260 oder Vollmarshausen (Hessen) mit 252 erfassten Bestattungen. In der Frühen und Mittleren Bronzezeit ist birituelle Belegung noch erheblich häufiger: Auf dem Tumuluszeitlichen Platz Dolný Peter (Slowakei) verhalten sich Brand- zu Körperbestattungen in einem Verhältnis 5:50, in Streda nad Bodrogom (Slovakei) beträgt das Verhältnis 34:24, wobei weiterhin neun Kenotaphe erfasst wurden. Auf dem größten und archäologisch wichtigsten Gräberfeld der Mittelbronzezeit Zentraleuropas in Pitten (Niederösterreich) dominieren Kremationen mit 147:74. Ebenso gibt es aber auch in der Frühbronzezeit Gräberfelder mit großer Einheitlichkeit wie Gemeinlebarn F (Niederösterreich) wo unter den 258 erfassten Bestattungen nur eine einzige mit einem Verbrennungsritual begesetzt wurde und in der Spätbronzezeit Gräberfelder mit biritueller Belegung wie Przeczyce (Schlesien) mit einem Verhältnis von 132:727^[@harding_european_2000, 112.].

Von besonderem archäologischen Interessen sind eben jene Kontexte, wo verschiedene Rituale in größter räumlicher und -- soweit erfassbar -- zeitlicher Nähe zueinander durchgeführt wurden. Systematische Unterschiede hinsichtlich Beigabenreichtum, Geschlechterschwerpunkt oder horizontalstratigraphischer Aufteilung von Gräberfeldern bei biritueller Belegung... **Mal nachsehen!**. 
Sowohl für das urnenflederzeitliche Vollmarshausen als auch das frühbronzezeitliche Gemeinlebarn F deuten sich eine horizontalstratigraphische Trennung nach Familiengruppen an, deren Nachweis allerdings erst mit genetischen Mitteln erfolgen könnte, die zum Zeitpunkt der Untersuchung noch nicht zur Verfügung standen oder im Falle der Brandbestattungen von Vollmarshausen wahrscheinlich erhaltungsbedingt ausgeschlossen werden müssen^[@harding_european_2000, 114.].

In Kontakt- und Übergangsbereichen der Bestattungssitten kam es an verschiedenen Punkten zu überraschenden Überschneidungen der Ritualausführung. In Periode III der skandinavischen Bronzeit wurde in Dänemark Leichenbrand in Sarg- und Kistengräbern beigesetzt, die zuvor für Körperbestattungen verwendet worden waren. In der Champagnen finden sich Brandbestattungen in Grabgruben, die ausreichend Platz für einen unverbrannten Körper geboten hätten. Für ein aunjetitzerzeitliches Gräberfeld in Jeßnitz (Sachsen-Anhalt) rekonstruieren die Ausgräber ein Ritual, das sekundäre Feuereinwirkung auf schon in Särgen deponierte Körperbestattungen eingeschlossen hätte. **Ausbauen!** ^[@harding_european_2000, 113.] 

### Flachgrab und Hügelgrab

huhu

### Regionaler Überblick {regions-archaeological-overview}

Schwerpunkt auf Grabform (Brandgrab vs. Körpergrab) und Grabkonstruktion. Weitere Aspekte wie Grabbeigaben, Körperhaltung, Geschlechtsdimorphismen, etc. werden nur dann beachtet, wenn sie direkt mit diesen Primäraspekten zusammenhängen.

#### Slovakei und Ungarn

Die Slowakei ist vor allem durch die Gebirgsrücken von Ost- und Westkarpaten geprägt. Im Südosten und Südwesten davon öffnet sich das Land nach Ungarn zum Karpatenbecken mit Kleiner und Großer Ungarischer Tiefebene. Die ausgedehnte, flache Landschaft wird und wurde von den Flüssen Donau und Theiß sowie deren Nebenflüssen dominiert, die das Becken in Nord-Süd-Richtung durchziehen. Vor ihrer Begradigung im 19. Jahrhundert mäandrierten beide stark und ihr Verlauf änderte sich häufig und in kurzen Intervallen. Neben ihrer geomorphologisch prägenden Wirkung stellten sie wichtige Kommunikationswege und kulturelle Grenzen dar: Im Karpatenbecken begneten West- und Mitteleuropa den Steppengebieten, dem Ostbalkan und dem östlichen Mittelmeergebiet. Für die bronzezeitliche kulturgeographie ist es sinnvoll, von West nach Ost in drei Areale zu untergliedern: Der Donauraum (Transdanubien), das Zwischenstromland zwischen Donau und Theiß und die Theißregion. Aufgrund der großen Heterogenität und inneren Komplexität der Entwicklungen in diesen Regionen, wird der Schwerpunkt der folgenden Ausführungen auf dem Westen Ungarns und der Slowakei liegen, also jenen Gebieten, die auch im Untersuchungsareal dieser Arbeit liegen. Die slowakische, bronzezeitliche Chronologie folgt einem modifizierten Schema nach Reinecke, in Ungarn dagegen ist eine an der Tellsiedlung Toszeg erarbeitete Chronologie verbreitet. Eine Aufteilung in Früh-, Mittel-, Spät und Endbronzezeit ist jedoch in beiden Kontexten gebräuchlich und kann Grenzenüberschreitend zur Anwendung gebracht werden^[@markova_slovakia_2013, 813-814.].

Ungarn und die Slowakei waren zu Beginn der Frühbronzezeit, die nach Definition von 2500/2300 bis 1550/1450calBC dauerte, kulturell vielfältg und territorial fragmentiert. Im Laufe dieser Phase fand eine langsame Konsolidierung von Gruppen statt, die mit Bevölkerungswachstum, zunehmender Metallverarbeitung und steigender Siedlungsdichte und -kontinuität einherging. Etliche Siedlungen haben sich als bis heute in der Landschaft sichtbare Tellhügel erhalten. Westlich der Donau entstand am Beginn der Frühbronzezeit aus spätneolithischen Substrat der Makó-Kosihy-Čaka Komplex. In diesem Kontext waren isolierte Brandbestattungen mit oder ohne Urne üblich, später auch gelegentlich Körperbestattungen. Die Region wurde von verschiedenen Phänomenen in angrenzenden Räumen beeinflusst, besonders von der Somogyvár-Vinkovci Kultur aus dem Nord- und Nordwestbalkan. In Süd- und Nordwesttransdanubien waren Körperbestattungen aus dieser Tradition heraus wesentlich häufiger als Urnenbestattungen. Grabhügel und Flachgräber traten nebeneinander auf. Im Süden waren reiche Grabbeigaben üblich, sie werden seltener, sucht man weiter im Norden. Von Westen kommend über Südmähren und die westlichen Ausläufer der Karpatevorland in der Slowakei bis ins Areal des heutigen Budapest trat eine lokale Variante -- die Csepel Gruppe -- der Glockenbecherkultur auf. Im Gegensatz zu zu anderen Glockenbecherkontexten waren Körperbestattungen hier zugunsten von Brandbestattungen eher selten. In der Südwestslowakei siedelten außerdem Vertreter einer Variante der frühen Schnurkeramik -- die Chłopice-Veselé Kultur. Das ist Ausdruck einer weiteren Verbindung nach Mähren und bis nach Kleinpolen. Flache Körpergräber waren die Regel in diesem Kontext. Mit dem Fortschreiten der Frühbronzezeit ab Bz A1 entstand in der Südwestslowakei aus Chłopice-Veselé Kultur, Glockenbecherkultur und Makó-Kosihy-Čaka Kultur die Nitra Kultur. Die übliche Bestattungsform in diesem Zusammenhang waren nun Ost-West-orientierte Körpergräber in Hockerlage. Grabaufbauten wie Totenhäuser geben Indizien über den soziale Rang der Bestatteten. Schon in der Materiellen Kultur des Nitra Kontext finden sich starke Einflüsse aus dem Aunjetitzer Kulturraum und ab dem Ende von Bz A1 ist es angemessen, die Kulturerscheinungen in der Südwestslowakei als lokale Ausprägung der Aunjetitzer Kultur zu beschreiben, obgleich besonders hinsichtlich der Bestattungspraktiken Nitratraditionen fortbestanden. Sozialen Unterschiede in Beigabenmenge und Grabkonstruktion manifestierten sich hier nicht so stark wie im Kernraum der Aunjetitzer Kultur. Auch drang die Aunjetitzer Kultur nicht weiter nach Süden nach Transdanubien vor. Am Übergang von Bz A2 zu Bz B1 entwickelte sie sich stattdessen lokal weiter zur Maďarovce Kultur, der östlichen Ausprägung des österreichischen und mährischen Maďarovce-Věteřov-Böheimkirchen Komplexes. Im Maďarovce Kreis wurden zunächst vor allem flache Körpergräber angelegt, später mehr Hügelbestattungen und Brandgräber. Am Übergang zur Mittelbronzezeit in BZ B1 löste sich das Kulturphänomen langsam auf. Der westliche Zugang zum Karpatenbecken war zeitweise durch die frühbronzezeitlichen Entwicklungen im Nordosten Österreichs geprägt, wo sich mit der Leithaprodersdorf Kultur und der Wieselburg gut abgrenzbare Einheiten ausbreiteten. Weiter südlich in Ungarn wurde die Makó-Kosihy-Čaka Kultur noch in Bz A von der Kisapostag Kultur abgelöst. Hier wurden Brandbestattungen in Urnen oder mit einer Verstreuung des Leichenbrands praktiziert. Körperbestattungen treten zwar auch auf, sind aber selten. Auf die Kisapostag Kultur folgte die Kultur Inkrustierter Keramik (Transdanubian Encrusted Pottery oder North Pannonian culture) mit Brandbestattungen in einfachen Gruben und mit Urnen. Körperbestattungen traten sporadisch auf. Westlich davon, zwischen Donau und Theiß, entstand am Beginn der Bronzezeit in bz A0 un Bz A1 die Nagyrév Kultur. Die übliche Form der Bestattung waren auch in diesem Kontext Brandbestattungen, verstreut oder in Urnen. Körperbestattungen treten nur vereinzelt in der Anfangsphase auf. Vor dem Hintergrund von Nagyrév und Kisapostag Kultur entstand hier im weiteren Verlauf der Frühbronzezeit die Vatya Kultur -- mit einem sehr umfangreichen und fortgeschrittenen Metallinventar. Der Bestattungsritus dieser Gruppe war stark normiert und bestand aus strukturiert auf Gräberfeldern angeordneten Brandbestattungen mit stark differenzierender Beigabenausstattung^[@markova_slovakia_2013, 814-821.].

Die Mittelbronzezeit in der Slowakei und in Ungarn ist eine Vergleichsweise kurze Phase von 1500/1450 bis 1200/1150calBC (Bz B1 bis Bz C). Zur Frage, ob der Beginn des Übergangs von Früh- zu Mittelbronzezeit aus Westen oder Osten angestoßen wurde, herrscht in der Fachdiskussion keine einheitliche Meinung. Als Resultat setzte sich jedoch im gesamten Raum die Grabhügelkultur durch. Ihre lokale Ausprägung -- im Westen Ungarns und der Slowakei die Mitteldonauländische Grabhügelkultur -- war sehr ähnlich zu jener in anderen Teilen Zentraleuropas. Grabhügel fanden in diesem Zeitraum weite Verbreitung, die bisherigen, lokalen Präferenzen für Körper- oder Brandbestattung wurden allerdings beibehalten und mit der Veränderung im Grabaufbau kombiniert. Die Bestattungen zeigen allgemein einen Geschlechtsdimorphismus und konnten auf Erdbodennivau platziert und dann überhügelt, oder in eine Grabgrube unter dem Hügel eingebracht werden. Am Übergang zur Spätbronzezeit, in Bz D, wurde die Grabhügelkultur durch die Urnenfelderkultur -- konkret die Mitteldonauländische Urnenfelderkultur -- abgelöst. Östlich der Donau zeichnete sich die Grabhügelkultur durch größere räumliche und zeitliche Heterogenität aus. Im Norden, in der Slowakei, lässt sich die Entwicklung in der Mittelbronzezeit als Abfolge ausgehend von der Dolný Peter Phase, ein Übergangshorizont zwischen Maďarovce und Grabhügelkultur, und dann der Frühen, Klassischen und Späten Grabhügelkultur beschreiben. Südlich davon gelten die Tápé, die Egyek und die Hajdúbagos Gruppe als Vertreter der Grabhügelkultur im Karpathenbecken. Von Region zu Region unterschiedlich wurden Körper- oder Brandbestattung praktiziert. Auch die Errichtung von Grabhügeln war nicht obligatorisch: Auch Flachgräberfelder treten auf^[@markova_slovakia_2013, 825-827.].

^[@markova_slovakia_2013, 827-833.].

#### Österreich und Tschechische Republik

Die Bronzezeit in Österreich und Tschechien lässt sich in vier wesentliche Perioden gliedern: Früh-, Mittel-, Spät- und Jungbronzezeit. In der Frühbronzezeit entwickelte sich nördlich der Donau in Österreich unter Einfluss der Ungarischen Nagyrév Kultur die Proto-Aunjetitz Kultur parallel zum Aunjetitz Kreis in Böhmen und Mähren. Im Aunjetitz Areal folgen die Bestattungssitten einem relativ festen Regelwerk: Üblich waren Einzel- und Körpergräber. Einzelne Funde von Massengräbern im Siedlungskontext, die sich auch in der Tumulus und und der Urnenfelderkultur fortsetzen, dürfen nicht als reguläre Bestattungskontexte verstanden werden. In Nordbömen, Mähren und den anschließenden Teilen von Österreich dominieren Flachgräber, während in Süd- und Westböhmen Hügelgräber häufiger aufreten. Die Flachgräber gingen den Grabhügeln zeitlich voran und zeichnen sich oft durch eine gemauerte Grabkiste oder einen Holzsarg aus. In mehreren Fällen konnte der Nachweiß für eine hölzerne Konstruktion über dem Flachgrab erbracht werden. Die Bestattungen in den Hügeln sind meist in den Urhumus eingetieft und durch eine Steinpackung geschützt, die damit gleichermaßen den Kern der Hügelaufschüttung bildet. Im Aunjetitzer Kontext dominieren linke Hocker in Süd-Nord Orientierung ohne Geschlechtsdimorphismus. Obgleich eine Mehrzahl der Gräber wahrscheinlich zum Ende der Frühbronzeit beraubt wurden, lässt sich ihr Beigabeninventar rekonstruieren: Neben Gewandelementen und -- in einigen wenigen Kontexten -- Waffen und Prestigegegenstände aus Bronze, Gold und Bernstein überwiegen Keramikgefäße. Dabei lässt sich eine diachrone Entwicklung von größeren zu sehr kleinen, teilweise miniaturisierten Beigabengefäßen beobachten^[@lubos_czech_2013, 789 & 794-796].      

Zeitgleich mit der Aunjetitzer Kultur begegnen sich südlich der Donau in der österreichischen Frühbronzezeit mehrere Lokalgruppen. Die Leithaprodersdorf Gruppe, die noch in der Frühbronzezeit von der Wieselburg Kultur abgelöst wurde, findet sich östlich des Wienerwald. Im Kontext dieser aufeinander folgenden Gruppen sind flache Körperbestattungen üblich. Die Körperhaltung und Orientierung folgt einem klaren Geschlechtsdimorphismus und die Qualität und Quantität der Beigaben ist betont ungleich. Auch hier sind Steinkisten und Baumsärge ein wichtiger Teil der Grabkonstruktion. Südlich von Wien und westlich des Wienerwalds lässt sich die Unterwölbing Kultur verorten. Auch hier sind flache Körperbestattungen die Regel. Die Gräber sind stark standardisiert, zeigen einen deutlichen Geschlechtsdimorphismus und sind als mit gesetzten Steinkisten und Baumstammsärgen aufgebaut. Sie sind meist Teil siedlungsnaher Gräberfelder und vergleichsweise reich mit Keramik sowie Bronzewaffen und -schmuck ausgestattet. Schwere Halsringe sind charakteristisch für diesen Kulturzusammenhang. Im westlichen Teil Niederösterreichs bis nach Tirol findet sich die Straubing Kultur, deren Verbreitungsschwerpunkt in Bayern liegt. Aus Österreich sind trotz ausgeprägter Besiedlung keine Bestattungsplätze der Straubing Kultur bekannt, in Bayern verhält es sich allerdings wie im Unterwölbing Raum. Auch aus den Alpengebieten sind zu wenige Gräber erforscht, um eine zuverlässige Aussage über die vorherrschenden Bestattungsbräuche treffen zu können, jedoch deutet sich für die inneren Alpen ein früher Wandel hin zu Brandbestattungen an^[@lubos_czech_2013, 789 & 796-797].

Am Ende der Frühbronzezeit entstand in Böhmen und Mähren unter starkem Einfluss aus Südosteuropa die Věteřov Kultur. In Österreich wurde die Unterwölbing Kultur durch die Böheimkirchen-Gruppe abgelöst. Im Osten bestand die Wieselburg Kultur parallel zur neue geformten Drassburg Gruppe weiter. Im Salzkammergut konstituierte sich die Attersee Gruppe. Im Laufe der Mittelbronzezeit wurden die lokalen Phänomene im Süden Mährens, fast ganz Böhmen und in Ostösterreich durch die Mitteldonauländische Tumuluskultur homogenisiert. In dieser Konsequenz ist die geradezu universelle Bestattungsform in der Mittelbronzezeit Tschechien und Österreichs das Hügelgrab. Die Hügel sind einfache Erdhügel auf einem Steinkreisfundament. In den Hügeln wurden -- oft mehrere -- sowohl Körper- als auch Brandbestatttungen untergebracht, wobei erstere langsam als dominante Form von letzteren abgelöst werden. Bei Körperbestattungen sind die Beigaben um den Körper verteilt, wobei Keramik entweder am Fuß- oder Kopfende der Grube platziert wurde. Im Kontext der Brandbestattungen wurde die Ausstattung nicht mit verbrannt, sondern vor der Überhügelung auf dem Leichenbrand deponiert. Ein Geschlechtsdimorphismus zeigt sich mitunter nicht nur bei der Beigabenauswahl, sondern auch bei der Grabform: Im Fall der Grabhügelanlage von Pitten in Niederösterreich überwiegt Brandbestattung für weibliche Individuen während Männer überwiegend unverbrannt beigesetzt wurden. Im Westen Österreichs zeichnet sich das Tumulus Phänomen durch mehr Bezüge zu Süddeutschland aus. Im Salzburger Land wurden die Bestattungen als Rückenstrecker in Grabhügeln untergebracht. Brandbestattungen in einfachen, steinbedeckten oder leicht überhügelten Gruben enthalten die Überreste verbrannter Metall- und Keramikartefakte in Urnen aus Keramik oder organischem Material. Die wenigen Funde aus dem inneren Alpengebiet deuten auf beigabenlose Brandbestattungen hin^[@lubos_czech_2013, 790 & 797-798].

In der Spät- und Jungbronzezeit wurden Böhmen, Mähren und Österreich relativ homogen Teil des Urnenfelder Kulturkomplexes. Böhmen ist überwiegend im Einflussgebiet der Urnenfeldergruppen aus dem Oberen Donauraum, Siedlungen der Lausitzer Kultur in Norden und Osten Böhmens lassen sich allerdings besser aus der Perspektive der Nördlichen Urnenfeldergruppen verstehen und im äußersten Westen besteht mit der Cheb Urnenfeldergruppe eine kulturelle Verbindung ins Areal des heutigen Deutschland. Ebenso lassen sich auch Österreich und Mähren in verschiedene kleinere Sphären gliedern, die als verschiedentlich beeinflusste Varianten des Urnenfelderphänomens beschrieben werden können. In all diesen Kontexten folgt die allgemeine Bestattungsform -- mitunter in Nutzungskontinuität der Mittelbronzezeitlichen Bestattungsanlagen -- der stark vereinheitlichen Urnenfelderpraxis: Ausgedehnte Felder von flachen Brandgräbern. In einer Mehrzahl der Fälle ist der Leichenbrand in einer Keramikurne eingelagert, wobei in einer Grabgrube durchaus mehrere Urnen oder sonstige beigefügte Gefäße deponiert sein können. Urnen können neben menschlichen Überresten auch verbrannte Tierknochen und Bronzeartefakte enthalten. Die persönliche Tracht und Schmuck wie Nadeln oder Armreife wurde in der Regel mit verbrannt, während Gebrauchsgegenstände wie Messer erst nach der Verbrennung beigefügt wurden. Trotz der insgesamt großen Homogenität der Urnenfelderkulturen hinsichtlich ihres Bestattungsbrauches zeigen die kulturellen Subgruppen im Detail durchaus Abweichungen voneinander hinsichtlich der Anordnung von Urne und Beigaben im Grab und der Beigabenauswahl, die auf weiterreichende Unterschiede in Ideologie und Sozialstruktur schließen lassen. Zudem wurden in verschiedenen Regionen weiterhin vereinzelt Körpergräber angelegt oder Bestattungen in Grabhügel eingebracht. In der Frühen und Mittleren Urnenfelderzeit war die Beisetzung von Urnen und Beigaben in körpergroßen Steinkisten deutlich standardisiert. In der Späten Urnenfelderzeit verlieren Steinsetzungen an Bedeutung. Gleichzeitig nimmt die Beigabenmenge ab -- insbesondere Waffen werden nicht mehr beigegeben. In den inneren Alpenregionen setzen sich Urnenfelder bis weit in die Frühe Eisenzeit fort^[@lubos_czech_2013, 790 & 798].

#### Polen

Polen kann entlang seiner Nord-Süd Achse naturräumlich in drei Bereiche gegliedert werden: Ein 400-500km breiter Streifen flachen, seen- und feuchtgebietreichen Landes an der Ostseeküste, südich davon Hochland und das Heiligenkreuz Mittelgebirge, an der Südgrenze ein langer Gebirgszug, der sich von West nach Ost aus Erzgebirge, Sudeten und Karpathen zusammensetzt. Die größten Flüsse Polens sind Oder und Weichsel. Beide erstrecken sich über weite Teile Polens, entwässern in die Ostsee und stellten in der Vorgeschichte wichtige Verkehrswege dar. Aus archäologisch-kulturhistorischer Perspektive hinsichtlich der Bronzezeit zwischen 2300/2200-800calBC bietet sich eine andere Dreiteilung in West-, Nordost und Südost Polen an: Eine westliche Zone (Woiwodschaften Pommern, Kajuwien-Pommern, Westpommern, Großpolen, Lebus, Niederschlesien, Lodsch, Oppeln, Schlesien) war nach Osten durch eine Grenzlinie zwischen Danziger Bucht im Norden und dem Durchbruch zwischen Sudeten und Karpathen, der Mährischen Pforte, im Süden definiert. Der Bereich östlich dieser Linie war wiederrum zweigeteilt in einen nördlichen (Ermland-Masuren, Podlachien, Masowien) und einen südlichen (Lublin, Heiligkreuz, Kleinpolen, Karpatenvorland) Teil, getrennt am Ost-West orientierten Übergangsbereichs von Niederrungs- zu Hochland. Die westliche Zone spielte in der zentraleuropäischen Bronzezeit eine entscheidende Rolle, da sie mehrfach die Rolle der östlichen oder nordöstlichen Grenzregion von wichtigen Kulturphänomenen übernahm. Das betrifft etwa die Aunjetitzer Kultur, die Hügelgräber Kultur und, später, die Hallstattkultur. Die Hochland-Regionen von Südostpolen gehörten weitestgehend zum nördlichen Bezugsbereich der Kulturen des Karpathenbeckens. Nordostpolen wich in seiner Entwicklung deutlich vom Rest Polens ab. Eine Sonderrolle nahm nicht zuletzt wegen des Reichtums an Bernstein auch der Küstenstreifen zwischen Oder- und Weichselmündung ein. Diese Region war traditionell Teil eines Austauschnetzwerks, dass das Baltikum überspannte und bis in die Nordsee reichte^[@czebreszuk_bronze_2013, 767-770.].

Die früheste Phase der polnischen Bronzezeit dauerte von 2300/2200 bis 2000calBC. In West- und Südostpolen ist diese Proto-Bronzezeit mit der Glockenbecher Kultur verknüpft. Kuyavien und Pommern gehörten dabei zu einem Glockenbecher Kreis aus Südskandinavien und Nordostdeutschland, Niederschlesien war aus Böhmen inspiriert, Kleinpolen im Südosten des modernen Polens aus Mähren. Aus diesem Glockenbecher Substrat entstand in Westpolen ab 2300calBC die Aunjetitzer Kultur. Im Südosten Polens formte sich die Mierzanowice Kultur. Die zunächst enge Verbindung zwischen beiden Phänomenen löste sich um 2000calBC auf -- Weichsel und obere Oder wurden zur Kulturgrenze. Während die Aunjetitzer Kultur hinsichtlich ihrer materiellen Kultur ein klares Profil ausbildete, hochentwickelte Metallverarbeitung hervorbrachte und an herausragenden Grabhügeln erkennbare, soziale Differenzierung katalysierte, stagnierte und zerfaserte die Mierzanowice Kultur in Lokalgruppen. Nordostpolen blieb lange in einer spätneolithischen und wildbeuterischen Tradition verhaftet, obgleich Keramikfunde Verbindungen nach Westpolen nahelegen. Nach 2000calBC begann sich in Kuyawien und Großpolen mit der Trzciniec Kultur eine neue Größe herauszubilden, die große Teile Nordostpolens und -- um 1650/1600calBC -- auch Kleinpolens erfasste^[@czebreszuk_bronze_2013, 770-772.].

Die frühe Bronzezeit in Polen war von Körpergräbern in sehr großen Hügelgräbern auf Geländeerhebungen und Hügelgräberfeldern mit bis zu 60 einzelnen Hügeln dominiert. Flachgräber waren in dieser Zeit erheblich seltener. Erst am Übergang zur Lausitzer Kultur ab der Mittel- und Spätbronzezeit setzen diese sich durch. Im Südosten Polens, im Kontext der Mierzanowice Kultur, wurden die Toten in West-Ost Orientierung und nach Süden blickend angehockt auf die Seite gelegt. Frauen wurden mit dem Kopf nach Osten, Männer mit dem Kopf nach Westen bestattet. Im Südwesten drückte sich das Geschlecht nicht so offensichtlich in der Bestattungspraxis aus: Die Körper sind Nord-Süd orientiert, der Kopf im Süden, angehockt, das Gesicht nach Osten gerichtet. Im Nordwesten, und damit im Aunjetitzer Kulturkreis, scheint das Recht auf Bestattung einer sozialen Elite vorbehalten zu sein, die in großen Grabhügeln beigesetzt wurde. Aus diesem Kontext sind entsprechend erheblich weniger Bestattungen bekannt, es deutet sich aber an, dass die Leichname üblicherweise Ost-West orientiert, mit dem Kopf nach Westen und mit Blick nach Süden angeordnet wurden^[@dabrowski_aeltere_2004, 73 & 80-81.; @czebreszuk_bronze_2013, 775.].

Hügelgräber der Frühbronzezeit sind aus fast ganz Polen bekannt, sie fehlen nur Nordostpolen (Masowien und Podlasien). Ihr Durchmesser beträgt heute 10 bis 26m, wobei dieser Wert angesichts Jahrhunderte währender Erosion und landwirtschaftlicher Landnutzung nach unten korrigiert werden muss: die Mehrzahl der erhaltenen Hügel ist heute meist nicht mehr als einen Meter hoch. Manche Hügel sind von einem breiten, mehrschichtigen Steinkranz eingefasst, der darauf hindeutet, dass sie ursprünglich von einer nunmehr zerstörten Steinschicht bedeckt waren. Die notwendige Erde wurde aus der unmittelbaren Umfassung der Aufschüttunge entnommen, wodurch teilweise bis heute sichtbare Gräben rund um die Hügel eingetieft wurden. In der Hügelaufschüttung finden sich häufig ein reiches Artefaktinventar sowie Holz- und Steinkonstruktionen. Drei Hauptbauarten lassen sich unterscheiden: Einfache Erdhügel mit 1 bis 2 Körper- oder Brandbestattungen, die in den Urhumus eingegraben oder schlicht darauf gelegt und anschließend überhügelt wurden, Erdhügel mit einer ausgeprägten Brandschicht, die auch verbrannte Knochen und Inventar enthält sowie Hügelgräber mit Steinschutzkonstruktionen. Die Konstruktionen varieren deutlich zwischen gemauerten Grabkammern mit den Überresten mehrerer Körperbestattungen, Steinpflastern und Ringen am Boden der Hügel oder ovalen, kreisförmigen oder rechteckigen Steinabdeckungen, die ein oder mehrere Brand- oder Körpergräber im Hügelvolumen bedecken. In mehreren Grabkammern deutet eine chaotische Lage von Knochen und die Anhäufung von Schädeln auf Mehrfachbeisetzungen und ein komplexes Totenritual hin^[@dabrowski_aeltere_2004, 73-77.].

Flachgräber traten in der Frühbronzezeit ebenfalls in ganz Polen auf. In Zentral- und Nordostpolen (Masowien, Podlachien, Lodsch) waren sie jedoch die ausdrücklich vorherrschende Bestattungsform. Sie wurden überwiegend als Körper-, jedoch auch als Brandgräber ausgeführt. Die Körperbestattungen wurden teilweise in Särgen abgelegt oder in Leichentücher eingeschlagen. Auffallend sind Einzel- und Mehrfachbestattungen, die sowohl Körper- als auch Brandgräber oder sogar Mischformen mit teilweise angebrannten Skeletten enthalten. In Brandgräbern wurde der Leichenbrand entweder mit oder ohne Urne, manchmal in Särgen und sporadisch in anatomischer Lage deponiert. Die urnenlosen, flachen Brandgräber stimmen manchmal hinsichtlich Ausmaßen und Orientierung mit den Körpergräbern überein. In großen Brandgräbern wurden in mehreren Fällen viele -- in einem Fall bis zu 18 -- Individuen untergebracht. Wie bei Hügelgräbern treten auch bei Flachgräbern Steinkonstruktionen in Form von Kisten und Pflastern auf, wobei gelegentlich der Eindruck entsteht, die Steinsetzungen seien bewusst im Sinne eins Musters oder Symbols ausgelegt worden^[@dabrowski_aeltere_2004, 77-80.].

Der Übergang zur Mittelbronzezeit war in Polen durch neue Einflüsse aus der Nordischen Bronzezeit ab 1700calBC im Nordwesten und der Hügelgräber Kultur nach 1600calBC im Südwesten und Südosten geprägt. Trotz der Unterschiede zwischen diesen Kontexten scheinen sie doch einer gemeinsamen kulturellen Sphäre zuzugehören. In beiden waren Hügelgräber -- oft Steinhügel -- und Metallhorte wichtige Kulturphänomene. Ostpolen war weiterhin von Vertretern der in sich heterogenen Trzciniec Kultur besiedelt. Manche Bestattungsplätze waren auch über die Transformation von Mittel zu Spätbronzezeit hinweg kontinuierlich belegt -- in ältere Grabhügel wurden häufig Nachbestattungen eingebracht. Hügel- und Flachgräber weisen insgesamt weitreichende, strukturelle Ähnlichkeiten auf und konnten beide als Einzel- oder Kollektivgräber ausgeführt sein. In Fortsetzung der Traditionen aus Schnurkeramik und Mierzanowice Kultur wurde auch hier vor allem in Hügelgräbern bestattet, daneben bestand allerdings eine Vielfalt unterschiedlicher Phänomene, die die Heterogenität dieses Kulturraumes widerspiegeln^[@dabrowski_aeltere_2004, 73 & 80-81.; @czebreszuk_bronze_2013, 772 & 775.].

Die Spätbronzezeit in Polen war von der Lausitzer Kultur und deren Expansion dominiert. Die Lausitzer Kultur ist die nordöstliche Ausprägung der Urnenfelder Kultur. Sie lässt sich nach 1400calBC in Schlesien und Großpolen erstmals archäologisch fassen und brachte langanhaltende Stabilierung der Siedlungsaktivitäten in großen Teilen Polens mit sich. Sie dauerte bis 400calBC, ab 800calBC freilich stark von der Hallstatt Kultur beeinflusst. Kleinpolen geriet ab 1300calBC in den Einfluss der Lausitzer Kultur, dabei scheint Migration von Siedlern aus Schlesien eine wichtige Rolle gespielt zu haben. Nordostpolen beschritt auch hier einen Sonderweg: Die Veränderung durch die Lausitzer Kultur ist schwieriger fassbar. Die übliche Bestattungsform in der Spätbronzezeit ist auch in Polen damit die Brandbestattung in Urnen auf großen Gräberfeldern. Im Einzugsgebiet des San in Südostpolen trat die Tarnobrzeg Gruppe auf, die unter Einflüssen aus Steppenraum und Karpathenbecken, eine distinkte kulturelle Sphäre bildete^[@czebreszuk_bronze_2013, 772-773 & 775-776.].

#### Süddeutschland

Die kulturhistorische Entwicklung Deutschlands in der Bronzezeit ist komplex und erlaubt die Unterscheidung etlicher Gruppen, Stile und Kulturkomplexe. Wesentlich zum Verständnis sind seine geographische Gliederung und intensive Interdependenzen mit angrenzenden Phänomenen, die sich als Ergebnis seiner Lage in Zentraleuropa zu allen Himmelsrichtungen ergeben. Geomorphologisch kann Deutschland von Süd nach Nord grob in Folgende Regionen untergliedert werden: Die (Bayrischen) Alpen und zugehörige Vorgebirgszonen, die süddeutsche Schichtstufenlandschaft, die Mittelgebirge und schließlich das norddeutsche Flachland mit Küsten und Inseln in Nord- und Ostsee. Die großen Flusssysteme von Donau, Rhein, Weser, Elbe und Oder stellen wichtige Kommunikationskanäle dar, die sich im Verlauf der gesamten Vorgeschichte als Verbindungen und Grenzen in verschiedenen Austauschsystemen verhalten haben. Süddeutschland stand nach Osten in unmittelbarem Kontakt zu Regionen in den heutigen Grenzen von Böhmen, Mähren, Österreich und Ungarn. Nach Süden bestand Kontakt mit den Alpenregionen der heutigen Schweiz und Norditaliens, nach Osten mit Frankreich. Die Entwicklungen in Norddeutschland lassen sich am besten über seine Verbindungen zum Benelux Raum und der Nordischen Bronzezeit in Dänemark und Südschweden verstehen. Ostdeutschland bildete mit Polen eine Sphäre intensiver Interaktion. Das gebräuchliche chronologische System im Süden und bis in zu den Mittelgebirgen ist die für ganz Zentraleuropa relevante Phasengliederung nach Reinecke (s.o.), während in Norddeutschland die Periodenunterteilung der Nordischen Bronzezeit nach Montelius (s.u.) zur Anwendung kommt. Eine übergeordnete Dreigliederung in früh, mittel und spät ergibt sich aus einer vereinfachten Betrachtung der Bestattungssitten: Frühbronzezeit meint einen Zeitraum vom Ende des 3. Jahrtausends bis 1600calBC in dem flache Hockergräber überwiegen, Mittelbronzezeit das Fenter 1600-1300calBC mit Körperbestattungen in Grabhügeln und Spätbronzezeit, die Urnenfelderzeit, den Zeitraum 1300-800calBC^[@jockenhovel_germany_2013, 723-725.].

Für die folgende Zusammenstellung habe ich mich entsprechend meiner Regionengliederung entschieden, Deutschland zweigeteilt zu betrachten. Als gedankliche Grenzlinie dient der Main. Süddeutschland meint damit vor allem das Areal in den heutigen Grenzen von Bayern und Baden-Württemberg. 

In der Frühbronzezeit existierten mehrere lokal begrenzte Kultureinheiten in Süddeutschland, die als Inseln in einer meist noch spätneolithischen Umgebung entstanden. Im Süden und Südosten von Bayern fand sich die Straubing-Gruppe, deren Verbreitungsgebiet sich auch nach Österreich fortsetzte (s.o.). Westlich grenzte sie an die Ries Gruppe an. Ausgehend vom Oberrhein fanden sich in Baden-Württemberg, jeweils nördlich anneinander anschließend, die Singen Gruppe, die Hochrhein-Oberrhein Gruppe, die Neckar Gruppe und schließlich die Adlerberg Gruppe am nördlichen Oberrhein und der Untermainebene. Die übliche Bestattungsform in diesen Kontexten waren Flachgräberfelder mit angehockten Körperbestattungen. Die Orientierung der Toten ist geschlechtsabhängig und folgte der Glockenbechertradition. Manche Gräber sind mit einem Holzsarg oder einer abdeckenden Steinpackung ausgebaut. Metallbeigaben sind selten und weitestgehend auf Kupferzierrat, Nadeln und Dolchklingen beschränkt. Knochen und Muschelschmuck wurden dagegen oft beigegeben^[@jockenhovel_germany_2013, 726-727.].  

Die Mittelbronzezeit war in Zentraleuropa eine Phase nachhaltiger Innovation. Schwerter und Speere kamen auf und verbreiteten sich schnell. Zweischneidige Rasierklingen, Pinzetten, Messer und Sicheln erweiterten das Metallwerkzeuginventar. Pferd und Wagen gewannen als Transportmittel wesentlich an Bedeutung. In der Mittelbronzezeit entstand und dominierte besonders in Süddeutschland, aber darüber hinaus in ganz Zentraleuropa, die Tumulus- oder Hügelgräberkultur. Der Übergangsprozess dahin lief regional unterschiedlich ab, letztendlich erfasste das Phänomen jedoch einen bemerkenswert großen Raum. Die rund-ovalen Hügel wurden aus Erde, Sand, Grassoden, Steinen oder einer Kombination dieser Materialen errichtet. Je nach lokaler Verfügbarkeit von Baumaterialien unterscheidet sich auch ihre Architektur. Die Hügel waren oft von einer Steinsetzung, einem Graben oder -- besonders in Westfalen und den Niederlanden -- Pfostensetzungen eingehegt. Sie kommen in der Regel nicht einzeln vor, sondern clustern in kleineren bis sehr großen Gruppen, die gemeinsam ein landschaftsprägendens Gräberfeld mit oft dutzenden Hügeln bilden. Jeder Hügel gehörte einer kleinen Familiengruppe, wobei die Anlage ursprünglich meist über einer Zentralbestattung angelegt wurde. Spätere Bestattungen wurden in den vorhanden Hügel eingetieft und liegen deswegen meist höher als das Ursprungsgrab. Zwischen den Hügeln einer Gruppe wurden gelegentlich Flachgräber angelegt. Die Bestattungen wurden zunächst meist als Körpergräber ausgeführt, der Anteil von Brandgräbern nahm im Laufe der Mittelbronzezeit jedoch immer mehr zu. In der Regel wurde der Leichnam ausgestreckt in Nord-Süd- oder Ost-West-Orientierung deponiert und die Grabgrube mit Steinsetzungen oder Holzplanken ausgebaut. Die Ausstattung der Toten ist geschlechtsabhängig und scheint die persönlich Ausstattung im Leben widerzuspiegeln: Männer wurden mit Waffen wie Schwert, Dolch, Axt oder Lanzenspitze sowie Schmuck in Form von Nadeln oder Armreifen versehen, Frauen mit einer reichen Auswahl von Trachtbestandteilen. Bernsteinperlen aus dem Baltikum erfreuten sich großer Beliebtheit in Süddeutschland: In Württemberg und Südbayern enthält der archäologische Befund einzelne Gräber und Horte mit tausenden Perlen. Die Zusammenstellung des Grabbeigabeninventars ist das wesentliche Merkmal nach dem Lokalgruppen der Süddeutschen Mittelbronzezeit wie unter anderem die Alb Gruppe, die Hagenau Gruppe oder die Rhein-Main Gruppe definiert werden^[@jockenhovel_germany_2013, 727-730.].   

Auch in Süddeutschland war die Brandbestattung die wesentliche Bestattungsform der Spätbronzezeit. Die Deponierung des Leichenbrands in einer Urne war ab 1100calBC (Ha A2) die universelle Praxis. Die Urnen wurden zusammen mit anderen Keramikgefäßen -- manchmal Teile eines zusammengehörigen Services -- in einfache oder mit einer Steinkiste ausgebaute Grabgruben gelegt. Mit der Einführung der Brandbestattung ging die Aufgabe des Hügelbaus einher. Vereinzelt wurden jedoch noch weiter Körpergräber angelegt, die mit einer reichen Beigabenausstattung die Traditionen der Hügelgräberzeit fortführen. Obgleich die Spätbronzezeit in Süddeutschland mit größerer kultureller Standardisierung als die Mittelbronzezeit assoziiert werden kann ist sie doch bei weitem kein völlig einheitliches oder homogenes Phänomen. Sie lässt sich ausgehend von Bz D bis Ha B2/3 in mindestens fünf Phasen gliedern und reicht bis in die Eisenzeit hinein. Zwar sind viele Metallartefaktkategorien weit verbreitet, Schmuck -- besonders Fibeln -- und Keramik zeigen dagegen starke regionale Variabilität. In Süddeutschland kann die südliche Bayrische Gruppe im Alpenvorland, die Fränkisch-Pfälzische Gruppe in Ostbayern und weiter westlich die Untermainisch-Schwäbische Gruppe unterschieden werden. Auch innerhalb des Urnenfelderbestattungsrituals gibt es Varianten, die sich vor allem durch die Beigabenmenge und Auswahl ausdrücken: Die Mehrzahl der Gräber enthält nur Keramik, manche daneben auch einige wenige Nadeln und Schmuckgegenstände, reichere dann Messer, Rasierklingen und einfache Waffen wie ein Bogen mit Pfeilen. Die herausragend reichen Bestattungen sind mit größeren Waffen wie Schwertern und Speerspitzen, sowie bronzenem Drinkgeschirr, Wagenteilen und hochwertigem Bronze- und Goldschmuck ausgestattet. In Südwestdeutschland sind sie häufig mit einer nord-süd orientierten Kammer aus Holz oder Stein ausgebaut. Diese Gräber gehören meist zu erwachsenen Männern, denen seitens der Archäologischen Forschungstradition eine Führungsposition in ihrer lokalen Gruppe zugesprochen wird. Manche sind als Körperbestattungen ausgeführt und enthalten außergewöhnliche Beigaben wie Zeremonialwägen, Rohmetall und Bronzegewichte. Frauengräber dieser Art sind selten, gelegentlich treten jedoch Gräber auf, in denen die sowohl Überreste eines Mannes als auch einer Frau beigesetzt sind. Frauengräber sind mit Schmuck und Trachtbestandteilen ausgestattet und allgemein beigabenärmer als Männergräber. Geschlecht und Alter korrelieren grundsätzlich mit der Größe von Grab und Urne. Kindergräber sind üblicherweises mit einer feminin assoziierten Beigabenauswahl versehen^[@jockenhovel_germany_2013, 730-733.].

[@falkenstein_development_2012; @falkenstein_zum_2017]

#### Norddeutschland

Norddeutschland dient hier als vereinfachter Begriff in Abgrenzung zu Süddeutschland und umfasst eigentlich Nord-, Ost- und Mitteldeutschland. Diese Großregionen sind Teil unterschiedlicher Einflusssphären (s.o.) und durchlaufen in der Bronzezeit unterschiedliche kulturelle Entwicklungen. Norddeutschland (im Schwerpunkt Schleswig-Holstein, Niedersachsen und Mecklenburg-Vorpommern) wird stark aus Skandinavien (s.u.), Ostdeutschland (im Schwerpunkt Sachsen, Sachsen-Anhalt und Brandenburg) von Polen (s.o.) und Mitteldeutschland (im Schwerpunkt Saarland, Rheinland-Pfalz, Nordrhein-Westfalen, Hessen, Thüringen) aus dem Süden (s.o.) und Westen (s.u.) beeinflusst. Norddeutschland lässt sich damit als Teil der Nordischen Bronzezeit beschreiben und Ostdeutschland ist Teil der beiden großen, aufeinander folgenden Kreise Aunjetitzer sowie Lausitzer Kultur. Mittel- und Westdeutschland gehören in vielerlei Hinsicht zur süddeutschen Sphäre und durchlaufen entsprechend eine dazu ähnliche Entwicklung. 

##### Norddeutschland

Aus dem Substrat der spätneolithischen Einzelgrabkultur entstand in Norddeutschland, Südskandinavien und im Westbaltikum zwischen 2200 und 1600calBC die Nordische Frühbronzezeit. In vielerlei Hinsicht setzte sie neolithische Traditionen fort -- offensichtlich beispielweise an der weiten Verbreitung von hochwertigen Feuersteindolchen. Erste Metallgegenstände gelangten aus Zentral- und Westeuropa nach Norden, besonders aus dem unmittelbar angrenzenden Aunjetitzer Raum. Eine eigene Metallverarbeitung emanzipierte sich schnell und eindrucksvoll, wobei im Norddeutschen Raum Einflüsse aus Süddeutschland und der Schweiz sichtbar bleiben^[@jockenhovel_germany_2013, 735.]. 

Zur Mittelbronzezeit, nach 1600calBC, etablierte sich in Norddeutschland die Sögel-Wohlde Kultur, deren Verbreitungsgebiet sich vom Osten der Niederlande über Westphalen bis nach Jütland erstreckte. Sie zeichnet sich durch Körpergräber in Grabhügeln aus. Im Gegensatz zur Situation in der zeitgleich südlich davon vorherrschenden Hügelgräberkultur wurden allerdings nur Männer mit diese Bestattungsform bedacht. Die Beigabenauswahl umfasst Kurzschwerter, Dolche, Randleistenbeile, Pfeilspitzen, Nadeln und gelegentlich kleine, goldene Spiralringe. Die Sögel-Wohlde Kultur ging nördlich der Elbe und im heutigen Schleswig-Holstein in Montelius Perioden II bis III (1450-1250calBC und 1250-1100calBC) in eine vielfältige und dynamische Kulturlandschaft über. In diesem Kontext wurden große Grabhügel mit Steinkistengräbern errichtet, die noch heute Landschaftsprägend wirken. Wie in Zentraleuropa enthalten sie mehrere Gräber, wobei häufig ein Mann und eine Frau zusammen oder nacheinander in eine Grabkammer eingebracht wurden. Ein klassische Deutung versteht die Hügel jeweils als Familiengrabstätte eines einzelnen Hofes in einer weitestgehend egalitären Gesellschaft. Anhand typischer Waffenkombinationen lassen sich Lokalgruppen wie die Westholstein Gruppe (Schwert + Speerspitze), die Segeberg Gruppe (Schwert + Absatzbeil) und die Westmecklenburg Gruppe (Schwert + Absatzbeil + Dolch) unterscheiden. Unter den Grabhügeln fallen einzelne als sogenannte Trachthügel durch eine besonders reiche Ausstattung -- z.B. mit gegossenen Bronzegefäßen -- und gute Erhaltungssituation auf^[@jockenhovel_germany_2013, 735-736.]. 

Im Laufe von Montelius Periode III wurde die Körperbestattung in Norddeutschland langsam zugunsten der Brandbestattung aufgegeben -- ab Periode IV war letztere die absolute Regel. Zeitlich korrelierte der Übergang mit Importen von Bronzegefäßen und Kesselwägen aus dem Böhmischen und Mährischen Raum. Diese Artefakte sind verknüpft mit dem andersartigen und sicher religiös aufgeladenen Urnenfelder-Symbolinventar, was eine kausale Verbindung der Phänomene nahelegt und Hinweise auf den Ursprung des Urnenfelderphänomens gibt. Die Norddeutschen Urnenfelder können wie ihre Süddeutschen Pendants mehrere hundert Urnengräber umfassen, wurden oft um ältere Grabanlagen herum angelegt und bis in die frühe Eisenzeit genutzt. Das Beigabeninventar ist klein und reduziert auf Kleinwerkzeuge und Hygieneausstattung wie Rasiermesser, Pinzetten oder Nadeln. Größere Objekte wie Schwerter treten in einigen Fällen in Miniaturform auf. Oft wurden Bronzegegenstände in Horten -- Totenschätzen -- außerhalb der Gräber deponiert. Unter den Urnen fallen Sonderformen wie Haus- oder Gesichtsurnen auf^[@jockenhovel_germany_2013, 736-737.].

Die Nordische Spätbronzezeit, also nach üblichem Gebrauch Montelius Perioden IV bis VI, begann mit einer langen Phase der Konsolidierung. Sie wirkte nun stärker nach außen -- Artefakte der nordischen Bronzezeit wie Plattenfibeln oder einschneidige, mit Bootsymbolik verzierte Rasiermesser tauchen in Gräbern in Niedersachsen und Holland bis in die Niederrhein Region und Pommern auf. In Periode V wurden vereinzelt große und reich ausgestattete Brandgräber angelegt -- sogenannte *Königsgräber*. Auch in Periode VI wurde in Urnengräbern bestattet. Sie leitet über zur eisenzeitlichen Jastorf Kultur^[@jockenhovel_germany_2013, 737-738.].     

##### Ostdeutschland

In Ost- und Mitteldeutschland, aber auch weit darüber hinaus über Schlesien, Großpolen, Böhmen, Mähren, der Südwestslowakei und dem nördliche Teil Niederösterreich hinweg, siedelten in der Frühbronzezeit in einem Zeitfenster von 2300/2200 bis 1600/1500calBC Vertreter des Aunjetitzer Kulturkomplexes. Die Wurzeln der Aunjetitzer Kultur -- die Proto-Aunjetitzer Phase -- liegen im ausgehenden Spätneolithikum und greifen Elemente von Schnurkeramik und Glockenbecher Kultur auf. Der übliche Bestattungsmodus in der Aunjetitzer Kultur waren Flachgräber mit angehockten Körperbestattungen. Sowohl Männer als auch Frauen sind Nord-Süd orientiert mit Blick nach Osten. Mehrheitlich sind die Gräber einfache Gruben, gelegentlich wurden sie allerdings auch mit einer Steinkiste oder einem Baumstammsarg ausgebaut. Manchmal sind in einer Grabgrube mehrere Tote beigesetzt. Auffällig sind einige Fälle von Kinderbestattungen in großen Vorratsgefäßen. In der fortgeschrittenen Aunjetitzer Kultur, etwa ab dem Übergang zum 2. Jahrtausend, wurden einfache und kleine Kupfergegenstände zur häufigsten Beigabenkategorie. Die Beigabenmenge und -vielfalt ist insgesamt gering, sieht man von den wenigen, sehr reich ausgestatteten, großen und weithin sichtbaren Grabhügeln der Leubingen Gruppe am Dreiländereck Sachsen, Sachsenanhalt und Thüringen ab, die traditionell als *Fürstengräber* bezeichnet werden. Sie enthalten nur eine einzige, fast immer männliche Bestattung aber ein breites und hochqualitatives Beigabeninventar inkluvsive signifikanter Mengen Goldschmuck. Diese außergewöhnlichen Bestattungen sind in der Aunjetitzer Kultur fast ohne Vergleich. Sie weisen auf eine lokal begrenzte aber ausgeprägte soziale Differenzierung hin, die sich vielleicht durch eine Beherrschung von Handelswegen zwischen Donau und Baltikum, Salzgewinnung oder Kupfererzabbau im Harzvorland erklären lassen könnte. Für letzteren existiert allerdings kein archäologischer Nachweis. Vom Ende der Aunjetitzer Kultur am Beginn der Mittelbronzezeit sind fast keine Bestattungsbefunde bekannt^[@jockenhovel_germany_2013, 725-726.]. 

Ostdeutschland gehörte in der Mittelbronzezeit zum Verbreitungsgebiet der in ganz Ostmitteleuropa von Deutschland über Polen, Böhmen, Mähren und bis in die Slovakei dominanten Lausitzer Kultur. Sie entstand aus einem Substrat aus Aunjetitzer Kultur und verschiedenen Lokalgruppen, die bis ins 2. Jahrtausend an einer spätneolithischen Tradition festgehalten hatten. Die Lausitzer Kultur selbst ist kein homogenes Kulturphänomen -- in ihr lassen sich Keramikphasen (Prä-Lausitz Phase I: Bz B-C, Phase II Bz C-D, Phase III Bz D-Ha A1, Phase IV Ha A2-Ha C1) und deutlich distinkte, regionale Gruppen unterscheiden. Die Prä-Lausitz Gruppe in Ostdeutschland, Schlesien und Großpolen war zunächst stark von der frühen, zentraleuropäischen Urnenfelderkultur geprägt, löste sich davon aber zu Beginn der Spätbronzezeit. Das große Verbreitungsareal dieser Westlichen Lausitzer Gruppe reicht bis weit nach Mitteldeutschland hinein und umfasst die Flusssysteme von Oder, Elbe und Weichsel. Sie lässt sich in mehrere Subgruppen wie etwa die Saalemündungsgruppe, die Unstrut Gruppe oder die Elb-Havel Gruppe gliedern. Die übliche Bestattungsform der Lausitzer Kultur war die Brandbestattung in Urnen. Die Gräberfelder wurden über viele Generationen hinweg genutzt und fallen mit oft mehreren tausende Begräbnissen sehr groß aus. Die Grabbeigaben bestehen fast ausschließlich aus Gefäßkeramik, davon jedoch große Mengen. Metallobjekte sind selten und auf kleine Gegenstände wie Nadeln, Schmuck und Gebrauchsgegenstände wie Messer und Rasierklingen beschränkt. Die Beigabenarmut erschwert Schlüsse auf soziale Unterschiede innerhalb der bestattenden Gesellschaft. Besonders in der Elbe-Saale Region kommen vereinzelt Waffengräber vor^[@jockenhovel_germany_2013, 734-735.]. 

##### Mitteldeutschland

Der Raum südlich der Nordischen Bronzezeit, westlich der Aunjetitzer Kultur und nördlich der Rhein-Main-Linie lässt sich in der Frühbronzezeit keinem kohärenten Kulturphänomen zuordnen. Zwischen Niederrhein und Elbe traten verschiedene Varianten der spätneolithischen Riesenbecher Gruppe auf. Ihre Wickelschnurkeramik zeigt Parallelen zur Sögel-Wohlde Kultur der Nordischen Bronzezeit, andere Importe weisen auf Verbindungen nach Süddeutschland, in den Benelux-Raum und nach Großbritannien hin. Verbreitet war die Körperbestattung in Hügelgräbern nach Vorbild der Einzelgrabkultur^[@jockenhovel_germany_2013, 727.].

In der Mittelbronzezeit näherten sich Zentral- und Westdeutschland der süddeutschen Sphäre und damit der Hügelgräberkultur an. Lokalgruppen wie die Fulda-Werra Gruppe, die Thüringer Gruppe, die Oberpfälzische Gruppe und -- nördlich der Mittelgebirge -- die Lüneburger Gruppe gehören zum Kontakt- und Frauentauschnetzwerk der süddeutschen Mittelbronzezeit. Je weiter nördlich, desto stärker ist jedoch auch die Beziehung zu Periode II der Nordischen Bronzezeit. Weiter westlich, an Mittel- und Niederrhein sowie in Westfalen, zerfließen wie schon in der Frühbronzezeit die scharfen Kulturgrenzen. Starke Einflüsse aus den Niederlanden offenbaren sich in der Errichtung von Holzpfostenumfassungen um Grabhügel und der frühen Verbreitung von Brandgräbern^[@jockenhovel_germany_2013, 727-730.].

Auch in der Spätbronzezeit ist Mittel- und Westdeutschland zwischen verschiedenen Einflusssphären aufgeteilt. Westlich des Rhein siedelten Vertreter der Niedermainisch-Schwäbischen Gruppe und östlich des Ober- und Mittelrheins sowie im Moselgebiet und dem Saarland des Rhin-Suisse-France orientale (RSFO) Kulturkomplex. Die Areale östlich davon gehören bereits zur Peripherie der Lausitzer Kultur. Nördlich der Mittelgebirge, zwischen Niederrhein Saale und Elbe, zeigen Keramik und Bronzeartefakte weniger distinkte Unterschiede und erlauben so keine Gruppenuntergliederung. Ab 1000calBC geriet diese Region zunehmend unter den Einfluss der späten Nordischen Bronzezeit (Periode IV und V). Die lokale Spätbronzezeit dauerte bis 600calBC, dann gehörte sie auch zum Verbreitungsgebiet der eisenzeitlichen Jastorf Kultur. Wie in den umgebenden Regionen ist auch in der mitteldeutschen Spätbronzezeit Brandbestattung in Urnen üblich. Die Urnen wurden in alte Grabmonumente wie Hügel oder Langbetten eingebracht oder leicht überhügelten Gruben deponiert. Im Gegensatz zur Entwicklung in Süddeutschland wurden diese Tradition bis in die Eisenzeit fortgesetzt^[@jockenhovel_germany_2013, 730-733.].

#### Nordostfrankreich

Das bronzezeitliche Frankreich lässt sich in drei geographische und kulturelle Regionen gliedern: Die Atlantikküste, die starke Impulse von den Nordseeanrainern, Großbritannien und der Iberischen Halbinsel erfuhr, Südfrankreich, das besonders von den Entwicklungen im Westmediterranen Raum beeinflusst wurde und (Nord)ostfrankreich ausgehend vom Pariser Becken. Die Bronzezeit in Frankreich dauert von 2300calBC bis 800calBC, wobei eine Aufteilung in Frühbronzezeit (2300-1650calBC), Mittelbronzezeit (1650-1350calBC) und Spätbronzezeit (1350-800calBC) üblich ist^[@mordant_bronze_2013, 571.].

In Nordostfrankreich (in etwa die modernen, administrativen Regionen Ile-de-France, Hauts-de-France, Grand-Est und Bourgogne-Franche-Comté) begegnen sich in der Frühbronzezeit eine westliche Einflusssphäre aus der heutigen Normandie und Bretagne, eine noch weiter nordöstlich entlang der Nordsee gelegene Sphäre aus dem heutigen Benelux-Raum und die Rhone Kultur aus dem Süden. Im Nordwesten Frankreichs wurden riesige Grabhügel mit 40-50m Durchmesser und bis zu 5-6m Höhe errichtet. Diese monumentalen Anlagen sind in der Regel nur mit einer einzigen, zentralen Bestattung in einer großen Grabkammer versehen -- meist Männer und nur in selten Fällen Frauen oder Kinder. Zusammen mit den außerordentlich reichen Beigaben (Äxte, Hellebarden, Gold, Silber, Bernstein, Fayence) sind sie Anzeiger für eine deutliche vertikale Gliederung der Gesellschaft mit einzelnen, herausragenden Führungspersonen. Auch in Nordostfrankreich gibt es frühbronzezeitliche Grabhügel, jedoch ist die Erhaltungssituation erheblich schlechter als im Nordwesten. In diesen Hügeln wurden sowohl Brand- als auch Körperbestattungen deponiert. Die Urnen weisen Ähnlichkeiten zu Urnen aus Südengland und Flandern auf. Obgleich die Umfassungen der Hügel Durchmesser von bis zu 100m erreichen konnten, enthalten sie nur wenige oder keine Beigaben. Neben Grabhügeln gab es in Nordostfrankreich zeitgleich auch Brandgräberfelder mit einfachen Urnenbestattungen. Im südlichen Teil, im Einzugsbereich der Rhone Kultur, in Burgund und Franche-Comté, kommen kleinere Grabhügel mit 6-8m Durchmesser und 1m Höhe vor. Daneben wurden Neolithische Megalithikanlagen sowie Höhlen weiter als Kollektivbestattungsplätze genutzt. Ebenfalls in Burgund treten Einzelgräberfelder mit Körperbestattungen in gestreckter und angehockter Lage auf. Insgesamt ist die Beigabenauswahl in diesen Kontexten limitiert aber deutlich geschlechtsspezifisch: Dolche, Äxte und Nadeln für Männer, Schmuck nur für Frauen^[@mordant_bronze_2013, 571-572 & 581.].

In der Mittelbronzezeit, im Kontext einer massiven Zunahme von Quantität und Qualität der Metallverarbeitung und Erfindungen wie dem Absatzbeil und Schwertern, formt sich in Nord- und Westfrankreich eine große, intensiv vernetzte Kulturregion, die auch Flandern und den Süden Großbritanniens einschloss. In Bretagne und Normandie war die Errichtung von herausragenden Individualgrabhügel in Fortsetzung einer Entwicklung, die schon seit der fortgeschrittenen Frühbronzezeit zur Verkleinerung der Hügel geführt hatte, weiter rückläufig und wurde schließlich eingestellt. Darüber hinaus sind die Bestattungspraktiken in diesem Raum weitestgehend ein Desiderat. Im Nordosten wurden die Brandbestattungsfelder weitergeführt, die schon in der Frühbronzezeit in diesem Raum aufgetreten waren. Sie enthalten wenige Beigaben, kein Metall und höchstens ein Keramikgefäß als Urne. Südlich davon, in Ostfrankreich, lässt sich eine starke Expansion der östlichen Tumulus Kultur beobachten, die schließlich bis hinein ins Pariser Becken und ins Loire Tal wirkte. Die übliche Bestattungform in diesem Kulturkreis war das Hügelgrab mit mehreren Beisetzungen. Dabei konnten sowohl Körper- als auch Brandbestattungen eingebracht werden -- letztere gewannen im Laufe der Mittelbronzezeit an Bedeutung. Die Gräber sind reich mit Beigaben versehen und zeigen hier eine klare Differenzierung nach Geschlecht: Männer wurden mit Dolchen, Äxten und Pfeilspitzen, Frauen mit Nadeln, Perlen und Armreifen ausgestattet. Das Ritual weist Bezüge zu den kontemporären Praktiken in Süddeutschland auf^[@mordant_bronze_2013, 572-574 & 581-582.].

Am Übergang zur Spätbronzezeit konsolidierte sich die kulturelle Ost-West Spaltung Frankreichs. Entlang der Atlantikküste ausgehend von der Iderischen Halbinsel bis in den Beneluxraum hinein bestand der schon zuvor etablierte, atlantische Kulturkomplex fort. Auch in Ostfrankreich lassen sich die Entwicklungen vor dem Hintergrund der bereits in der Mittelbronzezeit nachvollziehbaren Prozessen verstehen. In einem großen Areal zwischen und jeweils jenseits von Rhein und Pariser Becken dominierte der Rhin-Suisse-France orientale (RSFO) Kulturkomplex. Wiederrum war die Situation in Nordostfrankreich geprägt von zwei Einflusssphären. Neben traditionelleren Grabformen, wie etwa Körperbestattungen in Steinkisten, wurde in Ostfrankreich im RSFO Raum zunehmend Brandbestattung auf Urnenfeldern praktiziert. Auch im Nordosten war die Brandgrabsitte zunehmend präsent und wurden ab dem 12. Jahrhundert fast universell. Im westlichen Teil hielt sich die Tradition sehr einfacher Brandgräber und karger Beigaben, die schon in der Mittelbronzezeit Verbreitung gefunden hatte. Neben flachen Einzelgräbern wurden für gesellschaftlich herausragende Individuen -- meist Männer -- auch Grabhügel errichtet. Sie sind mit einer Vielzahl von Beigaben versehen, manchmal mit einem Schwert oder Wägeausrüstung. Hügelgräber gewannen in Ostfrankreich zum Ende der Bronzezeit im 9. Jahrhundert wieder an Bewandtnis^[@mordant_bronze_2013, 574-575 & 582-583.].

#### Südskandinavien

Das wichtigste chronologische Instrument der skandinavischen Bronzezeit ist die -- freilich weiterentwickelte -- Periodengliederung nach Oskar Montelius. Der Begriff Frühbronzezeit wird für die Perioden I bis III verwandt, die etwa das Zeitfenster von Reineckes Phasen A2 bis Ha A abdecken. Spätbronzeit umfasst die Perioden IV bis VI, die von Ha B1 bis C reichen. Südskandinavien meint Dänemark sowie die schwedischen Provinzen Scania und Blekinge. Im Vergleich zu nördlicheren Teilen Skandinaviens bieten sich hier naturgeographisch günstigere Bedingungen für Ackerbau, was die Region in der Bronzezeit in die Rolle eines kulturellen Zentrums für Skandinavien versetzt. Im Vergleich zum restlichen Europa fällt die Nordische Bronzezeit vor allem durch ihre außergewöhnlich intensive und stilistisch einzigartige Metallverarbeitung, die Erhaltung vieler tausend Grabhügel und eine auffällige, weit verbreitete Form der Felskunst auf^[@thrane_scandinavia_2013, 746-750.].

Aus der Nordischen Bronzezeit sind viele Gräber erhalten -- besonders aus den Perioden II bis IV --, die es erlauben die Entwicklung der Bestattungssitten gut nachzuzeichnen. Bestattungen in einigen Grabhügeln Zentraljütlands sind unter Feuchtbodenbedingungen erhalten und damit ein hervorragendes archäologisches Archiv. Körperbestattungen (meist) in Grabhügeln waren die Regel, bis in Periode II sporadisch einzelne Brandbestattungen -- ebenfalls meist in Hügel eingebracht -- auftraten. Ab Periode III war die Brandbestattung universell, sieht man von der Situation auf der Insel Gotland ab. Der Übergang zur Bronzezeit in Südskandinavien vollzog sich in verschiedenen Lebensbereichen langsam. Neben dem Hausbau, wo weiter die schon im Neolithikum gebräuchlichen Langhäuser errichtet wurden, und der Flintproduktion, zeigt sich das auch in der Grabanlage, die an alte Tradition anknüpfte. In Dänemark und Südschweden wurden die zu bestattenden Leichname in der Frühbronzezeit in Baumsärgen -- meist ausgehöhlte Eichenstämme -- deponiert. Die Toten wurden gestreckt auf den Rücken gelegt und mit dem Kopf nach Westen orientiert. In Periode III änderte sich das hin zu einer Nord-Süd Orientierung. Oft wurde der Tote innerhalb des Sarges auf eine Ochsenhaut oder eine Wolldecke gebettet. Über manchen Gräbern wurden Totenhäuser errichtet und manche Grabhügel bedecken ein Langhaus. In Periode IV vollzog sich eine Wende hin zu kleineren Grabgruben -- Brandbestattungen brauchen weniger Platz. Große Beigaben wie Schwerter, die zuvor mit den Toten abgelegt worden waren, entfallen damit gleichermaßen. Im Laufe der Perioden IV bis VI wurde der Leichenbrand zunehmend in Urnen deponiert, aber Steinkisten und einfache Erdgruben kommen dennoch parallel weiter vor. Die Beigabenmenge nimmt im Zuge dieser Entwicklung weiter ab: Die meisten Brandbestattungen sind nicht mit Metallartefakten ausgestattet^[@thrane_scandinavia_2013, 754-756.].   

Das herausragendste Merkmal der Bestattungskultur der Nordischen Bronzezeit sind ihre Grabhügel. Aus der Bronzezeit sind schätzungsweise 100.000 Erdhügel erhalten, die meisten in Südskandinavien und aus den Perioden II bis III. Viele sind durch landwirtschaftliche Aktivität gefährdet. In der Größe variieren sie zwischen sehr klein (5m Durchmesser, 0,5m Höhe) und sehr groß (35m Durchmesser, 6m Höhe), wobei sie im mit im Durchschnitt 25m Durchmesser und 2,5m Höhe insgesamt beachtlich ausfallen. Neben diesen Erdhügeln gibt es auch etwa 30.000 Steinhügel, vor allem in den Regionen nördlich von Südskandinavien. Die größten Exemplare in dieser Kategorie messen mehr als 70m im Durchmesser und sind mehr als 10m hoch. Sie gehören damit zu den größten vorgeschichtlichen Bauwerken Europas. In der südskandinavischen Frühbronzezeit wurden Gräber häufig mit einer kleinen Steinpackung überhügelt und auf diesem Steinhügel anschließend ein Erdhügel aus Grassoden aufgebaut. In Dänemark gibt es auch einige spätbronzezeitliche Steinhügel. Während die frühbronzezeitlichen Hügel häufig auf natürlichen Erhebungen und Geländerücken errichtet wurden, finden sich die späteren Hügel tendentiell eher in Niederungslagen. Abgesehen von einigen Sonderformen wie Langbetten, Hügeln mit einer zum Plateau abgeflachten Spitze und schiffsförmigen Steinsetzungen sind die Hügel äußerlich größenunabhängig sehr ähnlich. Die Anlage der Gräber und Steinsetzungen in ihrem Inneren unterscheidet sich jedoch deutlich von Hügel zu Hügel. Ein Hügel kann in ein oder mehreren Bauphasen errichtet und für spätere Bestattungen erweitert worden sein. Oft findet sich jedoch auch in sehr großen Hügeln nur eine einzige Bestattung. Neolithische Anlagen konnten in der Bronzezeit Weiternutzung oder Ausbau erfahren haben, während bronzezeitliche Hügel selbst mitunter bis weit in die Eisenzeit hinein als Grabanlagen genutzt wurden. Spätbronzezeitliche Urnen wurden häufig in bestehende Hügel eingebracht, sodass viele Hügel Gräber aus zwei deutlich getrennten Phasen enthalten^[@thrane_scandinavia_2013, 752-754.]. 

Trotz der vielen erhaltenen Grabanlagen ist die Erforschung der bronzezeitlichen Bevölkerung auf Grundlage dieser Grabbefunde ein Desiderat. Die Erhaltungssituation der Knochen ist insgesamt schlecht. Zwischen Männern und Frauen sind keine systematischen Unterschiede beim Bestattungsbrauch erkennbaren, abgesehen von den etwas zahlreicheren Grabbeigaben in Männergräbern. Jedoch zeigt der Vergleich der Geschlechtsbestimmung von Brandgräbern aufgrund physisch-anthropologischer Kriterien gegenüber derjenigen aufgrund von Beigaben erstaunliche Abweichungen, die die diachrone Relevanz dieses Ergebnisses in Frage stellen. Die Beigabenmenge und -qualität scheint immerhin Aufschluss über die soziale Gliederung zu geben, da sich jenseits von einigen wenigen, absolut herausragenden "Fürstengräbern" auch regelmäßige Ausstattungsklassen andeuten: Gräber mit Goldbeigaben und Waffen lassen sich von einfacheren mit verzierten Messern, Rasiermessern und Pinzetten unterscheiden. Die Mehrzahl der Gräber enthält kein oder nur ein Metallobjekt. Der Kontrast zwischen Arm und Reich ist in der Spätbronzezeit besonders akzentuiert. Kindergräber sind sehr selten -- erst in der Spätbronzezeit finden sich vereinzelt in Urnen neben den Überresten eines Erwachsenen auch die eines Kindes. Nicht alle Bestattungen sind überhügelt oder in Hügel eingebracht, die Flachgräber verhalten sich aber abgesehen davon ebenso wie die Hügelgräber. In der Spätbronzeit wurden in Südskandinaviens auch Flachgräberfelder angelegt, je weiter südlich, desto größer^[@thrane_scandinavia_2013, 756-758.]. 

#### Benelux

Im Benelux-Areal, das hier neben den Niederlanden, Belgien und Luxemburg auch Teile Nordostfrankreichs, Frieslands und des Rheinlands einschließen soll, begegnen sich in der Bronzezeit drei Einflussspähren: Die Nordische, die Kontinentale und die Atlantische Bronzezeit. Die lokale, kulturelle Entwicklung ist in dieser Konsequenz kleinteilig und abwechselungsreich. Entscheidenden Einfluss darauf hatte die geographische Gliederung des Areals, wobei zwei wesentliche Dichotomien zu beachten sind: Der Gegensatz von Fluss- und Küstenniederungen gegenüber Pleistozänem Hochland und die Trennung in Areale nördlich und südlich der Mündungsgebiete von Maas, Rhein und Ijssel. Im Spätneolithikum und der Bronzezeit gehören die Areale nördlich und östlich dieser Flüsse dem Austauschnetzwerk der Nordischen Bronzezeit zu. Südlich und Westlich der Flüsse überwiegt der Einfluss aus Nord- und Westfrankreich sowie Großbritannien. Das Kalksteinplateau in Südostbelgien einschließlich der Ardennen lässt sich der kontinentalen Sphäre zurechnen^[@fokkens_bronze_2013, 550-551.]. 

Für das Spätneolithikum bis 2500calBC lässt sich die Situation vereinfacht folgendermaßen darstellen: Die späte Vlardingen-Kultur besiedelte die nördlichen Niederlande und die Stein Gruppe die Maas-Niederung bis zur belgischen Grenze. In den pleistozänen Höhenlagen fand sich die Einzelgrabkultur, die die Trichterbecherkultur an dieser Position abgelöst hatte. Ab 2500calBC war das gesamte Areal bis in die Ardennen Teil des Glockenbecherkomplexes, wobei sich die vormaligen kulturellen und geographischen Einheiten auch hier in Subgruppen auszudrücken scheinen. Diese Regionalität ĺöste sich nicht auf, sondern wurde am Ende der Frühbronzezeit im Kontext der späten Glockenbecherkultur in der Verteilung von Leitformen wie Wickelschnurkeramik und Riesenbecher erneut sichtbar. Ab 1850calBC, in der Mittelbronzezeit, bildeten sich im Nordosten, Westen und Süden der Niederlande neue Keramikstile heraus: Im Norden -- nördlich und östlich von Ijssel und Vechte -- Elp Keramik, südlich der Ijssel Hilversum Keramik sowie später Drakenstein Keramik mit starken Einflüssen aus Südengland und Nordwestfrankreich, im Westen Hoogkarspel Keramik. Ab 1200 war der Benelux-Raum Teil des Urnenfelder-Phänomens. Insbesonder dank der für Urnen verwandten Gefäße lassen sich aber wiederrum innerhalb desselben deutlich Keramikstile unterscheiden: Im Nordosten die Ems Gruppe, im Süden der Niederlande Einflüsse aus dem Norddeutschen Raum und im Süden Belgiens eine starke Orientierung an der Rhin-Suisse-France Oriental (RSFO) Tradition. Im Benelux Raum dauert die Bestattung auf Urnenfeldern bis zum Ende der frühen Eisenzeit und damit länger als in anderen Regionen Europas an^[@fokkens_bronze_2013, 552-553.]. 

In großen Teilen des Benelux Gebiets wurden ab 2900calBC Grabhügel errichtet, wobei diese Tradition in einzelnen Regionen, wie etwa Nordbelgien, erst ab 2600 bzw. 2000calBC zur Regel wurde. Sie hielt dann bis 1400calBC an. Im Norden und Osten des Benelux Raums waren bis 1200calBC Körperbestattungen, ab der Mittelbronzezeit in gestreckter Rückenlage, die Regel. Ab 1200 überwiegt die Brandbestattung in Urnenfeldertradition. Südlich der Maas findet ein anderer Prozess statt: Brandbestattungen wurden hier bereits im Spätneolithikum im Glockenbecherkontext praktiziert. Schon in der Mittelbronzezeit, also mehrere Jahrhunderte vor der Entstehung des Urnenfelderphänomens, wurde die Brandbestattung die vorherrschende Bestattungssitte. Im Westen der Niederlande vollzieht sich wiederrum eine andere, lokale Entwicklung: Nach 1600calBC wurden in Westfriesland keine Grabhügel mehr angelegt. Auch Urnenfelder kommen hier nicht vor. Da die Region besiedelt war und der Forschungsstand als gut gelten darf, muss davon ausgegangen werden, dass hier ein abweichender Bestattungsritus praktiziert wurde, der archäologisch nicht oder nur schwer zu erfassbar ist^[@fokkens_bronze_2013, 557-558.].

Verglichen mit den Hügeln der Nordischen Bronzezeit fielen die Grabhügel im Benelux Raum klein aus. Selten übersteigt ihr Durchmesser 15m und sie sind sämtlich weniger als 1,5m hoch. Um den Hügel herum wurden Begrenzungs- und Einhegeanlagen in Form von dicht oder locker gepackten Pfostensetzungen und/oder flachen Gräben errichtet. Diese Anlagen zeigen eine große Variabilität -- Regionalgruppen deuten sich nicht an. Die Parameter Beigabenqualität und -quantität, Hügelgröße und Komplexität der Einhegeanlage scheinen voneinander unabhängig zu sein. Grabhügel bildeten landschaftliche Bezugspunkte, in deren Nähe überproportional häufig Siedlungen anlegt, weitere Hügel errichtet oder in die weitere Gräber eingebracht wurden. Auch Urnenfelder wurden häufig um ältere Grabhügel herum angelegt. Zwischen den einzelnen Bestattungsereignissen in einem Hügel konnten lange Zeiträume vergehen, was darauf hindeutet, dass nur Mitglieder einer sozialen Elite in Grabhügeln beigesetzt wurden. Die Beigabenarmut vieler Bestattungen, besonders südlich der Maas, stellt diese Deutung jedoch in Frage. Nördlich des Rhein und im Nordwesten der Niederlande trat in der Mittelbronzezeit eine standardisierte Form der Männerbestattung auf. Die Leichname wurden als Rückenstrecker deponiert und mit einem Rapier, einem Randleistenbeil und manchmal einer Speerspitze, Arm- oder Haarringen, Pinzetten, einer Rasierklinge und Pfeilspitzen ausgestattet. Nicht zuletzt aufgrund der hohen Standardisierung der Beigaben ist die häufig vorgenommene Assoziation dieser Bestattungen mit dem Begriff "Fürstengrab" zweifelhaft^[@fokkens_bronze_2013, 558-561.]. 

In der Spätbronzezeit ab 1200calBC bis 800calBC wandelte sich die vormalige Praxis, nur einen kleinen Teil der Verstorbenen archäologisch fassbar beizusetzen. Stattdessen wurden Urnenfelder mit einer großen Zahl von Bestattungen errichtet. Die Urnen wurden zunächst in große Langbetten eingebracht, nach 1000calBC dann in vereinheitliche, kleine Hügel mit einem flachen Umfassungsgraben und einer Rampe auf der Südostseite. Obgleich sehr große Urnenfelder existieren ist die Mehrzahl überschaubar und deutet auf eine Population hin, die sich aus drei oder vier Familien gespeißt haben könnte^[@fokkens_bronze_2013, 561-562.].

#### England

Die Bronzezeit in Großbritannien und Irland erstreckte sich über einen Zeitraum von 2500-800/600calBC. Das schließt jedoch auch das lokale Chalcolithikum ein, das bis 2150calBC reicht. Die Innovation der Bronzemetallurgie verbreitete sich, erst einmal entdeckt, äußert schnell. Die Frühbronzezeit dauerte nach britischer Terminologie von 2150-1500calBC, die Mittelbronzezeit von 1500-1150calBC und die Spätbronzezeit schließlich von 1150calBC bis 800/600calBC. Die Insellage hebt die Region deutlich von den oben betrachteten Fällen ab und ist Grund für den Sonderweg, den die Entwicklung in Großbritannien und Irland im Vergleich zum Festland ging. Gleichermaßen bestanden aber auch vielfältige und tiefgreifende Verbindungen insbesondere im Kontext der Atlantischen Bronzezeit nach Nordwestfrankreich und ebenfalls entlang der in die Nordsee entwässernden Flüsse bis nach Zentraleuropa hinein. Sowohl Irland als auch Großbritannien sind durch ihre lange, abwechslungsreiche Küstenlinie geprägt. Großbritannien ist naturräumlich in landwirtschaftlich gut nutzbare Niederungslagen im Süden und Osten, in England, gegenüber unwirtlicheren Hochebenen im Westen und besonders im Norden, also in Wales und Schottland gegliedert. Doch auch in Wales und Schottland stechen einzelne Regionen durch hohes ackerbauliches Potential hervor. Irlands Küste ist vielerorts hoch und schroff. Sie umschließt nieder gelegenes Land, dessen Potential für Landwirtschaft ebenfalls im Süden und Osten am höchsten ist^[@roberts_britain_2013, 531-533.].

Im Gegensatz zu Frankreich, wo Kupfermetallurgie schon im 4. Jahrtausend bekannt war, traten die frühesten Kupferartefakte in Großbritannien und Irland erst ein Jahrtausend später um 2500/2400calBC auf. Sie waren Teil eines Innovationspakets aus Zentraleuropa, das neben Glockenbecherkeramik, steinernen Armschutzplatten, gestielten und mit Widerhaken versehenen Pfeilspitzen auch Kupferdolche und goldene Körpchenanhänger umfasste. In Großbritannien bildete sich dieses Ereignis in einer neuen lokalen Glockenbecher Tradition ab, die sich durch Einzelkörperbestattungen auszeichnete. In Irland führte der Glockenbechereinfluss nicht zu einer so tiefgreifenden Veränderung der Bestattungssitte, allerdings wurde auch hier Glockenbecherkeramik Teil von Handlungen im Kontext des Totenrituals: Sie wurde an älteren Grabanlagen deponiert und in neue Brandgräber in Grabhügeln eingebracht. Sowohl in Großbritannien als auch in Irland war die bronzezeitliche Landschaft geprägt von intentional positionierten und aufeinander ausgerichteten Monumentalanalagen. Das schließt die neuen Grabhügel für Glockenbecherbestattungen in Großbritannien und Keilgräber in Irland ebenso ein wie eine Vielzahl unterschiedlicher, nichtfunktionaler Erd-, Holz- oder Steinanlagen und neolithische Henges und Megalithanlagen. Wie in Skandinavien entstand in Großbritannien Felskunst, die ebenfalls der komplexen Rituallandschaft zugerechnet werden muss. Die Grabhügel und Monumentalanlagen in Süd- und Nordostengland, Zentralschottland sowie Ostirland und dem Orkney Archipel sind vergleichsweise größer als in anderen Regionen, strukturell aber ähnlich^[@roberts_britain_2013, 533-535.].  

Im ausgehenden 3. und beginnenden 2. Jahrtausend überwogen in Südengland Körperbestattungen in Grabhügelgruppen nach dem Modell der Wessex Kultur. Die Gräber sind teilweise reich und mit exotischen Beigaben ausgestattet. Außerhalb von Südengland herrscht eine große regionale Variabilität von Bestattungssitten in Großbritannien und Irland: In Nordengland hatten Bestattungen in Höhlen einige Bedeutung, in Ostengland Moorbestattungen. In großen Teilen Westschottlands und Irlands wurden Flachgräberfelder angelegt. Die Gräber sind einfache Gruben oder mit einer Steinkiste ausgebaut. In Irland wurden zudem auch ältere Keilgräber wiederbelegt und herausragend große Grabhügel neu errichtet. Auch hinsichtlich der Beigaben gab es klare regionale Vorlieben für einzelne Artefaktkategorien: Gagatcolliers in weiblichen Bestattungen im Norden Großbritanniens, Bernsteincolliers im Süden, sowie lokal Bronze- oder Feuersteindolche. In den verschiedenen Kontexten wurde häufig sowohl Brand- als auch Körperbestattung praktiziert, wobei die Verbrennung der Verstorbenen ab dem Beginn des 2. Jahrtausends allgemein zu überwiegen scheint. Grabanlagen wurden häufig über lange Zeiträume genutzt oder deutlich nach deren ursprünglicher Anlage wieder neu belegt. Auch Ritualanlagen wie Holz-, Stein- und Menhirkreise sowie Ring Cairns sind regelmäßig mit Bestattungen assoziiert^[@roberts_britain_2013, 535-536.].

Mitte des 2. Jahrtausends vollzogen sich sowohl in Großbritannien als auch in Irland, ganz besonders jedoch im Süden und Osten Englands, eine Reihe von Veränderungen. Die archäologische Quellenlage verschiebt sich in diesem Zeitfenster zuungunsten von Grab- und Monumentalanlagen. Stattdessen nimmt die Informationsdichte hinsichtlich Siedlungen und Subsitenz zu. Jetzt häufiger befestigte Siedlungen mit kreisförmigem Aufriss, Rundhäuser und regelmäßige, rechtwinklige Ackersysteme mit begrenzenden Gräben und Zäunen begannen die Kulturlandschaft zu dominieren. Wilde Pflanzen und Tiere verloren an Bedeutung in der Subsistenz, stattdessen ist mit der Einführung von Brunnen sowie neuen Getreiden und Hülsenfrüchten eine Intensivierung der Landwirtschaft zu beobachten. Stein, Flint und andere organische und inorganische Werkstoffe wurden als wichtigste Träger der materiellen Kultur von Gold und Bronze verdrängt. Letztere sind archäologisch allerdings auch deswegen viel sichtbarer, da sich eine ausgeprägte Deponierungstradition etablierte. Diese bildet sich jedoch nicht im stark fragmentierten und regional heterogenen Bestattungsbefund ab. Ab der Mitte des 2. bis zum Anfang des 1. Jahrtausends war die Brandbestattung die am weitesten verbreitete Bestattungsform. In vielen Regionen Englands wurden siedlungsnahe Flachgräberfelder angelegt. Die Beigabenauswahl war fast vollständig auf Gefäßkeramik beschränkt. In Irland wurden Urnengräber angelegt, parallel allerdings auch weiter bis ins erste Jahrtausend Grabhügel errichtet. Die älteren Tradition wurden langsam durch eine sehr flexible Praxis ersetzt, nach der der Leichenbrand zusammen mit unverzierten, groben Keramikgefäßen in Flachgräberfeldern, Grabhügeln, Gräben und sogar Siedlungen beigesetzt wurde. Neben den eigentlichen Brandbestattungen kommen auch Pseudogräber verhältnismäßig häufig vor. Sie wurden unter anderem auf Gräberfeldern deponiert und enthalten große Mengen verbranntes Getreide. In Schottland wurden die Brandbestattungen meist in ältere Monumente eingebracht. Im frühen ersten Jahrtausend wurde vielerorts kein archäologisch fassbares Bestattungsritual mehr praktiziert. Die Bestattungsbefunde beschränken sich auf kleine Mengen verbrannter menschlicher Knochen, die in Siedlungen, Gräben oder auf Äckern sporadisch auftreten^[@roberts_britain_2013, 537-542.]. 

## Fragestellungen

...



\pby[title={Literatur},segment=\therefsegment,heading=subbibintoc]



