# Bestattungsritus in der Europäischen Bronzezeit {#bronze-age-burial-rites}

## Wahl des Fallbeispiels

Ausgangspunkt dieser Arbeit war die Formulierung eines computerbasierten Cultural Evolution Modells. Um sich mit diesem Ansatz inhaltlich und technisch auseinander zu setzen war es unerlässlich ein Fallbeispiel heranzuziehen, das potentiell geeignet ist überhaupt durch ein solches abgebildet zu werden. Für den Kontext des Fallbeispiels sollen sich idealerweise Synergieeffekte ergeben. Das heißt, das Modell sollte geeignet sein, archäologische Fragestellungen in seinem Kontext zu beantworten oder zumindest aus einer neuen Perspektive zugänglich zu machen.

Die Wahl des Fallbeispiels hat wesentliche Konsequenzen für die Modellimplementierung. Unmittelbar funktional relevante Innovationen, die z.B. eine Veränderung der Subsistenzstrategie hervorrufen, sind anders zu analysieren als Mode in Keramikverzierung und Gewandschmuck (siehe Kapitel \@ref(stylistic-variability)). Manche Ideen sind äußerst erfolgreich, breiten sich über ganze Kontinente aus und bleiben über Jahrhunderte verhältnismäßig stabil, andere dagegen sind nur auf eine eine Siedlung beschränkt und überdauern nicht einmal ihre Schöpfergeneration. Jedes Fallbeispiel ist über eine Auswahl archäologischer Daten zugänglich. Diese sind höchst heterogen strukturiert, mit unterschiedlichen Zielsetzungen -- meist nicht der einer Cultural Evolution Analyse -- aufgenommen und decken, ebenso wie das repräsentierte Kulturverhalten, sehr verschiedene zeitliche und geographische Spektren und Skalenniveaus ab. Ideal wäre sicher, selbst Daten zu zu einzelnen Ideen und deren Entwicklung zu sammeln. Das war aber im Rahmen dieser Arbeit nicht möglich, ohne viel Zeit zu verlieren, die für theoretische Vorüberlegungen sowie die Modellimplementierung und -analyse investiert werden sollte. Die Suche nach einem Fallbeispiel war also gleichermaßen die Suche nach einem Datensatz, bei dem Anküpfungspunkte zur Modellidee zu erwarten waren.

Ein spezielles Subset der C14-Datenbank Radon-B^[@jutta_kneisel_radon-b_2013] erfüllt diese Bedingung (siehe Kapitel \@ref(radonb-dataset)). Es enthält Informationen zur zeitlichen und räumlichen Verteilung bronzezeitlicher Bestattungssitten: Die Fallstudie dieser Arbeit konzentriert sich auf vier eng verknüpfte Ideen -- Körperbestattung, Brandbestattung, Flachgrab, Hügelgrab -- die im Laufe der europäischen Bronzezeit (hier: 2200-800calBC) in Nord-, Ost und Westeuropa eine komplexe Verbreitungsgeschichte durchleben.

Brandbestattung und Körperbestattung sind Traditionen, die schon lange vor Beginn der Bronzezeit in Konkurrenz standen. Erstaunlicherweise ist dieser Konflikt bis heute nicht entschieden -- beide Bestattungsrituale, freilich immer wieder neu konnotiert und kontextualisiert -- finden in der Gegenwart in Europa Anwendung. Man könnte den Konflikt aus dieser Perspektive in seiner gesamten zeitlichen Dimension von der frühesten Vorgeschichte bis in die Moderne nachzeichnen. Er ist auch nicht auf Europa beschränkt: Diese Bestattungsformen sind derart universell, dass sie in einer Vielzahl von Kulturen auf der ganzen Welt in lokalen Ausprägungen praktiziert wurden. Dennoch konzentriert sich diese Arbeit auf die europäische Bronzezeit. Das geschieht einerseits aufgrund der zur Verfügung stehenden Daten und weiterhin aufgrund der unglaublichen Komplexität der Kulturphänomene, in die sich beide Praktiken im Laufe der Geschichte eingegliedert haben. Eine Geschichte von Brand- und Körperbestattung würde den Rahmen dieser Arbeit bei weitem sprengen, ist vielleicht überhaupt nicht sinnvoll formulierbar. Ähnlich verhält es sich mit der Grabüberhügelung: Auch dieser Brauch kann auf eine lange Geschichte zurückschauen und hat im Laufe der Zeit mannigfaltige, verwandte weil abgeleitete Rituale hervorgebracht. 

## Tod und Archäologie

*Thanatologie* ist die Wissenschaft des Todes und seiner Wirkung auf die Umwelt des Sterbenden und Verstorbenen. Sie ist interdisziplinär angelegt und beschäftigt sich mit allen biologischen, sozialen, psychologischen und sonstigen Prozessen im Kontextes des biologischen und speziell menschlichen Todes^[ @hofmann_rituelle_2008, 100.]. *Thanatoarchäologie* beschäftigt sich mit dem Tod in archäologischen Kontexten, also mit dem Niederschlag, den der Tod von Menschen im archäologischen Befund hinterlassen hat^[@hofmann_rituelle_2008, 123.] -- eine Subdisziplin mit langer Geschichte^[@hofmann_rituelle_2008, 132-140.]. Der wichtigste Befundtyp der Thanatoarchäologie ist das Grab, das umgekehrt einer der wichtigsten Forschungsgegenstände der Archäologie im allgemeinen ist. Seiner Erforschung wird vor dem Hintergrund chronologischer und sozialer Fragestellungen viel Aufmerksamkeit gewidmet. Dennoch bleibt ein großer Teil der mit Gräbern assoziierten Bedeutungsbelegung unbekannt, da Gräber sich nur aus der Wahrnehmung des Todes ihn ihrer Erzeugerkultur und deren Vorstellungen pränataler- und postmortaler Zustandsformen in Abgrenzung zum bekannten irdischen Leben verstehen lassen. Archäologische Quellen geben über diese spirituellen Abstraktionen keinen oder nur sehr eingeschränkt Aufschluss. 

Eben daraus erwächst die große Gefahr, in Ermangelung des Wissens über das Todesverständnis prähistorischer Gesellschaften moderne, westliche Vorstellungen auf archäologisch erschlossene Grabzusammenhänge zu projizieren. Ein eurozentrisches Verhalten, das die *Postprozessuale Archäologie* in Anlehnung an die *Postmoderne* als solches identifiziert hat^[@atalay_indigenous_2006]. Stattdessen muss eine Auseinandersetzung mit dem breiten Spektrum an Weltanschauungen und Wahrnehmungen erfolgen, in die Bestattungssitten eingeordnet werden können. Vollständigkeit kann dabei nicht erreicht werden, aber zumindest eine erhebliche und wertvolle Aufweitung der Perspektive.

Kerstin Hofmanns Dissertationsschrift *Der rituelle Umgang mit dem Tod -- Untersuchungen zu bronze- und früheisenzeitlichen Bestattungen im Elbe-Weser-Dreieck*^[@hofmann_rituelle_2008] enthält umfangreiche, theoretische Vorüberlegungen zur Thanatoarchäologie, die hier verarbeiten und einer kurzen Einordnung von Bestattungssitten im Kontext der Cultural Evolution Theory vorangestellt werden sollen. Damit soll einerseits einer zu simplistischen Deutung von Gräbern vorgebeugt, andererseits die Besonderheiten von Bestattungssitten als tradiertes Kulturverhalten betont werden.

### Sterben als Prozess

Die Feststellung, ab wann genau ein Mensch Tod ist, ist mit erstaunlichen Unsicherheiten und Unschärfen verknüpft. Diese nehmen ihren Anfang bei den biologischen Prozessen, die es erlauben, den Eintritt des Todes an verschiedenen Parametern zu messen und entsprechend unterschiedlich festzulegen. Leben drückt sich im Menschen in verschiedenen Körperfunktionen wie Atmung, Herzschlag oder Stoffwechsel aus. Der Ausfall eines Teilsystems bewirkt je nach seiner Relevanz mehr oder weniger schnell den Zusammenbruch aller anderen Systeme. Das kann sich über einen langen Zeitraum hinziehen: Auch im Falle des normalen, sukzessiven Ausfalls aller Teilsysteme stirbt die letzte Körperzelle viele Stunden nach dem Kreislaufstillstand. Da die Individualität eines Menschen an die intakte Funktion seines Gehirns gebunden ist, gilt der Kollaps dieses Teilsystems als eines der wesentlichen Definitionsmomente für den Eintritt des Todes. Umgekehrt kennt die Medizin mit dem Hirntod auch den Sonderfall, dass nur das Gehirn seine Funktion mit irreparablen Schäden eingestellt hat, alle anderen Körperprozesse allerdings weiter funktionieren. Der Hirntod kann nur klinisch diagnostiziert werden (Harvard-Kriterium), da in diesem Fall andere Indikatoren für den Eintritt des Todes fehlen. Letztere lassen sich grundsätzlich in unsichere und sichere pathophysiologische Kriterien untergliedern. Zu den unsicheren gehören ein Abkühlen des Körpers, Reflexlosigkeit, Erschlaffen der Muskeln, Pulslosigkeit, Atemstillstand, Leichenblässe und ein Vertrocknen an Schleimhäuten und Wunden^[@forster_stichwort_1989]. Obgleich diese traditionellen Todesanzeiger weitreichend bekannt sind und im Laufe der Geschichte wesentlich für die Feststellung des Todes waren, sind sie einzelnen oder sogar bei gemeinsamem Auftreten nicht verlässlich. Sie können (zumindest kurz- bis mittelfristig) als Folge von Erkrankungen oder Umgebungsparametern auftreten. Pulslosigkeit und Atemstillstand sind, wenn der Zustand anhält, sichere Todesanzeichen. Dazu gehören auch Totenflecken -- rötliche Verfärbungen an der Körperunterseite infolge der Unterbrechung des Blutflusses -- und die Totenstarre -- eine biochemische Körperreaktion, die zur Erstarrung der Muskulator in einem Zeifenster von 6-9 bis 50-300 Stunden nach dem Todeszeitpunkt führt. Völlig unzweifelhafte Todesanzeiger sind schließlich spätere Veränderungen an der Leiche wie Autolyse (Selbstauflösung/Selbstverdauung), Fäulnis, Mumifizierung, Fettwachsbildung und Skelettierung^[@hofmann_rituelle_2008, 92-94.].

Der mit naturwissenschaftlichen Kriterien messbare Tod ist in einer modernen, westlich geprägten Gesellschaft oftmals die entscheidende Form des Todes. Tatsächlich ergeben sich aber neben dieser biologisch-technischen auch fundamental abweichende Perspektiven, die den Tod durch seine Kontextualisierung im kulturell-sozialen Gefüge des Verstorbenen verstehen. Der Tod ist dabei der Abbruch der sozialen Beziehungen^[@hasenfratz_zum_1983]. Dieses Ereignis muss nicht mit dem biologischen Tod einhergehen. Tatsächlich kann sowohl ein biologisch Lebender aus einer Gemeinschaft ausgeschlossen und damit für "tot" erklärt werden, als auch ein biologisch Toter -- etwa im Kontext eines Ahnenkults -- weiter in zwischenmenschliche Interaktion einbezogen und wie ein Lebender behandelt werden^[@thomas_anthropologie_1975]. Vor diesem Hintergrund ist die Einschätzung ob jemand tot oder lebendig ist von kultureller Wahrnehmung abhängig:

> Niemand kann demnach eine Todesfeststellung kulturfrei vornehmen.
>
> -- @hofmann_rituelle_2008, 92.

Das Urteil, ob biologischer und sozialer Tod gleichzeitig eingetreten sind, ist darüber hinaus stark mit der Art des Todes verknüpft, die den Verstorbenen ereilt hat. Ein schneller Unfalltod, ein Mord, ein Tod in kriegerischem Konflikt oder ein langsames Dahindämmern infolge von Alter oder Krankheit werden unterschiedlich wahrgenommen und sind kulturell unterschiedlich konnotiert. Oftmals ist genau das Ausschlaggebend dafür, ob sich der Tod im Einzelfall Angehörigen und Beobachtern als schnelles, unumkehrbares Überschreiten einer Linie oder als länger andauernder Transformationsprozess darstellt. Den Rahmen für diese Unterscheidung bilden Vorstellungen von postmortalem Leben, das das irdische Leben fortsetzt oder mit ihm interagieren kann. Damit ist der Tod und seine Erfahrung eng mit grundsätzlichen, weltanschaulichen Fragen verknüpft, denen jede Kultur mit anderen Paradigmen begegnet^[@hofmann_rituelle_2008, 94-95.].

### Kulturübergreifende Wahrnehmung des Todes

Wie und mit welchen Hoffnungen und Ängsten der Einzelne dem eigenen oder dem Tod anderer Menschen begegnet, hängt von einer Vielzahl von Faktoren ab. Prägend dafür ist ein Erfahrungshorizont, der sich aus Kultur- und Religionszugehörigkeit ergibt, aber auch individuellen Eigenschaften und Erfahrungen^[@mischke_umgang_1996].

> Die Einstellung zum Tode entstehen aus der dynamischen, sich verändernden Wechselwirkung zwischen Individuum und Umwelt und sind mit dem individuellen und kollektiven Bild von Mensch, Natur und Gesellschaft verknüpft. 
>
> -- @hofmann_rituelle_2008, 96.

Nach moderner, naturwissenschaftlicher Erkenntnis muss jeder Mensch sterben. Diese Wahrnehmung hat ihren Ursprung wahrscheinlich in der Antike, ist allerdings nicht universell menschlich. In indigenen Gesellschaften wird der Tod oft als etwas unnatürliches und fremdes gedeutet, dass durch schädliche äußere Einflüsse -- etwa durch Flüche oder den Eingriff von Gottheiten -- ausgelöst wird^[@condrau_mensch_1991]. Viele Schöpfungssagen beschreiben einen Urzustand, in dem der Tod noch nicht existierte. Erst ein durch Versehen oder Unwissenheit ausgelöstes Ereignis habe ihn in die Welt gebracht^[@weis_zur_1986]. Oft wird ein "guter", von der Gemeinschaft begleiteter Tod von einem "schlechten", einsamen in der Fremde abgegrenzt^[@bradbury_representations_1996]. 

Der Glaube an ein postmortales Weiterleben ist in der Mehrzahl bekannter Kulturen verbreitet. Die Auflösung des Körpers im Anschluss an den Tod mag ein wichtiger Grund dafür sein, dass die meisten das auch mit einer Trennung von Körper und Seele in Verbindung bringen. Die Seele vollzieht einen Transformationsprozess -- eine Reise ins Reich der Toten -- der sich über einen gewissen Zeitraum hin erstreckt^[@weis_zur_1986]. Oft werden Verstorbene in diesem Übergangsstadium als gefährlich empfunden, da sie sowohl Macht als auch das Interesse zur Interaktion mit der Welt der Lebenden besitzen könnten^[@drubig_geschichte_1994]. Im Gegensatz zum Personenkonzept des westlichen Individualismus, der Menschen als Einheit aus einem Körper und einer unteilbaren Seele versteht, unterscheiden andere Gesellschaften gegebenenfalls mehrere Seelenkategorien, die im Todesfall unterschiedlich reagieren, oder etwa durch unterschiedliche Rituale wie Kremation freigesetzt werden müssen^[@graslund_prehistoric_1994]. Unabhängig davon ist die Seele jedoch in vielen Weltanschauungen die Entität, die im Jenseits weiterlebt. Das Totenreich ist in verschiedenen Kulturen mit vielfältigen Assoziationen belegt -- häufig mit dem Bild des Schlafens, einer spiegelbildlichen Parallelwelt zum irdischen Dasein oder mit Mechanismen, die Ausgleich und Sühne schaffen sollen^[@stubbe_trauerverhalten_1988]. Kulturen, die ein Reinkarnationskonzept verinnerlicht haben, verstehen den Tod meist nur als eine kurze Phase zwischen zwei Daseinsformen^[@payer_stichwort_1998].

In ausnahmslos allen Kulturen gibt es ein Totenbrauchtum, das den Umgang mit Verstorbenen regelt. Die praktizierten Handlungen wie Leichnamsvorbereitung, Bestattung, Totenmahlzeit, Besuchsfeste oder Wiederbestattungen sind höchst vielfältig und stark von den oben beschriebenen, ideologischen Voraussetzungen abhängig. Ebenso sind Zweck und Bedeutung der Riten unterschiedlich. Sie zeigen jedoch kulturübergreifend einige Gemeinsamkeiten^[@macho_stichwort_1997] und richten sich grundsätzlich sowohl an die Toten als auch die Lebenden. Viele Rituale dienen dazu, das emotionale Trauma und die Trennung zu verarbeiten. Darüber hinaus soll der Zusammenhalt der Bestattenden sozialen Gruppe auch über den Tod des Verstorbenen hinaus aufrecht erhalten werden^[@gladigow_naturae_1997; @hasenfratz_zum_1983]. Dabei kanalisieren die rituellen Handlungen den kritischen Übergangsprozess von der dauerhaften An- zur Abwesenheit des Individuums. Bestattungsbräuche können auch aus einer Angst vor dem Toten hervorgehen und dazu dienen, ihn zu bannen, zu besänftigen oder zumindest seinen Einfluss auf die Lebenden zu verringern^[@lauf_im_1997]. Umgekehrt existiert mit der Totenfürsorge ein Verhalten, den Verstorbenen mit Grabbeigaben für sein postmortales Dasein auszustatten oder ihn mit Wegzehr für die Reise ins Totenreich zu versehen^[@nebelsick_doppelte_1995]. Bestattungsrituale können auch dazu dienen formalisiert zu Erinnern und eine bestimmte Form der Erinnerung an den Toten zu konstruieren. Weltanschauung und Moralvorstellungen können gegebenenfalls in der Gruppe durch Repetition und den besonderen Charakter des Anlasses vertieft werden. Eben hieran wird deutlich, dass Bestattungssitten nicht losgelöst, sondern in den religiösen, sozioökonomischen, politischen und sonstigen Kontexten einer Gesellschaft verankert sind. Umfang und Komplexität einer Beisetzung hängen oft stark von der Ausprägung der sozialen Hierarchien und der individuellen Position des Verstorbenen darin ab^[@harke_final_1997]. Totenbrauchtum ist mit anderen Subsystem der Gesellschaft verschalten und kann diese widerspiegeln^[@hofmann_rituelle_2008, 96-99.].

### Thanatoarchäologie

Prähistorisches Kulturverhalten lässt sich nur über das Medium archäologischer Quellen erschließen. Materielle Kultur spiegelt den eigentlichen Forschungsgegenstand allerdings nur mehrfach und stark gefiltert wieder. Selbst ihre eigene Bedeutung lässt sich nur indirekt und unvollständig rekonstruieren. Dieser Problematik widmet sich ein großer Teil der theoretischen, archäologischen Forschung^[@hofmann_rituelle_2008, 123-128.]. Wie oben ausgeführt sind Handlungen, die mit dem Tod in Verbindung stehen, meist besonders bedeutungsgeladen und deswegen schwer aus den zur Verfügung stehenden Daten rekonstruierbar^[@harke_nature_1997]. Schrift- oder ikonographische Quellen, die Aufschluss über das Totenritual oder sogar die zugrunde liegende Vorstellungswelt geben würden, existieren in der prähistorischen Archäologie nicht oder sind äußerst selten.

Die wichtigsten Befundtypen der Thanatoarchäologie sind Gräber -- einzeln oder im Kontext von Gräberfeldern und sonstigen Kollektivgrabanlagen. Im Kontext von Gräberfeldern können oft neben den eigentlichen Bestattungseinrichtungen auch Gruben, Steinpflaster, Ustrinen (Verbrennungsplätze, an denen Scheiterhaufen errichtet wurden) und aufgehende Strukturen wie Zäune, Grabmarkierungen oder Ritualaufbauten dokumentiert werden^[@fischer_vom_1996]. Selbst im Fall von datierbarer Gleichzeitigkeit müssen jedoch nicht alle Befunde auf einem Gräberfeld mit dem Totenbrauchtum in Verbindung stehen. Umgekehrt haben nicht alle Handlungen eines Bestattungsrituals in räumlicher Nähe zum Bestattungsplatz stattfinden müssen. Auch die Anlage von Gräbern ist nicht obligatorisch: Viele Bestattungsrituale sehen keine Grabarchitektur vor und manche schließen den eigentlichen Leichnam aus der Deponierung aus^[@hausler_zur_1975]. Solche Pseudogräber oder Kenotaphe sind schwer von Hortfunden unterscheidbar und werden meist nur über ihre Position auf dem Gräberfeld identifiziert. Siedlungsbestattungen sind in wenigen Kulturzusammenhängen die Regel, treten aber immer wieder auf^[@veit_studien_1998]. Sie erlauben eine besondere Kontextualisierung der Bestattung über die räumliche Verknüpfung zu Siedlungsarealen oder Haushalten^[@hofmann_rituelle_2008, 128-129.].

Menschliche Überreste finden sich auch außerhalb von intentionell angelegten Gräbern -- etwa als Konsequenz unnatürlicher Tode durch Unglücke, Naturkatastrophen oder Gewalt. Auch diese Quellen sind Teil der thanatoarchäologischen Forschung, müssen aber anders interpretiert werden. Aufgrund schlechter Erhaltungssituation durch stärkere taphonomischer Einflüsse sowie Unsicherheiten über das Kulturverhalten vormoderner Menschen ist die Entscheidung, ob ein Leichnam in einem Ritual bewusst niedergelegt oder schlicht zufällig durch Sedimentbedeckung konserviert wurde besonders in der paläolithischen Archäologie oftmals schwer^[@hofmann_rituelle_2008, 145-147.]. 

Neben Siedlungen, Horten und Einzelfunden gehören Gräber zu den Hauptkategorien archäologischer Quellengattungen. Gräber und Depots heben sich von Siedlungen ab, da sie grundsätzlich eine positive Artefaktauswahl einschließen, das heißt, die eingebrachten Objekte wurden intentional in diesem Kontext platziert^[@eggers_einfuhrung_1959]. Diese Intentionalität gilt auch für den Grabaufbau. Gräber sind also hochgradig bedeutungsgeladene Befunde, die als Überrest der rituellen Handlungen des Totenbrauchtums konserviert werden. Sie bilden religiöse, soziale und politische Strukturen, Werte und Normen einer Gruppe ab -- allerdings stets schematisiert und gegebenenfalls bewusst manipuliert^[@harke_final_1997; @humphreys_comparative_1981; @palgi_death_1984]. Die Vielzahl an Filtermechanismen, die zwischen der Lebensrealität einer prähistorischen Gesellschaft und dem archäologisch fassbaren Befund wirken, werden bei der Rekonstruktion von Sozialstrukturen oftmals nicht ausreichend reflektiert. Das ist umso mehr relevant, wenn aus den statischen archäologischen Quellen dynamische, chronologische Entwicklungen und Transformationsprozesse abgelesen werden sollen^[@hofmann_rituelle_2008, 128-132.].  

##### Gräber in Landschaften

Menschen trafen in der Vorgeschichte immer wieder neu eine Entscheidung für die Position eines Bestattungsplatzes im natur- und kulturgeographischen Raum. Der Entscheidungsprozess erschließt sich aus einer landschaftsarchäologischen Perspektive, die einerseits natürliche Gegebenheiten wie Topographie, Vegetation oder Wassernähe am Bestattungsplatz sowohl absolut als auch in Relation zu damit wahrscheinlich verknüpften Siedlungen betrachtet, als auch die kulturhistorischen Bezüge zu kontemporärer oder vorangegangener menschlichen Aktivität in der Umgebung^[@balee_historical_1998]. Das erfordert eine grundsätzlich mit Unsicherheiten behaftet Rekonstruktion der Landschaft zum Zeitpunkt der Anlage des Bestattungsplatzes. Funktionale Kriterien wie das Meiden von hochwassergefährdeten Flächen oder Arealen mit schwacher Bodendecke mögen zu einer Vorauswahl der Plätze geführt haben. Darüber hinaus sind dem Feld ideologischer Konnotationen keine Grenzen gesetzt^[@artelius_bronze_1998; @stjernquist_introduction_1992-1]. Das kann zum Beispiel zur Beachtung astronomischer Relationen oder einer bewusst erzeugten über- oder unterbetonten Sichtbarkeit der Anlage führen. Ein Bestattungsplatz ist schließlich selbst landschaftsprägend^[@enninger_friedhofe_1989]: Grabanlagen können Territorien abgrenzen oder Wege markieren. Die Aufgabe eines Gräberfelds, seine kontinuierliche Nutzung oder die Wiederaufnahme der Nutzung einer alten Anlage, die gegebenenfalls aus einem vorangegangenen, archäologischen Kulturzusammenhang stammt, geschieht oft in einem Prozess, der mit anderen schwerwiegenden Veränderungen in einer Siedlungsgemeinschaft korreliert^[@hofmann_rituelle_2008, 145-149.].  

##### Gliederung von Gräberfeldern

Jenseits der Frage nach der Position des Bestattungsplatzes stellt sich eine weitere nach der inneren Gliederung desselben. Wird ein Areal neu für diesen Zweck erschlossen, ist es zunächst meist ohne Einrichtungen, die als kulturelle Bedeutungsträger fungieren. Erst die Nutzung für Bestattungen führt zu einer langsamen Akkumulation von -- aus archäologischer Perspektive -- Befunden^[@koch_geschichte_1989]. Architektur wie Grabanlagen oder Ritualstellen können über längere Nutzungszeiträume erneuert, umgebaut oder entfernt werden. Gräber können einzelnen in individuellen Einrichtungen wie Gruben oder Kisten für sich stehen oder durch Konstruktionen wie Grabhügel, Kammern in Megalithbauten oder Einhegungen zu Einheiten zusammengefasst werden. Letztere führen zu einer Gliederung des Bestattungsplatzes in nach verschiedenen, oft unbekannten Kriterien zusammengehörige Grabkomplexe. Auch die Anordnung von Einzelgräbern auf Gräberfeldern ist in der Regel nicht zufällig und wird unter dem Stichwort der Horizontalstratigraphie archäologisch diskutiert: Durch das sukzessive Sterben von Mitgliedern einer Siedlungsgemeinschaft stellt sich aus Sicht der Bestattenden für jeden Toten erneut die Frage der Platzierung in Relation zu den bereits vorhandenen Gräbern. Häufig bilden sich in der Verteilung der Gräber die chronologische Entwicklung des Gräberfelds ab, aber auch andere Kategorien wie biologische und soziale Gruppengliederung, Alters- und Geschlechtsunterschiede sowie Unterschiede im Rang der Verstorbenen in einer vergangenen soziopolitischen Hierarchie können sich hier niederschlagen^[@derks_geschlechtsspezifische_1993; @mchugh_theoretical_1999; @veit_tod_1997]. Ausdruck dieser Kategorien sind räumliche Verteilungsmuster der Gräber in denen Merkmalsvariation von einem Zentrum aus oder entlang einer Achse nachvollzogen werden können, merkmalsgleiche Gruppen zu voneinander getrennten Clustern akkumulieren oder Außreißer mit positiv oder negativ herausragenden Eigenschaften getrennt von der Hauptgruppe platziert wurden. Eine weitere Beobachtungsgröße ergibt sich daraus, ob Gräber in andere Gräber eingreifen und diese stören. Das kann bewusst vermieden werden, zufällig in Einzelfällen auftreten oder ein Gräberfeld als Charakteristikum auszeichnen. Auch die Beraubung von Gräbern nach der Beisetzung kann Teil des Bestattungsrituals sein und die innere Gliederung eines Bestattungsplatzes sowie die Grabarchitektur beeinflussen^[@hofmann_rituelle_2008, 149-151.].

##### Bestattungsform und Grabbau

Die vorliegende Arbeit betrachtet mit den Dichotomien Brandgrab vs. Körpergrab sowie Hügelgrab vs. Flachgrab Aspekte von Bestattungsform und Grabbau. Diese Kategorien dürfen als besonders bedeutungsgeladen verstanden werden: Sie sind kulturell deutlich unterschiedlich und ihre Merkmale besitzen meist starken, symbolischen Aussagewert^[@kaliff_grave_1998]. Auch innerhalb von Kulturzusammenhängen herrscht große Variabilität -- ein möglicher Indikator für die Intensität sozialer Reglementierung des Bestattungsrituals. Das erschwert eine umfassende Klassifizierung, die in der Lage wäre alle Phänomene aufzunehmen. Wesentliche Gliederungsgrößen sind Ein- und Mehrphasigkeit sowie Partielle und Vollständige Bestattung, darüber hinaus ergeben sich aus der Architektur des Grabbaus sowie der Art der Deponierung des Leichnams Unterscheidungskriterien^[Hofmann sammelt einige der wichtigsten Kategorien in einer tabellarischen Aufstellung: @hofmann_rituelle_2008, 152.]. Grabanlagen besitzen in der Regel eine innere, unsichtbare Struktur und einen sichtbaren, oberirdischen Aufbau^[@skjoldebrand_variations_1995]. Das Innere des Grabes ist oft nur während der Errichtung und im Moment der Beisetzung offen und zugänglich. Es adressiert entsprechend neben dem Toten und angenommener Entitäten der postmortalen Welt vor allem die Bestattenden und eventuelle Zuschauer der Bestattungszeremonie. Der dauerhaft sichtbare Teil des Grabes hat einen potentiell größeren Adressatenkreis und damit oft einen anderen Symbolgehalt. Grabformen können -- müssen jedoch nicht -- Strukturen im sozialen Gefüge der Lebenden widerspiegeln, indem für Verstorbene aus verschiedenen sozialen Gruppen jeweils unterschiedliche Grabformen genutzt oder indem besondere Individuen in von der Norm abweichenden Sondergrabformen beigesetzt werden^[@hodder_social_1980]. In vielen Gesellschaften werden für Führungspersonen und deren Verwandten aufwendigere und auffälligere Gräber errichtet, während fremde und soziale Außenseiter gegebenenfalls deutlich einfacher oder anderweitig ungewöhnlich bestattet werden^[@pauli_ungewohnliche_1978]. Diese Hierarchien -- und andere, oben schon genannte Parameter, können sich in völlig unterschiedlichen Bestattungssitten innerhalb eines Kulturzusammenhangs ausdrücken (viele Beispiele dafür in Kapitel \@ref(regions-archaeological-overview)). Kollektivgräber nivellieren soziale Hierarchien: Die archäologische Forschung bringt sie häufig mit einem betonten Gemeinschaftsdenken und egalitären Gesellschaftsformen in Verbindung. Bestattungsform und Grabbau bieten die Möglichkeit, nicht nur Einblicke in die soziale Organisation sondern auch die spirituelle Vorstellungswelt einer archäologischen Kultur zu gewinnen. Zwar sind mit ein und der selben Religion durchaus unterschiedliche Grabriten vereinbar und eine plakative Trennung der Vorstellungen, die zum Beispiel hinter Körper- und Brandbestattungen stehen mögen, ist nicht haltbar^[@portmann_sterben_1993]. Bestimmte Rituale, wie etwa eine aufwändige Mumifizierung, geben allerdings begründeten Anstoß zur Vermutung, die Unversehrtheit des Körpers spiele in der Jenseitsvorstellung der entsprechenden Kultur eine entscheidende Rolle. In verschiedenen Kulturzusammenhängen erwecken Gräber, die als Totenhäuser gestaltet sind oder hausförmige Urnen enthalten, den Eindruck, die Toten würden in ihren Gräbern wie in Häusern weiterleben. Die systematische Orientierung des Körpers in Relation zu den Himmelsrichtungen tritt auf prähistorischen Gräberfeldern häufig auf und könnte mit einer religiösen Begründung gut erklärt werden. Der Grabbau kann auch durch die Angst vor dem Toten beziehungsweise dessen Eingriffe in die Welt der Lebenden bestimmt sein. Das kann sich dadurch ausdrücken, dass der Leichnam bewusst mit schweren Steinen bedeckt oder gefesselt wird^[@hofmann_rituelle_2008, 151-156.].

##### Grabbeigaben

Jenseits von Bestattungsform und Grabbau konzentriert sich die archäologische Erforschung von Gräbern vor allem auf die Grabausstattung, also jene Artefakte und Überreste, die bei der Beisetzung intentionell in das Grab eingebracht wurden. Aufgrund taphonomischer Gegebenheiten muss das nicht für alle Funde aus dem Grabkontext gelten^[@ravn_use_2000]. Außerdem erhalten sich bestimmte Materialkategorien weniger gut oder besser als andere und sind entsprechend im archäologischen Befund über- oder unterrepräsentiert. Grabbeigaben können und müssen hinsichtlich ihrer Bedeutung nach verschiedenen Kriterien untersucht werden. Bestimmte Objekte wurden nur für den Bestattungskontext hergestellt, andere dem Materialkreislauf der Lebenden bewusst entzogen. Artefakte können Teil des Grabbaus sein, zur persönlichen Ausstattung und Tracht des Verstorbenen gehört haben oder als sonstige Beigaben in den Grabkontext eingebracht worden sein. Letztere können beispielsweise als Gebrauchsgegenstände für den Toten in seiner postmortalen Existenz verstanden werden, als durch den Tod verunreinigt gelten oder zur Selbstdarstellung der Hinterbliebenen im Bestattungsritual präsentiert werden^[@harke_beigabensitte_2003]. Aus archäologischer Perspektive ist es oft sehr schwierig die Motive hinter der Deponierung einer einzelnen Beigabe zu erschließen. Der potentielle Symbolgehalt von Form, Farbe und Verzierung der Artefakte bringt weitere Unsicherheiten mit sich. In der archäologischen Literatur werden beispielsweise immer wieder einzelne Artefakte als Amulette angesprochen. Meist handelt es sich um Einzelstücke ohne erkennbaren, funktionalen Nutzen, die nah am Leichnam platziert wurden^[@thrane_stichwort_1973]. Sie könnten sowohl Funktionen als Glücksbringer für den Toten als auch als Bannmittel zum Schutz der Lebenden übernommen haben. Nahrungsbeigaben sind in rezenten Kulturen oft mit der Vorstellung einer Reise ins Jenseits verknüpft: Der Verstorbene hätte entsprechend auch nach dem Tod noch Bedarf nach physischer Nahrung. Diese Assoziation ist allerdings nicht zwingend: Nahrungsbeigaben können auch schlicht eine weitere Ausdrucksform für die soziale Identität des Toten sein. Interpretationsansätze für Grabausstattungen betonen meist den Aussagewert der Beigabensammlung für die Identität des Bestatteten. In der Regel werden Unterschiede in der Qualität und Quantität von Beigaben mit dem vertikalen sozialen Status einer Person oder Gruppe in Verbindung gebracht. Insbesondere Prestigegüter -- auffallende Einzelobjekte aus heute als wertvoll erachteten Materialien^[@bernbeck_prestige_1996] -- werden in diesem Kontext betont betrachtet. Beigaben können auch die Zugehörigkeit unter anderem zu einem sozialen Geschlecht, einer Altersgruppe, einem Berufszweig oder einer Herkunftsregion ausdrücken. Zuordnungen dieser Art lassen sich mit physisch-anthropologischen oder naturwissenschaftlichen Daten korrelieren und so gegebenenfalls verifizieren. Allerdings kann sowohl eine Person mehrere Identitäten in sich vereinen als auch ein Artefakt mit mehreren Bedeutungsebenen verknüpft sein. Die Auszeichung von eindeutigen Leit- oder Faziesartefakten kann zwar statistisch relevant, im Einzelfall aber auch irreführend sein und zu Zirkelschlüsse führen^[@hofmann_rituelle_2008, 156-165.].

## Bestattungsriten und Cultural Evolution

Betrachtet man Bestattungsriten als in Raum und Zeit verbreitetes Kulturverhalten aus der Perspektive der Cultural Evolution oder Cultural Transmission Theory, so ergeben sich einige besondere Implikationen. Folgt man der von @dunnell1978style vorgeschlagenen Unterscheidung von *Style* und *Function*, so hat sich Evolutionary Archaeology vor allem auf die Extreme dieses Spektrums konzentriert (siehe Kapitel \@ref(stylistic-variability) und  \@ref(cultural-niche-construction)). Bestattungssitten sind jedoch weder funktional -- obgleich auch aus hygienischer Perspektive und hinsichtlich Materialkosten und Arbeitszeit für oder gegen bestimmte Rituale argumentiert werden kann -- noch sind sie Mode, die leichtfertig und ohne Reflexion übernommen wird. Der Tod von Angehörigen ist meist ein schwerwiegendes Ereignis, das mit einem besonderen religiösen, kulturellen und individuellen Verarbeitungsprozess einhergeht. Bestattungssitten gehören eben zu diesem Verarbeitungsverhalten und sind als solche Gegenstand ihrer Erforschung.

Diese Qualität als mit dem Tod assoziiertem Verhalten rückt Bestattungssitten in die Sphäre von Ritual und Religion. Die archäologische Auseinandersetzung mit diesen Themengebieten ist zwar umfangreich^[@bertemes_archaeology_2001; @chapman_archaeology_1981; @insoll_archaeology_2004; @renfrew_archaeology_1994], leidet aber am Dilemma der Datengrundlage, tut sich schwer damit, falsifizierbare, wissenschaftliche Aussagen hervorzubringen und wird durch die inflationäre Verwendung von Ritual als Erklärung für unverständliche Befundsituationen in unzähligen Fallstudien in Frage gestellt. Auch im Cultural Evolution Kontext ist Religion viel Aufmerksamkeit zugekommen, selbst wenn man die antireligiösen Stimmen beiseite lässt, die rund um Dawkins Memetik laut geworden sind (siehe Kapitel \@ref(memetics)) und ihren wissenschaftlichen Anspruch für Gesellschaftskritik aufgegeben haben. Joseph Watts Dissertation *The Cultural Evolution of Religion: A phylogenetic approach*^[@watts_cultural_2016] gibt einen aktuellen Überblick über *Evolutionary Religious Studies*, der hier schlicht aufgrund seines Umfangs nicht nachvollzogen werden kann. Religion ist eine bemerkenswerte Kategorie des menschlichen Verhaltensspektrums, da die in sie investierten Kosten an Zeit, Arbeit und intellektueller Kapazität ihren Nutzen scheinbar signifikant übersteigen. Ihre Erforschung aus evolutionärer Perspektive hat also vor allem den Anspruch, ihre Entstehung trotz dieses Missverhältnisses zu erklären^[@wilson_evolutionary_2012-1]. Dabei haben sich mit *by-product accounts* und *functional accounts* zwei Schulen herausgebildet: Erstere konzentiert sich auch die kognitive Veranlagung des Menschen, religiös oder spirituell aufgeladene Information leicht zu erzeugen, aufzunehmen und zu verarbeiten^[@barrett_exploring_2000; @baumard_explaining_2013; @boyer_evolutionary_2008], während letztere nach den Selektionsvorteilen religiöser Strukturen und Verhaltensmuster sucht^[@norenzayan_cultural_2016; @sosis_adaptationist-byproduct_2009; @wilson_darwins_2002]. 

Tod und Ableben waren selten explizit Gegenstand der Cultural Evolution Forschung^[@falger_cultural_2003]. Auch in der Evolutionary Archaeology beschäftigten sich wenige Beiträge mit diesem Themenkomplex: ein Desiderat. Im folgenden sollen einige wesentliche Gedanken dreier Artikel genannt werden, die jeweils einzelne Aspekte von Tod und Ritual beleuchten, ohne allerdings Bestattungsriten aus Cultural Evolution Perspektive vollständig zu charakterisieren. Diese Aufgabe verbleibt für die Zukunft und kann erst auf Grundlage von explizit darauf ausgerichteten Fallstudien gelingen.

### Atkinson und Whitehouse: Ritualvielfalt

Atkinsons und Whitehouses Beitrag *The cultural morphospace of ritual form: Examining modes of religiosity cross-culturally*^[@atkinson_cultural_2011] zeichnet sich gegenüber vielen anderen anthropologischen Untersuchungen zu Ritual und Religion durch den Versuch der Quantifizierung aus. Aus den Human Relations Area Files^[http://hraf.yale.edu [06.10.2018]] stellen sie einen Datensatz zusammen, der geeignet ist, einige Grundaussagen zur Natur des menschlichen Ritualverhaltens aufzustellen und zu prüfen. Rituale lassen sich grundsätzlich hinsichtlich zweier Dimensionen kategorisieren: Häufigkeit des regelmäßigen Wiederholens (*frequency*) und Intensität der Wirkung auf die Teilnehmer (*arousal*). Kleine, homogene Gruppen praktizieren eher seltene (*low-frequency*), aber eindrücklichen (*high-arousal*) Rituale, während größere, stärkere sozial zentralisierte Populationen zu häufigeren (*high-frequency*), aber weniger emotionalen (*low-arousal*) Ritualen tendieren. Gruppengröße und Struktur korrelieren also mit der Natur der in einer Gesellschaft verbreiteten Rituale. Die emotionale Erregung, die mit einem Ritual einhergeht ist im Bevölkerungsdurchschnitt in der Regel entweder positiv oder negativ, also mit Euphorie oder Dysphorie assoziiert. Der Übergang von einer wildbeuterischen zu einer landwirtschaftlichen und dann zu einer komplexer stratifizierten Gesellschaftsstruktur scheint mit einer Zunahme häufiger und niederschwellig negativ konnotierter Rituale einherzugehen.

### Henrich: Kostenaufwändige Demonstration

Joseph Henrichs Artikel *The evolution of costly displays, cooperation and religion: credibility enhancing displays and their implications for cultural evolution*^[@henrich_evolution_2009] beschäftigt sich mit der Bedeutung und Entstehung von kostenaufwändigem Repräsentativverhalten wie Tieropfer, rituelle Verstümmelung oder Märtyrertum. Henrich erklärt diese Phänomene aus Cultural Evolution Perspektive mit Bezug auf Biased Transmission (siehe Kapitel \@ref(biased-transmission)): Menschen können Manipulation durch ihre kulturellen Vorbilder vermeiden, indem sie deren Aussagen dann mehr Gewicht geben, wenn die Kommunikation derselben mit persönlichen Kosten verknüpft ist. Demnach bevorzugen Lernende diese Form der Kommunikation und erzeugen Selektionsdruck hin zu aufwändigen Demonstrationen von Authentizität. Henrich demonstriert die Konsequenzen dieses Modells in einer computerbasieren Simulation, die relavante Parameter besser zugänglich macht. Die Konkurrenz zwischen Gruppen und Institutionen innerhalb von Gruppen scheint ein wichtiger Anreiz zur Konsolidierung, Intensivierung und  

Part III explores how cultural evolution, driven by competition among groups or institutions stabilized at alternative sets of these interlocking belief-practice combinations, has led to the association of costly acts, often in the form of rituals, with deeper commitments to group beneficial ideologies, higher levels of cooperation within groups, and greater success in competition with other groups or institutions. I close by discussing the broader implications of these ideas for understanding various aspects of religious phenomena.

### MacDonald: Trauer als abhängige Variable

Douglas MacDonalds *Grief and Burial in the American Southwest: The Role of Evolutionary Theory in the Interpretation of Mortuary Remains*^[@macdonald_grief_2001] nutzt ein evolutionäres Erklärungsmodell um eine modellhafte Beziehung zwischen Umfang und Komplexität einzelner Instanzen eines Bestattungsrituals und Variablen wie Alter und sozialer Verknüpfung des bestatteten Individuums zu formulieren. 

Evolutionary theory, in consort with Marxism and processualism, provides new insights into the interpretation of grave-good variation. Processual interpretations of burial sites in the American Southwest cite age, sex, or social rank as the main determinants of burial-good variation. Marxist theorists suggest that mortuary ritual mediates social tension between an egalitarian mindset and an existing social inequality. Evolutionary theory provides a supplementary explanatory framework. Recent studies guided by kin-selection theory suggest that humans grieve more for individuals of high reproductive value and genetic relatedness. Ethnographic examples also show that individuals mourn more intensively and, thus, place more social emphasis on burials of individuals of highest reproductive value (young adults). Analysis of grave goods from La Ciudad, a Hohokam site in the American Southwest, supports the hypothesis that labor value, reproductive value, and grief contributed to grave-good differentiation. At La Ciudad, individuals between the ages of 10 and 20 possessed more and higher-quality grave goods on average than any other age group. Grief at the loss of a young adult of high reproductive and labor value may facilitate explanation of mortuary variation at La Ciudad, as well as other sites in the greater Southwest and beyond.
