# Resümee

Im Einführungskapitel wurden sechs Ziele formuliert, die mit dieser Arbeit erfüllt werden sollten. Sie sollen im folgenden abschließend zusammengefasst werden:

**Cultural Evolution** \newline 
Die Übertragung von Mechanismen und Methodik zur Erforschung der natürlichen Evolution auf Kulturverhalten wurde im Kontext der frühesten Formulierungen von Evolutionstheorie im 18. Jahrhundert diskutiert. Forschungsgeschichtlich lässt sich eine Entwicklung von *Evolutionsismus* (und *Sozialdarwinismus*) über die Kritik durch den *Kulturrelativismus* hin zum *Neoevolutionismus* nachzeichnen. Ab Mitte der 1970 Jahre fand eine inhaltliche und strukturelle Diversifizierung der Ansätze statt, aus der *Evolutionary Psychology*, *Human Behavioural Ecology* und *Dual Inheritance Theory* (letztere mit der Subdisziplin *Memetik*). *Cultural Evolution* Forschung hat heute ein breites, fächerübergreifendes Forschungsfeld mit Schwerpunktthemen wie *Cultural Complexity*, *Social Learning* oder *Cultural Transmission*. *Evolutionary Archaeology* inkorporiert und appliziert Terminologie und Methodik aus diesem Feld und bereichert es um eine diachrone Perspektive. 

**Thanatoarchäologie** \newline 
*Thanatoarchäologie* beschäftigt sich mit dem Tod in archäologischen Kontexten, also mit dem Niederschlag, den der Tod von Menschen im archäologischen Befund hinterlassen hat. Ihr wichtigster Befundttyp ist das Grab, das aus verschiedenen Perspektiven archäologisch erforscht werden kann: Seine Position in der (Kultur)Landschaft, seine Anordnung in Relation zu anderen Gräbern, seine Beigabenausstattung und schließlich seine Form und sein Aufbau. Gräber sind intentioneller Ausdruck von Ideologie und und somit nur aus ihrem kulturellen und individuellen Kontext zu verständlich. Archäologie verfügt meist nicht über eine hinreichende Quellenlage, um dem gerecht zu werden.

**Bestattungssitten als Kulturverhalten** \newline 
Bestattungssitten sind eine besondere Kategorie von Kulturverhalten, da sie weder als funktionales Verhalten zur Sicherung des Überlebens dienen, noch als simple Mode leichtfertig und ohne Reflexion ausgetauscht werden. Als mit dem Tod assoziiertes Verhalten reichen Bestattungssitten weit in die Sphären von Ritual und Religion hinein. Eine Charakterisierung dieser Rituale aus Perspektive der *Evolutionary Archaeology* steht aus, jedoch lassen sich einige Beobachtungen vorweg nehmen: Bestattungen sind emotional negativ aufgeladene Rituale, die je nach Gruppengröße häufig aber unregelmäßig stattfinden und damit Teil der Etablierung dogmatischer Religionen sein können. Bestattungsrituale sind häufig kostenaufwändiges Repräsentationsverhalten, dass vor allem die Trauergemeinde addressiert. Die Intensität der Trauer um Verstorbene folgt auch einer biologischen, kulturunabhängigen Prädisposition des Menschen.

**Archäologischer Überblick** \newline 
Im Laufe der europäische Bronzezeit wurden viele unterschiedliche Bestattungsformen praktiziert. Zur Kategorisierung derjeniger, die sich archäologisch fassen lassen, eignet sich die mit den Variablen *burial type* und *burial construction* vorgenommene Gliederung in Brand- oder Körper, bzw. Flach- oder Hügelgrab. In der Frühbronzezeit sind Körperbestattungen wesentlich häufiger, Brandbestattungen treten in Ungarn, im Benelux-Raum und in Großbritannien jedoch in durchaus signifikantem Umfang auf. Die Anlage von Hügel- oder Flachgräbern ist regional stark unterschiedlich verbreitet. In der Mittelbronzezeit gewinnt Totenverbrennung langsam, Grabüberhügelung massiv an Relevanz -- *Hügelgräberzeit*. Die Spätbronzezeit ist dominiert von Brandbestattungen der *Urnenfelderkultur*.

**Datenauswertung** \newline 
Radon-B ist eine Datenbank mit ^14^C-Datierungen aus der Bronze- und frühen Eisenzeit Europas. Für diese Arbeit wurden Daten von Gräbern extrahiert, die mit Metainformationen zu *burial type* und *burial construction* versehen sind. So ließ sich ein Proxy zur diachronen Entwicklung der regionalen Verhältnisse der Ausprägungen dieser Variablen errechnen. Radon-B hat strukturelle Defizite und repräsentiert die reale Entwicklung nicht durchgehend korrekt -- wurde allerdings auch nicht für diese Anwendung zusammengestellt. Betrachtet man das diachrone Verhalten eines Maßes zwischenregionaler Kulturdistanz, zeigt sich, dass die Distanzen der Primärvariablen nicht miteinander und beide nur in der Frühbronzezeit mit der räumlichen Distanz korrelieren. Das ist erstaunlich und erfordert eine Erklärung jenseits des einfachen *Diffusion of Innovation* Paradigmas.

**Simulation** \newline 
Donec eu risus scelerisque, interdum libero ac, ultrices diam. Nam non euismod dolor. Donec egestas elit eget elit gravida posuere. Proin dignissim at tortor eu semper. Aliquam a libero non sem porttitor blandit non eget nunc. Maecenas tempus tortor ac ligula ultricies auctor. Sed tempor urna in ipsum suscipit mattis. Nunc blandit leo quis ex posuere, a vehicula lectus ultricies. Pellentesque pretium nulla quis tortor varius vestibulum. Cras finibus elit id ex porta luctus. Aenean enim velit, pellentesque sagittis tortor non, tempor ultricies leo. Duis ultricies consectetur purus, vel porttitor dui viverra vel. Curabitur ac ipsum rutrum, dignissim velit eget, tincidunt leo. Mauris suscipit lacus risus, vel dapibus enim cursus vitae.
